using Content.Shared._CE.ResourceManager;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.ResourceManager;

[GenerateTypedNameReferences]
public sealed partial class CEResourceRequirementControl : Control
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    public CEResourceRequirementControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public CEResourceRequirementControl(CEResourceRequirement requirement) : this()
    {
        NameLabel.Text = requirement.GetRequirementTitle(_proto);
        Icon.SetLayers(requirement.GetRequirementIcon(_entity, _proto));
    }
}
