using System.Linq;
using Content.Client._CE.Roles;
using Content.Client._CE.UserInterface.Systems.Character.Windows;
using Content.Shared._CE.Ghost;
using Content.Shared._CE.Roles;
using Content.Shared.Roles;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.UserInterface.Systems.Ghost.Controls;

/// <summary>
/// CE-owned copy of Content.Client.UserInterface.Systems.Ghost.Controls.GhostTargetWindow,
/// redesigned as two sortable tables ("Персонажи" / "Точки интереса") modeled on the Admin Menu's
/// Player tab, operating on <see cref="CEGhostWarp"/> instead of the vanilla GhostWarp.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEGhostTargetWindow : DefaultWindow
{
    [Dependency] private EntityManager _ent = default!;
    [Dependency] private IPrototypeManager _prototype = default!;

    // Resolved lazily (not in the constructor) - this window is built eagerly as part of the
    // screen's widget tree, before entity systems are guaranteed to be up.
    private SpriteSystem? _sprite;
    private SpriteSystem Sprite => _sprite ??= _ent.System<SpriteSystem>();

    private const string ArrowUp = "↑";
    private const string ArrowDown = "↓";
    private static readonly Color AltColor = Color.FromHex("#292B38");
    private static readonly Color DefaultColor = Color.FromHex("#2F2F3B");

    private enum PlayerColumn { Name, Job, SecretRole }

    private sealed record PlayerRow(
        NetEntity Entity,
        string Name,
        string? JobName,
        Texture? JobIcon,
        Color? JobColor,
        string? JobDepartmentName,
        string JobDepartmentSearchText,
        string? SecretRoleName,
        Texture? SecretRoleIcon,
        Color? SecretRoleColor,
        string? SecretRoleFactionName,
        string SecretRoleDepartmentSearchText);

    private sealed record LocationRow(NetEntity Entity, string Name);

    private List<PlayerRow> _allPlayers = new();
    private List<LocationRow> _allLocations = new();
    private string _searchText = string.Empty;

    private PlayerColumn _playerSortColumn = PlayerColumn.Name;
    private bool _playerSortAscending = true;
    private bool _locationSortAscending = true;

    public event Action<NetEntity>? WarpClicked;
    public event Action? OnGhostnadoClicked;
    public event Action? OnWarpToRandomFollowedClicked;
    public event Action? OnWarpToRandomClicked;

    public CEGhostTargetWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        SearchBar.OnTextChanged += OnSearchTextChanged;

        GhostnadoButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();
        WarpToRandomFollowedButton.OnPressed += _ => OnWarpToRandomFollowedClicked?.Invoke();
        WarpToRandomButton.OnPressed += _ => OnWarpToRandomClicked?.Invoke();

        PlayersNameHeader.OnKeyBindDown += args => OnPlayerHeaderClicked(args, PlayerColumn.Name);
        PlayersJobHeader.OnKeyBindDown += args => OnPlayerHeaderClicked(args, PlayerColumn.Job);
        PlayersSecretRoleHeader.OnKeyBindDown += args => OnPlayerHeaderClicked(args, PlayerColumn.SecretRole);
        LocationsNameHeader.OnKeyBindDown += OnLocationHeaderClicked;

        UpdateHeaderText();
    }

    public void UpdateWarps(IEnumerable<CEGhostWarp> warps)
    {
        _allPlayers = new List<PlayerRow>();
        _allLocations = new List<LocationRow>();

        foreach (var warp in warps)
        {
            if (warp.IsWarpPoint)
            {
                _allLocations.Add(new LocationRow(warp.Entity, warp.DisplayName));
                continue;
            }

            string? jobName = null;
            Texture? jobIcon = null;
            Color? jobColor = null;
            string? jobDepartmentName = null;
            var jobDepartmentSearchText = string.Empty;
            if (warp.Job is { } jobId && _prototype.TryIndex(jobId, out var jobProto))
            {
                jobName = jobProto.LocalizedName;
                jobIcon = _prototype.TryIndex(jobProto.Icon, out JobIconPrototype? jobIconProto)
                    ? Sprite.Frame0(jobIconProto.Icon)
                    : null;

                (var jobDepartment, jobDepartmentSearchText) = CEDepartmentResolver.ResolveJobDepartment(_prototype, jobId);
                jobColor = jobDepartment?.Color;
                jobDepartmentName = jobDepartment != null ? Loc.GetString(jobDepartment.Name) : null;
            }

            string? secretRoleName = null;
            Texture? secretRoleIcon = null;
            Color? secretRoleColor = null;
            string? secretRoleFactionName = null;
            var secretRoleDepartmentSearchText = string.Empty;
            if (warp.SecretRole is { } secretRoleId && _prototype.TryIndex(secretRoleId, out var secretRoleProto))
            {
                secretRoleName = secretRoleProto.LocalizedName;
                secretRoleIcon = _prototype.TryIndex(secretRoleProto.Icon, out JobIconPrototype? secretRoleIconProto)
                    ? Sprite.Frame0(secretRoleIconProto.Icon)
                    : null;

                (var secretDepartment, secretRoleDepartmentSearchText) = CEDepartmentResolver.ResolveSecretDepartment(_prototype, secretRoleId);
                secretRoleColor = secretDepartment?.Color;
                secretRoleFactionName = secretDepartment != null ? Loc.GetString(secretDepartment.Name) : null;
            }

            _allPlayers.Add(new PlayerRow(
                warp.Entity,
                warp.DisplayName,
                jobName,
                jobIcon,
                jobColor,
                jobDepartmentName,
                jobDepartmentSearchText,
                secretRoleName,
                secretRoleIcon,
                secretRoleColor,
                secretRoleFactionName,
                secretRoleDepartmentSearchText));
        }
    }

    public void Populate()
    {
        PlayersRows.RemoveAllChildren();
        LocationsRows.RemoveAllChildren();

        var players = FilterPlayers().ToList();
        SortPlayers(players);
        AddPlayerRows(players);

        var locations = FilterLocations().ToList();
        SortLocations(locations);
        AddLocationRows(locations);

        PlayersSection.Visible = players.Count > 0;
        LocationsSection.Visible = locations.Count > 0;
    }

    private void AddPlayerRows(List<PlayerRow> players)
    {
        for (var i = 0; i < players.Count; i++)
        {
            var row = players[i];
            var control = new CEGhostWarpPlayerRow();
            control.SetData(
                row.Name,
                row.JobName,
                row.JobIcon,
                row.JobColor,
                row.JobDepartmentName,
                row.SecretRoleName,
                row.SecretRoleIcon,
                row.SecretRoleColor,
                row.SecretRoleFactionName);
            control.PanelOverride = new StyleBoxFlat(i % 2 == 0 ? AltColor : DefaultColor);

            var target = row.Entity;
            control.WarpButton.OnPressed += _ => WarpClicked?.Invoke(target);
            control.InfoButton.OnPressed += _ => OpenCharacterView(row);

            PlayersRows.AddChild(control);
        }
    }

    private void AddLocationRows(List<LocationRow> locations)
    {
        for (var i = 0; i < locations.Count; i++)
        {
            var row = locations[i];
            var control = new CEGhostWarpLocationRow();
            control.SetData(row.Name);
            control.PanelOverride = new StyleBoxFlat(i % 2 == 0 ? AltColor : DefaultColor);

            var target = row.Entity;
            control.WarpButton.OnPressed += _ => WarpClicked?.Invoke(target);

            LocationsRows.AddChild(control);
        }
    }

    private IEnumerable<PlayerRow> FilterPlayers()
    {
        if (string.IsNullOrEmpty(_searchText))
            return _allPlayers;

        return _allPlayers.Where(row =>
            row.Name.Contains(_searchText, StringComparison.OrdinalIgnoreCase)
            || (row.JobName?.Contains(_searchText, StringComparison.OrdinalIgnoreCase) ?? false)
            || (row.SecretRoleName?.Contains(_searchText, StringComparison.OrdinalIgnoreCase) ?? false)
            || row.JobDepartmentSearchText.Contains(_searchText, StringComparison.OrdinalIgnoreCase)
            || row.SecretRoleDepartmentSearchText.Contains(_searchText, StringComparison.OrdinalIgnoreCase));
    }

    private void OpenCharacterView(PlayerRow row)
    {
        var window = new CECharacterViewWindow();
        window.Open(
            row.Entity,
            row.Name,
            row.JobName,
            row.JobIcon,
            row.JobColor,
            row.SecretRoleName,
            row.SecretRoleIcon,
            row.SecretRoleColor,
            row.SecretRoleFactionName);
    }

    private IEnumerable<LocationRow> FilterLocations()
    {
        if (string.IsNullOrEmpty(_searchText))
            return _allLocations;

        return _allLocations.Where(row => row.Name.Contains(_searchText, StringComparison.OrdinalIgnoreCase));
    }

    private void SortPlayers(List<PlayerRow> players)
    {
        players.Sort((x, y) =>
        {
            if (!_playerSortAscending)
                (x, y) = (y, x);

            return _playerSortColumn switch
            {
                PlayerColumn.Name => string.Compare(x.Name, y.Name, StringComparison.OrdinalIgnoreCase),
                PlayerColumn.Job => CompareNullableLast(x.JobName, y.JobName),
                PlayerColumn.SecretRole => CompareNullableLast(x.SecretRoleName, y.SecretRoleName),
                _ => 0
            };
        });
    }

    private void SortLocations(List<LocationRow> locations)
    {
        locations.Sort((x, y) =>
        {
            var result = string.Compare(x.Name, y.Name, StringComparison.OrdinalIgnoreCase);
            return _locationSortAscending ? result : -result;
        });
    }

    // Empty values always sink to the end, regardless of sort direction - see SortPlayers,
    // which swaps (x, y) for descending sort before this runs.
    private static int CompareNullableLast(string? x, string? y)
    {
        if (x is null && y is null)
            return 0;
        if (x is null)
            return 1;
        if (y is null)
            return -1;

        return string.Compare(x, y, StringComparison.OrdinalIgnoreCase);
    }

    private void UpdateHeaderText()
    {
        PlayersNameHeader.Text = Loc.GetString("ce-ghost-target-window-column-name");
        PlayersJobHeader.Text = Loc.GetString("ce-ghost-target-window-column-job");
        PlayersSecretRoleHeader.Text = Loc.GetString("ce-ghost-target-window-column-secret-role");
        LocationsNameHeader.Text = Loc.GetString("ce-ghost-target-window-column-name");

        var sortedHeader = _playerSortColumn switch
        {
            PlayerColumn.Name => PlayersNameHeader,
            PlayerColumn.Job => PlayersJobHeader,
            PlayerColumn.SecretRole => PlayersSecretRoleHeader,
            _ => PlayersNameHeader
        };
        sortedHeader.Text += $" {(_playerSortAscending ? ArrowUp : ArrowDown)}";

        LocationsNameHeader.Text += $" {(_locationSortAscending ? ArrowUp : ArrowDown)}";
    }

    private void OnPlayerHeaderClicked(GUIBoundKeyEventArgs args, PlayerColumn column)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        if (_playerSortColumn == column)
            _playerSortAscending = !_playerSortAscending;
        else
        {
            _playerSortColumn = column;
            _playerSortAscending = true;
        }

        UpdateHeaderText();
        Populate();
        args.Handle();
    }

    private void OnLocationHeaderClicked(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _locationSortAscending = !_locationSortAscending;

        UpdateHeaderText();
        Populate();
        args.Handle();
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text;
        Populate();
    }
}
