using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.UserInterface.Systems.Ghost.Controls;

/// <summary>
/// A single row of the "Точки интереса" table in <see cref="CEGhostTargetWindow"/>: name and a
/// small icon-only warp button.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEGhostWarpLocationRow : PanelContainer
{
    public CEGhostWarpLocationRow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetData(string name)
    {
        NameLabel.Text = name;
        WarpButton.ToolTip = Loc.GetString("ce-ghost-target-window-warp-tooltip", ("name", name));
    }
}
