using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.UserInterface.Systems.Ghost.Controls;

/// <summary>
/// A single row of the "Персонажи" table in <see cref="CEGhostTargetWindow"/>: name, job, secret
/// role, and a small icon-only warp button. Purely presentational - the window resolves job/secret
/// role icons and localized names before calling <see cref="SetData"/>, and wires <see cref="WarpButton"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEGhostWarpPlayerRow : PanelContainer
{
    public CEGhostWarpPlayerRow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetData(
        string name,
        string? jobName,
        Texture? jobIcon,
        Color? jobColor,
        string? secretRoleName,
        Texture? secretRoleIcon,
        Color? secretRoleColor)
    {
        NameLabel.Text = name;

        JobLabel.Text = jobName ?? "-";
        JobLabel.FontColorOverride = jobColor;
        JobIcon.Texture = jobIcon;
        JobIcon.Visible = jobIcon != null;

        SecretRoleLabel.Text = secretRoleName ?? "-";
        SecretRoleLabel.FontColorOverride = secretRoleColor;
        SecretRoleIcon.Texture = secretRoleIcon;
        SecretRoleIcon.Visible = secretRoleIcon != null;

        WarpButton.ToolTip = Loc.GetString("ce-ghost-target-window-warp-tooltip", ("name", name));
        InfoButton.ToolTip = Loc.GetString("ce-ghost-target-window-info-tooltip", ("name", name));
    }
}
