using Content.Client.UserInterface.Controls;
using Content.Shared._CE.Bluetext;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.Bluetext;

[GenerateTypedNameReferences]
public sealed partial class CEBluetextMenu : FancyWindow
{
    public event Action<string>? OnSubmitBluetext;

    public CEBluetextMenu()
    {
        RobustXamlLoader.Load(this);

        BluetextInput.OnTextChanged += _ => OnTextChanged();
        SubmitBluetext.OnPressed += SubmitBluetext_OnPressed;

        ClampAndUpdate();
    }

    private void SubmitBluetext_OnPressed(BaseButton.ButtonEventArgs obj)
    {
        OnSubmitBluetext?.Invoke(Rope.Collapse(BluetextInput.TextRope));
        Close();
    }

    public void Update(EntityUid owner, CEBluetextBuiState state)
    {
        var text = state.Text;

        if (text.Length > CESharedBlueTextSystem.MaxTextLength)
            text = text[..CESharedBlueTextSystem.MaxTextLength];

        var current = Rope.Collapse(BluetextInput.TextRope);
        if (!string.Equals(current, text, StringComparison.Ordinal))
            BluetextInput.TextRope = new Rope.Leaf(text);

        ClampAndUpdate();
    }

    private void OnTextChanged()
    {
        ClampAndUpdate();
    }

    private void ClampAndUpdate()
    {
        var text = Rope.Collapse(BluetextInput.TextRope);

        UpdateCharCount(text.Length);
        SubmitBluetext.Disabled = string.IsNullOrWhiteSpace(text) || text.Length > CESharedBlueTextSystem.MaxTextLength;
    }

    private void UpdateCharCount(int length)
    {
        CharCountLabel.Text = $"({length}/{CESharedBlueTextSystem.MaxTextLength})";
    }
}
