using Content.Client.UserInterface.Controls;
using Content.Shared._CE.BlueText;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.BlueText;

[GenerateTypedNameReferences]
public sealed partial class CEBlueTextMenu : FancyWindow
{
    public event Action<string>? OnSubmitBlueText;

    public CEBlueTextMenu()
    {
        RobustXamlLoader.Load(this);

        BlueTextInput.OnTextChanged += _ => OnTextChanged();
        SubmitBlueText.OnPressed += SubmitBlueText_OnPressed;

        ClampAndUpdate();
    }

    private void SubmitBlueText_OnPressed(BaseButton.ButtonEventArgs obj)
    {
        OnSubmitBlueText?.Invoke(Rope.Collapse(BlueTextInput.TextRope));
        Close();
    }

    public void Update(EntityUid owner, CEBlueTextBuiState state)
    {
        var text = state.Text;

        if (text.Length > CESharedBlueTextSystem.MaxTextLength)
            text = text[..CESharedBlueTextSystem.MaxTextLength];

        var current = Rope.Collapse(BlueTextInput.TextRope);
        if (!string.Equals(current, text, StringComparison.Ordinal))
            BlueTextInput.TextRope = new Rope.Leaf(text);

        ClampAndUpdate();
    }

    private void OnTextChanged()
    {
        ClampAndUpdate();
    }

    private void ClampAndUpdate()
    {
        var text = Rope.Collapse(BlueTextInput.TextRope);

        UpdateCharCount(text.Length);
        SubmitBlueText.Disabled = string.IsNullOrWhiteSpace(text) || text.Length > CESharedBlueTextSystem.MaxTextLength;
    }

    private void UpdateCharCount(int length)
    {
        CharCountLabel.Text = $"[{length}/{CESharedBlueTextSystem.MaxTextLength}]";
    }
}
