using Content.Client.UserInterface.Controls;
using Content.Shared._CE.Bluetext;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.Bluetext;

[GenerateTypedNameReferences]
public sealed partial class CEBluetextMenu : FancyWindow
{
    public CEBluetextMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(EntityUid owner, CEBluetextBuiState state)
    {
        // State currently carries no data; hook for future updates.
    }
}
