- type: job
  id: CEBard
  setPreference: true
  name: ce-job-name-bard
  description: ce-job-desc-bard
  playTimeTracker: CEJobBard
  startingGear: CEBardGear
  icon: CEJobIconBard
  supervisors: ce-job-supervisors-empire

- type: startingGear
  id: CEBardGear
  equipment:
    pocket1: CEWalletFilledBard

- type: entity
  id: CEWalletFilledBard
  parent: CEWallet
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents: #50cp total
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinCopper10
    - id: CECoinCopper10

- type: entity
  id: CEChestFilledBard
  parent: CEWoodenChest
  suffix: Filled, Bard
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: CEInstrumentFlute
        - id: CEInstrumentLute

- type: entity
  id: CEBedsideTableFilledBard
  parent: CEBedsideTableWooden
  suffix: Filled, Bard
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:GroupSelector
        rolls: !type:RangeNumberSelector
          range: 2, 3
        children:
        - id: CEClothingHeadJestersCap
        - id: CEClothingHeadBeretMercenary
        - id: CEClothingHeadFedoraRed
        - id: CEClothingShirtJestersAttire
        - id: CEClothingShirtMercenary
        - id: CEClothingPantsJesters
        - id: CEClothingPantsMercenary
        - id: CEClothingShoesJestersRingers
