- type: job
  id: CETownfolk
  setPreference: true
  name: ce-job-name-townfolk
  description: ce-job-desc-townfolk
  playTimeTracker: CEJobTownfolk
  #startingGear: CEGuardGear
  icon: CEJobIconTownfolk
  supervisors: ce-job-supervisors-empire
  canBeAntag: false

#- type: startingGear
#  id: CEGuardGear
#  equipment:
#    keys: CEKeyRingGuard
#    belt: CEWalletFilledTest
