using Content.Client.Pinpointer.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._CE.MurkSphere;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Utility;

namespace Content.Client._CE.MurkSphere;

[GenerateTypedNameReferences]
public sealed partial class CEMurkSphereFixerMonitorWindow : FancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;

    private static readonly SpriteSpecifier.Texture SphereBlip =
        new(new ResPath("/Textures/Interface/NavMap/beveled_circle.png"));

    private static readonly SpriteSpecifier.Texture BlockerBlip =
        new(new ResPath("/Textures/Interface/NavMap/beveled_triangle.png"));

    private static readonly NetEntity SphereBlipKey = new(int.MinValue);

    public CEMurkSphereFixerMonitorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetMap(EntityUid? mapUid)
    {
        NavMap.MapUid = mapUid;
        NavMap.ForceNavMapUpdate();
    }

    public void UpdateState(CEMurkSphereFixerMonitorBoundUserInterfaceState state)
    {
        ChargeBar.Value = state.Charge;
        var charge = (int)(state.Charge * 100);
        ChargeLabel.Text = $"{Loc.GetString("ce-murk-sphere-fixer-monitor-window-charge")}: {charge}%";

        var spriteSystem = _entManager.System<SpriteSystem>();

        if (state.SphereCoordinates is { } sphereNetCoords)
        {
            var coords = _entManager.GetCoordinates(sphereNetCoords);
            NavMap.TrackedEntities[SphereBlipKey] =
                new NavMapBlip(coords, spriteSystem.Frame0(SphereBlip), Color.White, false, false);
        }
        else
        {
            NavMap.TrackedEntities.Remove(SphereBlipKey);
        }

        var staleBlockerKeys = new List<NetEntity>();
        foreach (var key in NavMap.TrackedEntities.Keys)
        {
            if (key.Id > int.MinValue && key.Id < 0)
                staleBlockerKeys.Add(key);
        }

        foreach (var key in staleBlockerKeys)
        {
            NavMap.TrackedEntities.Remove(key);
        }

        BlockersContainer.RemoveAllChildren();

        var blipIndex = 0;
        foreach (var blocker in state.Blockers)
        {
            var hasLocation = blocker.Coordinates.Count > 0;

            var entry = new CEMurkSphereFixerBlockerEntry(blocker.Title, blocker.Description, hasLocation);
            BlockersContainer.AddChild(entry);

            if (!hasLocation)
                continue;

            var coordsList = new List<EntityCoordinates>(blocker.Coordinates.Count);
            foreach (var netCoords in blocker.Coordinates)
            {
                var coords = _entManager.GetCoordinates(netCoords);
                coordsList.Add(coords);

                var blipKey = new NetEntity(int.MinValue + 1 + blipIndex++);
                NavMap.TrackedEntities[blipKey] =
                    new NavMapBlip(coords, spriteSystem.Frame0(BlockerBlip), Color.Red, true, false);
            }

            // Cycles through every location this blocker points at, one per press.
            var cycleIndex = 0;
            entry.CenterButton!.OnPressed += _ =>
            {
                NavMap.CenterToCoordinates(coordsList[cycleIndex]);
                cycleIndex = (cycleIndex + 1) % coordsList.Count;
            };
        }
    }
}

/// <summary>
/// One blocker row in the monitor's side list: title, description, and (if the blocker has a
/// location to point at) a button to center the navmap on it.
/// </summary>
public sealed class CEMurkSphereFixerBlockerEntry : PanelContainer
{
    public readonly Button? CenterButton;

    public CEMurkSphereFixerBlockerEntry(string title, string description, bool hasLocation)
    {
        HorizontalExpand = true;
        Margin = new Thickness(0, 0, 0, 4);
        PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(40, 40, 45) };

        var column = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(6, 4, 6, 4),
        };

        column.AddChild(new Label { Text = title, StyleClasses = { "highlight" } });

        var descriptionLabel = new RichTextLabel { HorizontalExpand = true };
        descriptionLabel.SetMessage(description);
        column.AddChild(descriptionLabel);

        if (hasLocation)
        {
            CenterButton = new Button
            {
                Text = Loc.GetString("ce-murk-sphere-fixer-monitor-window-center"),
                HorizontalExpand = true,
                Margin = new Thickness(0, 4, 0, 0),
            };

            column.AddChild(CenterButton);
        }

        AddChild(column);
    }
}
