using Content.Client._CE.UserInterface.Systems.Character.Tabs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.UserInterface.Systems.Character.Windows;

[GenerateTypedNameReferences]
public sealed partial class CECharacterWindow : DefaultWindow
{
    public readonly CECharacterInventoryTab InventoryTab;
    public readonly CECharacterObjectivesTab ObjectivesTab;

    public CECharacterWindow()
    {
        RobustXamlLoader.Load(this);

        InventoryTab = new CECharacterInventoryTab();
        Tabs.AddChild(InventoryTab);
        Tabs.SetTabTitle(0, Loc.GetString("ce-character-window-inventory-tab"));

        ObjectivesTab = new CECharacterObjectivesTab();
        Tabs.AddChild(ObjectivesTab);
        Tabs.SetTabTitle(1, Loc.GetString("ce-character-window-objectives-tab"));
    }
}
