using System.Linq;
using Content.Client._CE.Character;
using Content.Client._CE.Objectives.Ui;
using Content.Client._CE.Skill;
using Content.Client._CE.Skill.Ui;
using Content.Client._CE.UserInterface.Systems.Character.Tabs;
using Content.Client.Stylesheets;
using Content.Shared._CE.Character;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface.Systems.Character.Windows;

/// <summary>
/// A read-only "dossier" for another player, opened from the ghost target window's info button.
/// Visually mirrors CECharacterWindow's header, but only has Objectives/Skills tabs (no
/// inventory - ClientInventorySystem is hard-wired to the local player, see GhostGui/CEGhostTargetWindow
/// grilling notes). Unlike CECharacterWindow this isn't a UIController-owned singleton: the ghost
/// target window can open several of these at once, one per inspected player.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CECharacterViewWindow : DefaultWindow
{
    private const int ObjectivesTabIndex = 0;
    private const int SkillsTabIndex = 1;

    [Dependency] private EntityManager _ent = default!;

    private readonly CEClientSkillSystem _skill;
    private readonly CEViewCharacterSystem _viewCharacter;

    public readonly CECharacterObjectivesTab ObjectivesTab;
    public readonly CECharacterSkillsTab SkillsTab;

    private Direction _rotation = Direction.South;
    private NetEntity _target;

    public CECharacterViewWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        // A lighter border than the theme's own PanelInsetDark (whose border blends into its
        // own dark fill) so the portrait panel actually reads as a distinct frame.
        PortraitPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = StyleNano.PanelDark,
            BorderColor = StyleNano.ButtonColorHovered,
            BorderThickness = new Thickness(2f),
        };

        RotateLeft.OnPressed += _ => Rotate(TurnCardinal(_rotation, -1));
        RotateRight.OnPressed += _ => Rotate(TurnCardinal(_rotation, 1));

        _skill = _ent.System<CEClientSkillSystem>();
        _viewCharacter = _ent.System<CEViewCharacterSystem>();
        _viewCharacter.Response += OnResponse;

        ObjectivesTab = new CECharacterObjectivesTab();
        Tabs.AddChild(ObjectivesTab);
        Tabs.SetTabTitle(0, Loc.GetString("ce-character-window-objectives-tab"));

        SkillsTab = new CECharacterSkillsTab();
        Tabs.AddChild(SkillsTab);
        Tabs.SetTabTitle(1, Loc.GetString("ce-character-window-skills-tab"));
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            _viewCharacter.Response -= OnResponse;
    }

    /// <summary>
    /// Populates the header instantly from data the caller already has (the ghost target
    /// window's row) and kicks off the async objectives request. Skills don't need a network
    /// round trip - CESkillStorageComponent is normal PVS, readable off any visible entity.
    /// </summary>
    public void Open(
        NetEntity target,
        string name,
        string? jobName,
        Texture? jobIcon,
        Color? jobColor,
        string? secretRoleName,
        Texture? secretRoleIcon,
        Color? secretRoleColor,
        string? secretRoleFactionName)
    {
        _target = target;
        var entity = _ent.GetEntity(target);

        SpriteView.SetEntity(entity);
        NameLabel.Text = name;

        JobLabel.Text = jobName ?? string.Empty;
        JobLabel.FontColorOverride = jobColor;
        JobIcon.Texture = jobIcon;
        JobIcon.Visible = jobIcon != null;

        if (secretRoleName != null)
        {
            SecretRoleContainer.Visible = true;
            SecretRoleLabel.Text = secretRoleName;
            SecretRoleLabel.FontColorOverride = secretRoleColor;
            SecretRoleIcon.Texture = secretRoleIcon;
            SecretRoleIcon.Visible = secretRoleIcon != null;

            FactionLabel.Clear();
            if (secretRoleFactionName != null)
            {
                var factionText = new FormattedMessage();
                factionText.PushColor(secretRoleColor ?? Color.White);
                factionText.AddText(secretRoleFactionName);
                factionText.Pop();
                FactionLabel.SetMessage(factionText);
            }
        }
        else
        {
            SecretRoleContainer.Visible = false;
        }

        // Physical appearance, not mind-based - safe to read straight off the target entity.
        var detailsText = new FormattedMessage();
        if (_ent.TryGetComponent<HumanoidProfileComponent>(entity, out var profile))
        {
            var species = _ent.System<HumanoidProfileSystem>().GetSpeciesRepresentation(profile.Species);
            detailsText.AddText($"{profile.Gender} • {profile.Age} • {species}");
        }
        DetailsLabel.SetMessage(detailsText);

        UpdateSkills(entity);

        ObjectivesTab.CEObjectives.RemoveAllChildren();
        _viewCharacter.RequestView(target);

        OpenCentered();
    }

    private void UpdateSkills(EntityUid target)
    {
        SkillsTab.CESkills.RemoveAllChildren();

        var learned = _skill.GetLearnedSkills(target);
        var ordered = learned
            .Select(skill => (skill, descriptor: _skill.GetDescriptor(target, skill)))
            .OrderBy(entry => entry.descriptor is null)
            .ThenBy(entry => entry.descriptor is { } d ? Loc.GetString(d.Name) : string.Empty, StringComparer.CurrentCultureIgnoreCase);

        foreach (var (skill, _) in ordered)
        {
            var control = new CESkillControl();
            control.SetSkill(target, skill);
            SkillsTab.CESkills.AddChild(control);
        }

        Tabs.SetTabVisible(SkillsTabIndex, learned.Count > 0);
    }

    private void OnResponse(CEViewCharacterResponseEvent msg)
    {
        if (msg.Target != _target)
            return;

        ObjectivesTab.CEObjectives.RemoveAllChildren();
        foreach (var info in msg.Objectives)
        {
            var control = new CEObjectiveControl();
            control.SetObjectiveInfo(info);
            ObjectivesTab.CEObjectives.AddChild(control);
        }

        Tabs.SetTabVisible(ObjectivesTabIndex, msg.Objectives.Count > 0);
    }

    private void Rotate(Direction direction)
    {
        _rotation = direction;
        SpriteView.OverrideDirection = _rotation;
    }

    // Direction.TurnCw/TurnCcw step through all 8 compass points (45 degrees);
    // most sprites only have 4 facings, so we step directly between cardinals (90 degrees).
    private static Direction TurnCardinal(Direction current, int steps)
    {
        return (Direction)(((int) current + steps * 2 + 8) % 8);
    }
}
