using Content.Client._CE.UserInterface.Systems.Character.Tabs;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.UserInterface.Systems.Character.Windows;

[GenerateTypedNameReferences]
public sealed partial class CECharacterWindow : DefaultWindow
{
    public readonly CECharacterInventoryTab InventoryTab;
    public readonly CECharacterObjectivesTab ObjectivesTab;
    public readonly CECharacterSkillsTab SkillsTab;

    private Direction _rotation = Direction.South;

    public CECharacterWindow()
    {
        RobustXamlLoader.Load(this);

        // A lighter border than the theme's own PanelInsetDark (whose border blends into its
        // own dark fill) so the portrait panel actually reads as a distinct frame.
        PortraitPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = StyleNano.PanelDark,
            BorderColor = StyleNano.ButtonColorHovered,
            BorderThickness = new Thickness(2f),
        };

        RotateLeft.OnPressed += _ => Rotate(TurnCardinal(_rotation, -1));
        RotateRight.OnPressed += _ => Rotate(TurnCardinal(_rotation, 1));

        InventoryTab = new CECharacterInventoryTab();
        Tabs.AddChild(InventoryTab);
        Tabs.SetTabTitle(0, Loc.GetString("ce-character-window-inventory-tab"));

        ObjectivesTab = new CECharacterObjectivesTab();
        Tabs.AddChild(ObjectivesTab);
        Tabs.SetTabTitle(1, Loc.GetString("ce-character-window-objectives-tab"));

        SkillsTab = new CECharacterSkillsTab();
        Tabs.AddChild(SkillsTab);
        Tabs.SetTabTitle(2, Loc.GetString("ce-character-window-skills-tab"));
        Tabs.SetTabVisible(2, false);
    }

    private void Rotate(Direction direction)
    {
        _rotation = direction;
        SpriteView.OverrideDirection = _rotation;
    }

    // Direction.TurnCw/TurnCcw step through all 8 compass points (45 degrees);
    // most sprites only have 4 facings, so we step directly between cardinals (90 degrees).
    private static Direction TurnCardinal(Direction current, int steps)
    {
        return (Direction)(((int) current + steps * 2 + 8) % 8);
    }
}
