"Edit: Sprites":
- changed-files:
  - any-glob-to-any-file: '**/*.rsi/*.png'

"Edit: Mapping":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/**/*.yml'
    - 'Resources/Prototypes/Maps/**/*.yml'

"Edit: zLevels":
- changed-files:
  - any-glob-to-any-file: '**/_CE/ZLevels/**/*.cs'