using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface.Systems.Vitals.Widgets;

/// <summary>
/// Clock showing the time of day: the arrow points up at midnight and down at noon.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEClockUI : UIWidget
{
    private const string ClockRsiPath = "/Textures/_CE/Interface/Vitals/clock.rsi";
    private const float TextureScale = 3f;

    [Dependency] private IResourceCache _resCache = default!;

    private Texture? _baseTex;
    private Texture? _arrowTex;

    private float _progress;

    public CEClockUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Needed for the tooltip to receive hover.
        MouseFilter = MouseFilterMode.Pass;

        LoadTextures();

        if (_baseTex != null)
        {
            var w = _baseTex.Width * TextureScale;
            var h = _baseTex.Height * TextureScale;
            MinWidth = w;
            MinHeight = h;
            SetWidth = w;
            SetHeight = h;
        }
    }

    private void LoadTextures()
    {
        if (!_resCache.TryGetResource<RSIResource>(new ResPath(ClockRsiPath), out var rsi))
            return;

        if (rsi.RSI.TryGetState("base", out var baseState))
            _baseTex = baseState.Frame0;

        if (rsi.RSI.TryGetState("arrow", out var arrowState))
            _arrowTex = arrowState.Frame0;
    }

    /// <param name="progress">Day progress: 0 is midnight, 0.5 is noon</param>
    /// <param name="tooltip">Time left until dawn/sunset, null to hide the tooltip</param>
    public void SetTime(float progress, string? tooltip)
    {
        _progress = progress;

        if (ToolTip != tooltip)
            ToolTip = tooltip;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var size = PixelSize;

        if (_baseTex != null)
            handle.DrawTextureRect(_baseTex, UIBox2.FromDimensions(Vector2.Zero, size));

        if (_arrowTex == null)
            return;

        // Rotate clockwise around the center of the widget
        var center = size / 2f;
        handle.SetTransform(GlobalPixelPosition + center, new Angle(_progress * MathF.Tau));
        handle.DrawTextureRect(_arrowTex, UIBox2.FromDimensions(-center, size));
        handle.SetTransform(GlobalPixelPosition, Angle.Zero);
    }
}
