using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface.Systems.Vitals.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CEHealthUI : UIWidget
{
    private bool _lastCriticalState;
    private int _lastHealthState = -1;

    private const string AliveRsiPath = "/Textures/_CE/Interface/Vitals/alive.rsi";
    private const string CriticalRsiPath = "/Textures/_CE/Interface/Vitals/critical.rsi";

    private const int MaxHealthStates = 10; // health0..health9
    private const float TextureScale = 3f;

    public CEHealthUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        HealthTexture.DisplayRect.TextureScale = new Vector2(TextureScale, TextureScale);
    }

    public void UpdateHealthDisplay(float ratio, bool critical)
    {
        if (critical != _lastCriticalState)
        {
            _lastCriticalState = critical;
            _lastHealthState = -1;
        }

        if (critical)
        {
            if (_lastHealthState != -2)
            {
                _lastHealthState = -2;
                var specifier = new SpriteSpecifier.Rsi(new ResPath(CriticalRsiPath), "critical");
                HealthTexture.SetFromSpriteSpecifier(specifier);
            }

            return;
        }

        var stateIndex = (int) (ratio * (MaxHealthStates - 1));
        stateIndex = Math.Clamp(stateIndex, 0, MaxHealthStates - 1);

        if (stateIndex != _lastHealthState)
        {
            _lastHealthState = stateIndex;
            var specifier = new SpriteSpecifier.Rsi(new ResPath(AliveRsiPath), $"health{stateIndex}");
            HealthTexture.SetFromSpriteSpecifier(specifier);
        }
    }
}