using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface.Systems.Vitals.Widgets;

/// <summary>
/// Round progress bar: the restoration ritual's progress (light) racing the murk's collapse countdown (murk).
/// Both fill left to right, murk is drawn over light.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CERoundProgressUI : UIWidget
{
    private const string RoundProgressRsiPath = "/Textures/_CE/Interface/Vitals/round_progress.rsi";
    private const float TextureScale = 3f;

    [Dependency] private IResourceCache _resCache = default!;

    private Texture? _baseTex;
    private Texture? _lightTex;
    private Texture? _murkTex;

    private float _light;
    private float _murk;

    private int _lightPercent;
    private int _murkPercent;

    public CERoundProgressUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Needed for the tooltip to receive hover.
        MouseFilter = MouseFilterMode.Pass;

        LoadTextures();

        if (_baseTex != null)
        {
            var w = _baseTex.Width * TextureScale;
            var h = _baseTex.Height * TextureScale;
            MinWidth = w;
            MinHeight = h;
            SetWidth = w;
            SetHeight = h;
        }
    }

    private void LoadTextures()
    {
        if (!_resCache.TryGetResource<RSIResource>(new ResPath(RoundProgressRsiPath), out var rsi))
            return;

        if (rsi.RSI.TryGetState("base", out var baseState))
            _baseTex = baseState.Frame0;

        if (rsi.RSI.TryGetState("light", out var lightState))
            _lightTex = lightState.Frame0;

        if (rsi.RSI.TryGetState("murk", out var murkState))
            _murkTex = murkState.Frame0;
    }

    public void SetProgress(float light, float murk)
    {
        _light = Math.Clamp(light, 0f, 1f);
        _murk = Math.Clamp(murk, 0f, 1f);

        // Called every frame - only rebuild the tooltip string when a displayed percentage changes.
        var lightPercent = (int) MathF.Round(_light * 100f);
        var murkPercent = (int) MathF.Round(_murk * 100f);
        if (ToolTip != null && lightPercent == _lightPercent && murkPercent == _murkPercent)
            return;

        _lightPercent = lightPercent;
        _murkPercent = murkPercent;
        ToolTip = Loc.GetString("ce-round-progress-tooltip", ("light", lightPercent), ("murk", murkPercent));
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var size = PixelSize;

        if (_baseTex != null)
            handle.DrawTextureRect(_baseTex, UIBox2.FromDimensions(Vector2.Zero, size));

        DrawFill(handle, _lightTex, _light, size);
        DrawFill(handle, _murkTex, _murk, size);
    }

    private static void DrawFill(DrawingHandleScreen handle, Texture? tex, float ratio, Vector2 size)
    {
        if (tex == null || ratio <= 0f)
            return;

        var dest = UIBox2.FromDimensions(Vector2.Zero, new Vector2(size.X * ratio, size.Y));
        var src = UIBox2.FromDimensions(Vector2.Zero, new Vector2(tex.Width * ratio, tex.Height));
        handle.DrawTextureRectRegion(tex, dest, src);
    }
}
