using System.Numerics;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class DefaultGameScreen : InGameScreen
{
    public DefaultGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(TopLeft, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        SetAnchorAndMarginPreset(Chat, LayoutPreset.BottomLeft, margin: 10); // CrystallEdge: chat redesign, moved to bottom-left
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.TopRight, margin: 10);

        // CrystallEdge: top bar (escape/guidebook/emotes/etc buttons) is hidden until the escape menu opens
        TopBar.Visible = false;

        // CrystallEdge: inventory UI removed from the main screen
        // SetAnchorAndMarginPreset(Inventory, LayoutPreset.TopLeft, margin: 10);
        // SetMarginTop(Inventory, 80);
        // LayoutContainer.SetGrowVertical(Inventory, LayoutContainer.GrowDirection.End);

        //CrystallEdge - health/mana spheres, stamina bar, centered+lowered action bar
        var gap = 310f;
        var manaOffset = ManaBar.MinSize.X / 2f + gap;
        // Mirror health to the left so that HealthBar.Right == -ManaBar.Left.
        var healthOffset = -(HealthBar.MinSize.X + manaOffset);

        SetAnchorAndMarginPreset(HealthBar, LayoutPreset.CenterBottom);
        SetMarginLeft(HealthBar, healthOffset);

        SetAnchorAndMarginPreset(ManaBar, LayoutPreset.CenterBottom);
        SetMarginLeft(ManaBar, manaOffset);

        SetAnchorAndMarginPreset(StaminaBar, LayoutPreset.CenterBottom, margin: 80);
        SetMarginLeft(StaminaBar, -StaminaBar.MinSize.X / 2f);
        SetMarginRight(StaminaBar, StaminaBar.MinSize.X / 2f);

        SetAnchorPreset(Actions, LayoutPreset.BottomWide);
        SetMarginLeft(Actions, 0);
        SetMarginRight(Actions, 0);
        //CrystallEdge end

        // CrystallEdge: chat is fixed-size and no longer shares a corner with Alerts, no resize wiring needed
        // Chat.OnResized += ChatOnResized;
        // Chat.OnChatResizeFinish += ChatOnResizeFinish;

        MainViewport.OnResized += ResizeActionContainer;
        // Inventory.OnResized += ResizeActionContainer; // CrystallEdge: inventory UI removed from the main screen
        Hotbar.OnResized += ResizeActionContainer;
        StaminaBar.OnResized += ResizeActionContainer; // CrystallEdge: stamina bar's size settles late (waits on networked data), must retrigger too

        ResizeActionContainer();
    }

    private void ResizeActionContainer()
    {
        //CrystallEdge - action bar stacks above whichever is taller: stamina bar or hotbar
        float indent = 20;
        var maxWidth = MainViewport.Size.X - indent;
        if (maxWidth > 0)
            Actions.ActionsContainer.MaxGridWidth = maxWidth;

        var staminaTop = 80f + StaminaBar.MinSize.Y;
        var hotbarTop = 5f + Hotbar.Size.Y;
        var actionHeight = MathF.Max(Actions.MinSize.Y, 64f);
        var actionBottomOffset = MathF.Max(staminaTop, hotbarTop) + 8f - actionHeight / 2f;
        SetMarginBottom(Actions, -actionBottomOffset);
        SetMarginTop(Actions, -actionBottomOffset - actionHeight);
        //CrystallEdge end
    }

    // CrystallEdge: chat is fixed-size now, resize wiring below is unused (kept for reference)
    // private void ChatOnResizeFinish(Vector2 _)
    // {
    //     var marginBottom = Chat.GetValue<float>(MarginBottomProperty);
    //     var marginLeft = Chat.GetValue<float>(MarginLeftProperty);
    //     OnChatResized?.Invoke(new Vector2(marginBottom, marginLeft));
    // }
    //
    // private void ChatOnResized()
    // {
    //     var marginBottom = Chat.GetValue<float>(MarginBottomProperty);
    //     SetMarginTop(Alerts, marginBottom);
    // }

    public override ChatBox ChatBox => Chat;

    // CrystallEdge: chat is fixed-size now, nothing to persist
    public override void SetChatSize(Vector2 size)
    {
    }
}
