using System.Numerics;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class DefaultGameScreen : InGameScreen
{
    public DefaultGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(TopLeft, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Inventory, LayoutPreset.BottomLeft, margin: 5);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        SetAnchorAndMarginPreset(Chat, LayoutPreset.TopRight, margin: 10);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.TopRight, margin: 10);

        //CrystallEdge - health/mana spheres, stamina bar, centered+lowered action bar
        var gap = 310f;
        var manaOffset = ManaBar.MinSize.X / 2f + gap;
        // Mirror health to the left so that HealthBar.Right == -ManaBar.Left.
        var healthOffset = -(HealthBar.MinSize.X + manaOffset);

        SetAnchorAndMarginPreset(HealthBar, LayoutPreset.CenterBottom);
        SetMarginLeft(HealthBar, healthOffset);

        SetAnchorAndMarginPreset(ManaBar, LayoutPreset.CenterBottom);
        SetMarginLeft(ManaBar, manaOffset);

        SetAnchorAndMarginPreset(StaminaBar, LayoutPreset.CenterBottom, margin: 80);
        SetMarginLeft(StaminaBar, -StaminaBar.MinSize.X / 2f);
        SetMarginRight(StaminaBar, StaminaBar.MinSize.X / 2f);

        SetAnchorPreset(Actions, LayoutPreset.BottomWide);
        SetMarginLeft(Actions, 0);
        SetMarginRight(Actions, 0);
        //CrystallEdge end

        Chat.OnResized += ChatOnResized;
        Chat.OnChatResizeFinish += ChatOnResizeFinish;

        MainViewport.OnResized += ResizeActionContainer;
        Inventory.OnResized += ResizeActionContainer;
        Hotbar.OnResized += ResizeActionContainer;

        ResizeActionContainer();
    }

    private void ResizeActionContainer()
    {
        //CrystallEdge - action bar stacks above whichever is taller: stamina bar or hotbar
        float indent = 20;
        var maxWidth = MainViewport.Size.X - indent;
        if (maxWidth > 0)
            Actions.ActionsContainer.MaxGridWidth = maxWidth;

        var staminaTop = 80f + StaminaBar.MinSize.Y;
        var hotbarTop = 5f + Hotbar.Size.Y;
        var actionHeight = MathF.Max(Actions.MinSize.Y, 64f);
        var actionBottomOffset = MathF.Max(staminaTop, hotbarTop) + 8f - actionHeight / 2f;
        SetMarginBottom(Actions, -actionBottomOffset);
        SetMarginTop(Actions, -actionBottomOffset - actionHeight);
        //CrystallEdge end
    }

    private void ChatOnResizeFinish(Vector2 _)
    {
        var marginBottom = Chat.GetValue<float>(MarginBottomProperty);
        var marginLeft = Chat.GetValue<float>(MarginLeftProperty);
        OnChatResized?.Invoke(new Vector2(marginBottom, marginLeft));
    }

    private void ChatOnResized()
    {
        var marginBottom = Chat.GetValue<float>(MarginBottomProperty);
        SetMarginTop(Alerts, marginBottom);
    }

    public override ChatBox ChatBox => Chat;

    //TODO: There's probably a better way to do this... but this is also the easiest way.
    public override void SetChatSize(Vector2 size)
    {
        SetMarginBottom(Chat, size.X);
        SetMarginLeft(Chat, size.Y);
        SetMarginTop(Alerts, size.X);
    }
}
