using Content.Shared._CE.Knowledge;
using Content.Shared._CE.MagicEssence.Prototypes;
using Content.Shared._CE.Science;
using Content.Shared._CE.Science.Components;
using Content.Shared._CE.Science.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._CE.Science;

/// <summary>
/// Left-hand panel of the research table window: shows the selected tile's content (if any), plus
/// the candidate cards if it's an offered star.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEResearchTileInfoControl : BoxContainer
{
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPlayerManager _player = default!;

    private CEKnowledgeSystem _knowledge = default!;

    /// <summary>
    /// Raised when the player presses one of an offered star's candidate cards' "Choose" button,
    /// with that candidate's id.
    /// </summary>
    public event Action<ProtoId<CEScienceDiscoveryPrototype>>? OnChooseDiscovery;

    public CEResearchTileInfoControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _knowledge = _entity.System<CEKnowledgeSystem>();
    }

    public void UpdateTile(CEScienceMapTile? tile)
    {
        CardsContainer.Visible = false;
        CardsContainer.RemoveAllChildren();

        switch (tile)
        {
            case CEScienceDeadZoneTile:
                TitleLabel.Visible = true;
                TitleLabel.Text = Loc.GetString("ce-research-tile-dead-zone-title");
                DescLabel.Visible = true;
                DescLabel.SetMessage(Loc.GetString("ce-research-tile-dead-zone-desc"));
                break;

            case CEScienceStarTile starTile when _prototype.TryIndex(starTile.Rarity, out var rarity):
                TitleLabel.Visible = true;
                TitleLabel.Text = Loc.GetString(rarity.Name);
                DescLabel.Visible = true;
                DescLabel.SetMessage(Loc.GetString("ce-research-tile-star-desc"));
                break;

            case CEScienceOfferedStarTile offeredTile when _prototype.TryIndex(offeredTile.Rarity, out var rarity):
                TitleLabel.Visible = true;
                TitleLabel.Text = Loc.GetString("ce-research-tile-offered-star-title");
                DescLabel.Visible = true;
                DescLabel.SetMessage(Loc.GetString("ce-research-tile-offered-star-desc"));

                BuildCards(offeredTile, rarity);
                break;

            case CEScienceDiscoveryTile discoveryTile
                when _prototype.TryIndex(discoveryTile.Discovery, out var discovery)
                     && _prototype.TryIndex(discovery.Knowledge, out var knowledge):
                TitleLabel.Visible = true;
                TitleLabel.Text = Loc.GetString(knowledge.Name);

                var effects = _knowledge.GetKnowledgeEffectDescription(discovery.Knowledge);
                DescLabel.Visible = effects.Length > 0;
                DescLabel.SetMessage(FormattedMessage.FromMarkupPermissive(effects));
                break;

            default:
                TitleLabel.Visible = false;
                DescLabel.Visible = false;
                break;
        }
    }

    /// <summary>
    /// Builds one <see cref="CEScienceDiscoveryCardControl"/> per candidate offered by
    /// <paramref name="offered"/>.
    /// </summary>
    private void BuildCards(CEScienceOfferedStarTile offered, CEScienceDiscoveryDifficultyPrototype rarity)
    {
        if (_player.LocalEntity is not { } localEntity)
            return;

        _entity.TryGetComponent<CEScienceResearchDataComponent>(localEntity, out var researchData);
        var points = researchData?.Points ?? new Dictionary<ProtoId<CEMagicEssenceTypePrototype>, int>();

        foreach (var discoveryId in offered.Candidates)
        {
            if (!_prototype.TryIndex(discoveryId, out var discovery))
                continue;

            if (!_prototype.TryIndex(discovery.Knowledge, out var knowledge))
                continue;

            var card = new CEScienceDiscoveryCardControl(discovery, knowledge, rarity, _knowledge, points);
            card.OnPressed += () => OnChooseDiscovery?.Invoke(discoveryId);
            CardsContainer.AddChild(card);
        }

        CardsContainer.Visible = true;
    }
}
