using System.Numerics;
using Content.Client._CE.MagicEssence.Controls;
using Content.Shared._CE.MagicEssence.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Science;

/// <summary>
/// A single research action entry: a button that executes the action directly. The action's
/// description is shown as a tooltip and its research point cost (per essence type) is shown on
/// the button's right edge.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEResearchActionControl : BoxContainer
{
    private const int CostIconSize = 18;

    /// <summary>
    /// Raised when the "Execute" button is pressed.
    /// </summary>
    public event Action? OnExecute;

    public CEResearchActionControl()
    {
        RobustXamlLoader.Load(this);

        ExecuteButton.OnPressed += _ => OnExecute?.Invoke();
    }

    public string HeaderText
    {
        set => NameLabel.Text = value;
    }

    public string Description
    {
        set => ExecuteButton.ToolTip = value;
    }

    public IReadOnlyDictionary<ProtoId<CEMagicEssenceTypePrototype>, int> Cost
    {
        set
        {
            CostContainer.RemoveAllChildren();
            foreach (var (essence, amount) in value)
            {
                var control = new CEEssenceAmountControl { SetSize = new Vector2(CostIconSize, CostIconSize) };
                control.SetEssence(essence, amount);
                CostContainer.AddChild(control);
            }
        }
    }

    public bool CanExecute
    {
        set => ExecuteButton.Disabled = !value;
    }
}
