using System.Numerics;
using Content.Shared._CE.Hex;
using Content.Shared._CE.MagicEssence.Prototypes;
using Content.Shared._CE.MagicEssence.Systems;
using Content.Shared._CE.Science;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._CE.Science;

[GenerateTypedNameReferences]
public sealed partial class CEResearchHexGridControl : BoxContainer
{
    private const float LocalScaleDefault = 3f;
    private const float LocalScaleMin = 0.5f;
    private const float LocalScaleMax = 6f;

    /// <summary>Distance from a hex's center to its corner, in native pixels.</summary>
    private const float HexSize = 10f;

    private static readonly SpriteSpecifier CursorIcon = new SpriteSpecifier.Rsi(new ResPath("/Textures/_CE/Interface/Science/cursor.rsi"), "cursor");
    private static readonly SpriteSpecifier BgLight = new SpriteSpecifier.Rsi(new ResPath("/Textures/_CE/Interface/Science/bg.rsi"), "light");
    private static readonly SpriteSpecifier BgDark = new SpriteSpecifier.Rsi(new ResPath("/Textures/_CE/Interface/Science/bg.rsi"), "dark");

    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IEntityManager _entity = default!;

    private CEMagicEssenceSystem _essence = default!;

    private Dictionary<Vector2i, CEResearchMapTile> _tiles = new();
    private int _radius;
    private Color _linkColor = Color.White;
    private bool _hasParallax;
    private ProtoId<CEMagicEssenceTypePrototype>? _armed;

    private Vector2i _hovered;
    private bool _dragging;
    private bool _needsRecenter = true;
    private Vector2 _previousMousePosition;
    private Vector2 _globalOffset;
    private float _localScale = LocalScaleDefault;

    private float Scale => UIScale * _localScale;

    /// <summary>Raised when the player clicks a hex that's currently legal for the armed aspect.</summary>
    public event Action<Vector2i, ProtoId<CEMagicEssenceTypePrototype>>? OnPlaceAspect;

    /// <summary>
    /// Raised every draw with the current pan offset and zoom, so a background
    /// <see cref="Content.Client.Parallax.ParallaxControl"/> can be kept in sync (with a lag,
    /// for a parallax effect).
    /// </summary>
    public event Action<Vector2, float>? OnViewChanged;

    public CEResearchHexGridControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _essence = _entity.System<CEMagicEssenceSystem>();
    }

    public void UpdateState(Dictionary<Vector2i, CEResearchMapTile> tiles, int radius, Color linkColor, bool hasParallax)
    {
        _tiles = tiles;
        _radius = radius;
        _linkColor = linkColor;
        _hasParallax = hasParallax;
    }

    public void SetArmed(ProtoId<CEMagicEssenceTypePrototype>? essence)
    {
        _armed = essence;
    }

    private bool IsLegal(Vector2i hex, ProtoId<CEMagicEssenceTypePrototype> essence)
    {
        if (CEHexMath.CubeDistance(hex, Vector2i.Zero) > _radius)
            return false;

        if (_tiles.TryGetValue(hex, out var existing) && (existing.DeadZone || existing.Aspect is not null))
            return false;

        foreach (var neighbor in CEHexMath.Neighbors(hex))
        {
            if (_tiles.TryGetValue(neighbor, out var tile) &&
                tile.Aspect is { } neighborAspect &&
                _essence.AreDirectlyRelated(neighborAspect, essence))
                return true;
        }

        return false;
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        if (args.Handled)
            return;

        var cursor = (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;
        var oldScale = Scale;

        _localScale = MathHelper.Clamp(_localScale + 0.1f * args.Delta.Y, LocalScaleMin, LocalScaleMax);

        var newScale = Scale;
        _globalOffset = cursor - (cursor - _globalOffset) * (newScale / oldScale);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Handled)
            return;

        if (args.Function == EngineKeyFunctions.UIClick)
        {
            _dragging = true;

            if (_armed is { } essence && IsLegal(_hovered, essence))
            {
                OnPlaceAspect?.Invoke(_hovered, essence);
                UserInterfaceManager.ClickSound();
            }
        }

        if (args.Function == EngineKeyFunctions.UIRightClick)
        {
            _localScale = LocalScaleDefault;
            _needsRecenter = true;
        }
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Handled || args.Function != EngineKeyFunctions.UIClick)
            return;

        _dragging = false;
    }

    private Vector2 HexToScreen(Vector2i hex)
    {
        var x = HexSize * (MathF.Sqrt(3f) * hex.X + MathF.Sqrt(3f) / 2f * hex.Y);
        var y = HexSize * (1.5f * hex.Y);
        return new Vector2(x, -y) * Scale + _globalOffset;
    }

    private Vector2i ScreenToHex(Vector2 screen)
    {
        var local = (screen - _globalOffset) / Scale;
        var x = local.X;
        var y = -local.Y;

        var q = (MathF.Sqrt(3f) / 3f * x - 1f / 3f * y) / HexSize;
        var r = 2f / 3f * y / HexSize;

        return AxialRound(q, r);
    }

    private static Vector2i AxialRound(float q, float r)
    {
        var x = q;
        var z = r;
        var y = -x - z;

        var rx = MathF.Round(x);
        var ry = MathF.Round(y);
        var rz = MathF.Round(z);

        var dx = MathF.Abs(rx - x);
        var dy = MathF.Abs(ry - y);
        var dz = MathF.Abs(rz - z);

        if (dx > dy && dx > dz)
            rx = -ry - rz;
        else if (dy > dz)
            ry = -rx - rz;
        else
            rz = -rx - ry;

        return new Vector2i((int)rx, (int)rz);
    }

    private void DrawCentered(DrawingHandleScreen handle, Texture texture, Vector2 center, Color? tint = null)
    {
        var size = new Vector2(texture.Width, texture.Height) * Scale;
        var quad = new UIBox2(center - size / 2, center + size / 2);
        handle.DrawTextureRect(texture, quad, tint ?? Color.White);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (_needsRecenter)
        {
            _globalOffset = PixelSize / 2;
            _needsRecenter = false;
        }

        var cursor = (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;

        if (_dragging)
        {
            var delta = cursor - _previousMousePosition;
            _globalOffset += delta;
        }

        _previousMousePosition = cursor;
        _hovered = ScreenToHex(cursor);

        OnViewChanged?.Invoke(_globalOffset, _localScale);

        if (!_hasParallax)
            handle.DrawRect(PixelSizeBox, Color.Black);

        foreach (var hex in CEHexMath.Spiral(Vector2i.Zero, _radius))
        {
            if (_tiles.TryGetValue(hex, out var bgTile) && bgTile.DeadZone)
                continue;

            var parity = ((hex.X + hex.Y) % 2 + 2) % 2;
            var bg = parity == 0 ? BgLight : BgDark;
            DrawCentered(handle, bg.Frame0(), HexToScreen(hex));
        }

        DrawLinks(handle);

        foreach (var (hex, tile) in _tiles)
        {
            if (tile.Aspect is not { } aspect || !_prototype.TryIndex(aspect, out var essenceProto))
                continue;

            var pos = HexToScreen(hex);
            var texture = essenceProto.Icon.Frame0();

            if (tile.Fixed)
            {
                DrawCentered(handle, texture, pos);
            }
            else
            {
                var size = new Vector2(texture.Width, texture.Height) * Scale * 0.7f;
                var quad = new UIBox2(pos - size / 2, pos + size / 2);
                handle.DrawTextureRect(texture, quad, Color.White);
            }
        }

        var hoveredIsDeadZone = _tiles.TryGetValue(_hovered, out var hoveredTile) && hoveredTile.DeadZone;
        if (!hoveredIsDeadZone && CEHexMath.CubeDistance(_hovered, Vector2i.Zero) <= _radius)
        {
            var tint = _armed is { } essence
                ? (IsLegal(_hovered, essence) ? Color.LightGreen : Color.Red)
                : Color.White;
            DrawCentered(handle, CursorIcon.Frame0(), HexToScreen(_hovered), tint);
        }
    }

    // Draws a line between every pair of hex-adjacent tiles whose aspects are directly related -
    // i.e. an actual valid link in the puzzle's solution, not just two aspects sitting next to
    // each other by coincidence. Each pair is only drawn once (by coordinate ordering).
    private void DrawLinks(DrawingHandleScreen handle)
    {
        foreach (var (hex, tile) in _tiles)
        {
            if (tile.Aspect is not { } aspect)
                continue;

            foreach (var neighbor in CEHexMath.Neighbors(hex))
            {
                if (neighbor.X < hex.X || (neighbor.X == hex.X && neighbor.Y < hex.Y))
                    continue;

                if (!_tiles.TryGetValue(neighbor, out var neighborTile) ||
                    neighborTile.Aspect is not { } neighborAspect ||
                    !_essence.AreDirectlyRelated(aspect, neighborAspect))
                    continue;

                handle.DrawLine(HexToScreen(hex), HexToScreen(neighbor), _linkColor);
            }
        }
    }
}
