using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Utility;

namespace Content.Client._CE.Science;

/// <summary>
/// A single research action entry: a button that executes the action directly. The action's
/// description is shown as a tooltip and its research point cost is shown on the button's
/// right edge.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEResearchActionControl : BoxContainer
{
    private static readonly SpriteSpecifier PointIcon =
        new SpriteSpecifier.Rsi(new ResPath("/Textures/_CE/Interface/Science/science_point.rsi"), "point");

    /// <summary>
    /// Raised when the "Execute" button is pressed.
    /// </summary>
    public event Action? OnExecute;

    public CEResearchActionControl()
    {
        RobustXamlLoader.Load(this);

        CostIcon.Texture = PointIcon.Frame0();

        ExecuteButton.OnPressed += _ => OnExecute?.Invoke();
    }

    public string HeaderText
    {
        set => NameLabel.Text = value;
    }

    public string Description
    {
        set => ExecuteButton.ToolTip = value;
    }

    public int Cost
    {
        set => CostLabel.Text = value.ToString();
    }

    public bool CanExecute
    {
        set => ExecuteButton.Disabled = !value;
    }
}
