using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Utility;

namespace Content.Client._CE.Science;

/// <summary>
/// A single research action entry: a header button that expands to show the action's
/// description, research point cost, and an "Execute" button. Design mirrors
/// <see cref="Content.Client._CE.Roadmap.CERoadmapItem"/>'s expand/collapse header.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEResearchActionControl : BoxContainer
{
    private static readonly SpriteSpecifier PointIcon =
        new SpriteSpecifier.Rsi(new ResPath("/Textures/_CE/Interface/Science/science_point.rsi"), "point");

    /// <summary>
    /// Raised when the header is pressed, regardless of the current expanded state.
    /// The parent decides whether to expand this entry and collapse the others.
    /// </summary>
    public event Action? OnHeaderPressed;

    /// <summary>
    /// Raised when the "Execute" button is pressed.
    /// </summary>
    public event Action? OnExecute;

    public CEResearchActionControl()
    {
        RobustXamlLoader.Load(this);

        CostIcon.Texture = PointIcon.Frame0();

        HeaderButton.OnPressed += _ => OnHeaderPressed?.Invoke();
        ExecuteButton.OnPressed += _ => OnExecute?.Invoke();
    }

    public bool Expanded
    {
        get => ContentsContainer.Visible;
        set => ContentsContainer.Visible = value;
    }

    public string HeaderText
    {
        set => HeaderButton.Text = value;
    }

    public string Description
    {
        set => DescLabel.SetMessage(value);
    }

    public int Cost
    {
        set => CostLabel.Text = value.ToString();
    }

    public bool CanExecute
    {
        set => ExecuteButton.Disabled = !value;
    }
}
