using System.Numerics;
using Content.Client._CE.MagicEssence.Controls;
using Content.Shared._CE.Knowledge.Prototypes;
using Content.Shared._CE.MagicEssence.Prototypes;
using Content.Shared._CE.Science;
using Content.Shared._CE.Science.Components;
using Content.Shared._CE.Science.Prototypes;
using Content.Shared.Containers.ItemSlots;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Science;

[GenerateTypedNameReferences]
public sealed partial class CEResearchTableWindow : DefaultWindow
{
    private const int CostIconSize = 28;

    private static readonly Dictionary<ProtoId<CEMagicEssenceTypePrototype>, int> EmptyPoints = new();

    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    private readonly ItemSlotsSystem _itemSlots = default!;
    private readonly CEResearchTableSystem _researchTable = default!;
    private readonly CEClientScienceSystem _science = default!;

    private readonly Dictionary<ProtoId<CEScienceAreaPrototype>, CEScienceAreaCardControl> _areaCards = new();
    private readonly Dictionary<ProtoId<CEScienceDiscoveryPrototype>, CEScienceDiscoveryCardControl> _discoveryCards = new();

    private EntityUid _owner;
    private ProtoId<CEScienceAreaPrototype>? _selectedArea;
    private EntityUid? _currentProject;
    private ProtoId<CEScienceDiscoveryPrototype>? _selectedDiscovery;
    private Vector2i? _selectedHex;

    public event Action<ProtoId<CEMagicEssenceTypePrototype>, ProtoId<CEMagicEssenceTypePrototype>>? OnMergeAspects;
    public event Action<ProtoId<CEScienceAreaPrototype>>? OnStartResearch;
    public event Action<ProtoId<CEScienceDiscoveryPrototype>>? OnChooseDiscovery;
    public event Action<Vector2i, ProtoId<CEMagicEssenceTypePrototype>>? OnPlaceAspect;
    public event Action? OnFinishResearch;

    public CEResearchTableWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _itemSlots = _entityManager.System<ItemSlotsSystem>();
        _researchTable = _entityManager.System<CEResearchTableSystem>();
        _science = _entityManager.System<CEClientScienceSystem>();

        KnowledgeControl.OnMerge += (first, second) => OnMergeAspects?.Invoke(first, second);
        StartResearchButton.OnPressed += _ =>
        {
            if (_selectedArea is { } areaId)
                OnStartResearch?.Invoke(areaId);
        };
        ChooseDiscoveryButton.OnPressed += _ =>
        {
            if (_selectedDiscovery is { } discoveryId)
                OnChooseDiscovery?.Invoke(discoveryId);
        };
        FinishResearchButton.OnPressed += _ => OnFinishResearch?.Invoke();

        KnowledgeControl.OnMergeWindowSelected += () =>
        {
            _selectedHex = null;
            HexGrid.SetSelected(null);
            KnowledgeControl.SetMergeSelected(true);
            UpdateUi();
        };
        KnowledgeControl.OnEssenceSelectedForPlacement += essence =>
        {
            if (_selectedHex is { } hex)
                OnPlaceAspect?.Invoke(hex, essence);
        };
        HexGrid.OnSelect += hex =>
        {
            _selectedHex = hex;
            KnowledgeControl.SetMergeSelected(false);
            UpdateUi();
        };
        HexGrid.OnViewChanged += OnHexGridViewChanged;

        foreach (var area in _prototype.EnumeratePrototypes<CEScienceAreaPrototype>())
        {
            var card = new CEScienceAreaCardControl(area);
            card.OnSelect += areaId =>
            {
                if (_selectedArea is { } previous && _areaCards.TryGetValue(previous, out var previousCard))
                    previousCard.SetSelected(false);

                _selectedArea = areaId;
                _areaCards[areaId].SetSelected(true);

                UpdateUi();
            };

            _areaCards[area.ID] = card;
            AreaCardsContainer.AddChild(card);
        }
    }

    public void SetEntity(EntityUid owner)
    {
        _owner = owner;
        UpdateUi();
    }

    public void UpdateUi()
    {
        var points = EmptyPoints;
        if (_player.LocalEntity is { } player &&
            _entityManager.TryGetComponent<CEScienceResearchDataComponent>(player, out var researchData))
            points = researchData.Points;

        KnowledgeControl.UpdateKnowledge(points);

        if (_player.LocalEntity is { } localPlayer)
        {
            foreach (var (id, card) in _areaCards)
            {
                var (known, unlockable) = _science.GetAreaProgress(localPlayer, id);
                card.SetProgress(known, unlockable);
            }
        }

        if (!_entityManager.TryGetComponent<CEResearchTableComponent>(_owner, out var table))
            return;

        var item = _itemSlots.GetItemOrNull(_owner, table.PaperSlotId);

        NoPaperLabel.Visible = item is null;
        ActiveContainer.Visible = item is not null;

        if (item is { } itemUid && _entityManager.TryGetComponent<CEUnselectedDiscoveryProjectComponent>(itemUid, out var project))
        {
            AreaPickerContainer.Visible = false;
            DiscoveryPickerContainer.Visible = true;
            ProjectContainer.Visible = false;
            ResetPlacementTarget();
            UpdateDiscoveryPicker(itemUid, project);
            return;
        }

        if (item is { } projectUid && _entityManager.TryGetComponent<CEDiscoveryProjectComponent>(projectUid, out var activeProject))
        {
            AreaPickerContainer.Visible = false;
            DiscoveryPickerContainer.Visible = false;
            ProjectContainer.Visible = true;
            _currentProject = null;
            UpdateProjectContainer(activeProject);
            return;
        }

        AreaPickerContainer.Visible = true;
        DiscoveryPickerContainer.Visible = false;
        ProjectContainer.Visible = false;
        _currentProject = null;
        ResetPlacementTarget();

        CostContainer.RemoveAllChildren();
        if (_selectedArea is { } areaId && _prototype.TryIndex(areaId, out var area))
        {
            foreach (var (essence, amount) in area.Cost)
            {
                var control = new CEEssenceAmountControl { SetSize = new Vector2(CostIconSize, CostIconSize) };
                control.SetEssence(essence, amount);
                CostContainer.AddChild(control);
            }

            var exhausted = _player.LocalEntity is { } actor &&
                             _science.GetAreaProgress(actor, areaId).Unlockable == 0;

            StartResearchButton.Disabled = exhausted || !CESharedScienceSystem.CanAfford(points, area.Cost);
        }
        else
        {
            StartResearchButton.Disabled = true;
        }
    }

    private void UpdateDiscoveryPicker(EntityUid itemUid, CEUnselectedDiscoveryProjectComponent project)
    {
        // Candidates can still be empty here if this update fired before the project's own
        // networked state (spawned this tick) has arrived - rebuild once it does.
        var needsRebuild = _currentProject != itemUid || _discoveryCards.Count == 0 && project.Candidates.Count > 0;
        if (needsRebuild)
        {
            _currentProject = itemUid;
            _selectedDiscovery = null;
            _discoveryCards.Clear();
            DiscoveryCardsContainer.RemoveAllChildren();

            foreach (var discoveryId in project.Candidates)
            {
                if (!_prototype.TryIndex(discoveryId, out var discovery) ||
                    !_prototype.TryIndex(discovery.Knowledge, out var knowledge) ||
                    !_prototype.TryIndex(discovery.Area, out var area))
                    continue;

                var card = new CEScienceDiscoveryCardControl(discovery, knowledge, area.Color);
                card.OnSelect += selected =>
                {
                    if (_selectedDiscovery is { } previous && _discoveryCards.TryGetValue(previous, out var previousCard))
                        previousCard.SetSelected(false);

                    _selectedDiscovery = selected;
                    _discoveryCards[selected].SetSelected(true);

                    UpdateUi();
                };

                _discoveryCards[discoveryId] = card;
                DiscoveryCardsContainer.AddChild(card);
            }
        }

        var isAuthor = project.Player == _player.LocalEntity;
        if (isAuthor)
        {
            ChooseDiscoveryButton.Text = Loc.GetString("ce-research-table-choose-discovery-button");
            ChooseDiscoveryButton.Disabled = _selectedDiscovery is null;
        }
        else
        {
            ChooseDiscoveryButton.Text = Loc.GetString("ce-research-table-not-author");
            ChooseDiscoveryButton.Disabled = true;
        }
    }

    private void UpdateProjectContainer(CEDiscoveryProjectComponent project)
    {
        if (project.Discovery is not { } discoveryId ||
            !_prototype.TryIndex(discoveryId, out var discovery) ||
            !_prototype.TryIndex(discovery.Area, out var area) ||
            !_prototype.TryIndex(discovery.Knowledge, out var knowledge))
            return;

        ProjectTitleLabel.Text = Loc.GetString("ce-research-table-project-title", ("discovery", knowledge.GetTitle(_prototype)));

        var hasParallax = !string.IsNullOrEmpty(area.Parallax);
        if (hasParallax)
            ProjectParallax.ParallaxPrototype = area.Parallax;

        HexGrid.UpdateState(project.Tiles, discovery.Generation.Radius, area.Color, hasParallax);

        FinishResearchButton.Disabled = !_researchTable.IsProjectSolved(project.Tiles);

        if (_selectedHex is { } hex)
        {
            var tiles = project.Tiles;
            var radius = discovery.Generation.Radius;
            KnowledgeControl.SetPlacementLegality(essence => _researchTable.CanPlaceAspect(tiles, radius, hex, essence));
        }
        else
        {
            KnowledgeControl.SetPlacementLegality(null);
        }
    }

    private void ResetPlacementTarget()
    {
        _selectedHex = null;
        HexGrid.SetSelected(null);
        KnowledgeControl.SetMergeSelected(true);
    }

    private void OnHexGridViewChanged(Vector2 offset, float scale)
    {
        const float lag = 0.25f;

        ProjectParallax.Offset = -offset * lag + new Vector2(1000, 1000);
    }
}
