using System.Linq;
using Content.Shared._CE.EntityEffect;
using Content.Shared._CE.Knowledge;
using Content.Shared._CE.Knowledge.Components;
using Content.Shared._CE.MagicEssence.Prototypes;
using Content.Shared._CE.Science;
using Content.Shared._CE.Science.Components;
using Content.Shared._CE.Science.Effects;
using Content.Shared._CE.Science.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._CE.Science;

/// <summary>
/// Left-hand panel of the research table window: shows the selected cell's content (if any), the
/// candidate cards if it's an offered star, and one entry per <see cref="CEResearchActionPrototype"/>
/// that currently applies to it. Purely advisory - the server re-validates everything before acting.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEResearchCellInfoControl : BoxContainer
{
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPlayerManager _player = default!;

    private CEKnowledgeSystem _knowledge = default!;

    /// <summary>
    /// Raised when the player presses an action's "Execute" button, with that action's id.
    /// </summary>
    public event Action<ProtoId<CEResearchActionPrototype>>? OnAction;

    /// <summary>
    /// Raised when the player presses one of an offered star's candidate cards' "Choose" button,
    /// with that candidate's id.
    /// </summary>
    public event Action<ProtoId<CEScienceDiscoveryPrototype>>? OnChooseDiscovery;

    public CEResearchCellInfoControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _knowledge = _entity.System<CEKnowledgeSystem>();
    }

    public void UpdateCell(CEScienceMapCell? cell)
    {
        CardsContainer.Visible = false;
        CardsContainer.RemoveAllChildren();

        switch (cell)
        {
            case CEScienceDeadZoneCell:
                TitleLabel.Visible = true;
                TitleLabel.Text = Loc.GetString("ce-research-cell-dead-zone-title");
                DescLabel.Visible = true;
                DescLabel.SetMessage(Loc.GetString("ce-research-cell-dead-zone-desc"));
                break;

            case CEScienceStarCell starCell when _prototype.TryIndex(starCell.Rarity, out var rarity):
                TitleLabel.Visible = true;
                TitleLabel.Text = Loc.GetString(rarity.Name);
                DescLabel.Visible = true;
                DescLabel.SetMessage(Loc.GetString("ce-research-cell-star-desc"));
                break;

            case CEScienceOfferedStarCell offeredCell when _prototype.TryIndex(offeredCell.Rarity, out var rarity):
                TitleLabel.Visible = true;
                TitleLabel.Text = Loc.GetString("ce-research-cell-offered-star-title");
                DescLabel.Visible = true;
                DescLabel.SetMessage(Loc.GetString("ce-research-cell-offered-star-desc"));

                BuildCards(offeredCell, rarity);
                break;

            case CEScienceDiscoveryCell discoveryCell
                when _prototype.TryIndex(discoveryCell.Discovery, out var discovery)
                     && _prototype.TryIndex(discovery.Knowledge, out var knowledge):
                TitleLabel.Visible = true;
                TitleLabel.Text = Loc.GetString(knowledge.Name);

                var effects = _knowledge.GetKnowledgeEffectDescription(discovery.Knowledge);
                DescLabel.Visible = effects.Length > 0;
                DescLabel.SetMessage(FormattedMessage.FromMarkupPermissive(effects));
                break;

            default:
                TitleLabel.Visible = false;
                DescLabel.Visible = false;
                break;
        }

        ActionsContainer.RemoveAllChildren();

        if (_player.LocalEntity is not { } localEntity)
            return;

        var kind = cell?.Kind ?? CEResearchCellKind.Empty;
        var conditionArgs = new CEEntityEffectArgs(_entity, localEntity, null, default, 0f, localEntity, null);

        _entity.TryGetComponent<CEScienceResearchDataComponent>(localEntity, out var researchData);
        _entity.TryGetComponent<CEKnowledgeComponent>(localEntity, out var knowledgeComp);
        var points = researchData?.Points ?? new Dictionary<ProtoId<CEMagicEssenceTypePrototype>, int>();

        foreach (var action in _prototype.EnumeratePrototypes<CEResearchActionPrototype>())
        {
            if (!action.AllowedCells.HasFlag(kind))
                continue;

            var passes = true;
            foreach (var condition in action.Conditions)
            {
                if (condition.Passes(conditionArgs))
                    continue;

                passes = false;
                break;
            }

            if (!passes)
                continue;

            var cost = action.Cost;

            // "Learn discovery" actions cost the discovery's own price, not the action's generic
            // one, and no longer apply once the local player already knows it.
            if (cell is CEScienceDiscoveryCell discoveryCell && action.Effects.Any(effect => effect is CEResearchLearnDiscovery))
            {
                if (!_prototype.TryIndex(discoveryCell.Discovery, out var discovery))
                    continue;

                if (knowledgeComp?.Known.Contains(discovery.Knowledge) ?? false)
                    continue;

                cost = discovery.Cost;
            }

            var actionId = new ProtoId<CEResearchActionPrototype>(action.ID);
            var entry = new CEResearchActionControl
            {
                HeaderText = Loc.GetString(action.Name),
                Description = action.Desc is { } descText ? Loc.GetString(descText) : string.Empty,
                Cost = cost,
                CanExecute = CESharedScienceSystem.CanAfford(points, cost),
            };

            entry.OnExecute += () => OnAction?.Invoke(actionId);

            ActionsContainer.AddChild(entry);
        }
    }

    /// <summary>
    /// Builds one <see cref="CEScienceDiscoveryCardControl"/> per candidate offered by
    /// <paramref name="offered"/>. Shown alongside (not instead of) the generic action list, so
    /// e.g. BasicScan still works on an offered star.
    /// </summary>
    private void BuildCards(CEScienceOfferedStarCell offered, CEScienceDiscoveryDifficultyPrototype rarity)
    {
        if (_player.LocalEntity is not { } localEntity)
            return;

        _entity.TryGetComponent<CEScienceResearchDataComponent>(localEntity, out var researchData);
        var points = researchData?.Points ?? new Dictionary<ProtoId<CEMagicEssenceTypePrototype>, int>();

        foreach (var discoveryId in offered.Candidates)
        {
            if (!_prototype.TryIndex(discoveryId, out var discovery))
                continue;

            if (!_prototype.TryIndex(discovery.Knowledge, out var knowledge))
                continue;

            var card = new CEScienceDiscoveryCardControl(discovery, knowledge, rarity, _knowledge, points);
            card.OnPressed += () => OnChooseDiscovery?.Invoke(discoveryId);
            CardsContainer.AddChild(card);
        }

        CardsContainer.Visible = true;
    }
}
