using System.Linq;
using Content.Shared._CE.EntityEffect;
using Content.Shared._CE.MagicEssence.Prototypes;
using Content.Shared._CE.Science;
using Content.Shared._CE.Science.Components;
using Content.Shared._CE.Science.Effects;
using Content.Shared._CE.Science.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Science;

/// <summary>
/// Left-hand panel of the research table window: shows the selected cell's content (if any), and
/// one entry per <see cref="CEResearchActionPrototype"/> that currently applies to it. Purely
/// advisory - the server re-validates everything before acting.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEResearchCellInfoControl : BoxContainer
{
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPlayerManager _player = default!;

    /// <summary>
    /// Raised when the player presses an action's "Execute" button, with that action's id.
    /// </summary>
    public event Action<ProtoId<CEResearchActionPrototype>>? OnAction;

    public CEResearchCellInfoControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void UpdateCell(CEScienceMapCell? cell, IReadOnlyDictionary<ProtoId<CEMagicEssenceTypePrototype>, int> points)
    {
        switch (cell)
        {
            case CEScienceDeadZoneCell:
                TitleLabel.Visible = true;
                TitleLabel.Text = Loc.GetString("ce-research-cell-dead-zone-title");
                DescLabel.Visible = true;
                DescLabel.SetMessage(Loc.GetString("ce-research-cell-dead-zone-desc"));
                break;

            case CEScienceAchievementCell achievementCell when _prototype.TryIndex(achievementCell.Achievement, out var achievement):
                TitleLabel.Visible = true;
                TitleLabel.Text = Loc.GetString(achievement.Name);
                DescLabel.Visible = achievement.Desc is not null;
                DescLabel.SetMessage(achievement.Desc is { } desc ? Loc.GetString(desc) : string.Empty);
                break;

            default:
                TitleLabel.Visible = false;
                DescLabel.Visible = false;
                break;
        }

        ActionsContainer.RemoveAllChildren();

        if (_player.LocalEntity is not { } localEntity)
            return;

        var kind = cell?.Kind ?? CEResearchCellKind.Empty;
        var conditionArgs = new CEEntityEffectArgs(_entity, localEntity, null, default, 0f, localEntity, null);

        _entity.TryGetComponent<CEScienceResearchDataComponent>(localEntity, out var researchData);

        foreach (var action in _prototype.EnumeratePrototypes<CEResearchActionPrototype>())
        {
            if (!action.AllowedCells.HasFlag(kind))
                continue;

            var passes = true;
            foreach (var condition in action.Conditions)
            {
                if (condition.Passes(conditionArgs))
                    continue;

                passes = false;
                break;
            }

            if (!passes)
                continue;

            var cost = action.Cost;

            // "Discover achievement" actions cost the achievement's own price, not the action's
            // generic one, and no longer apply once that achievement is already discovered.
            if (cell is CEScienceAchievementCell achievementCell && action.Effects.Any(effect => effect is CEResearchDiscoverAchievement))
            {
                if (!_prototype.TryIndex(achievementCell.Achievement, out var achievement))
                    continue;

                if (researchData?.DiscoveredAchievements.Contains(achievementCell.Achievement) ?? false)
                    continue;

                cost = achievement.Cost;
            }

            var actionId = new ProtoId<CEResearchActionPrototype>(action.ID);
            var entry = new CEResearchActionControl
            {
                HeaderText = Loc.GetString(action.Name),
                Description = action.Desc is { } desc ? Loc.GetString(desc) : string.Empty,
                Cost = cost,
                CanExecute = CESharedScienceSystem.CanAfford(points, cost),
            };

            entry.OnExecute += () => OnAction?.Invoke(actionId);

            ActionsContainer.AddChild(entry);
        }
    }
}
