using System.Globalization;
using System.Linq;
using System.Numerics;
using Content.Client._CE.MagicEssence.Controls;
using Content.Shared._CE.MagicEssence.Prototypes;
using Content.Shared._CE.Science;
using Content.Shared._CE.Science.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._CE.Science;

/// <summary>
/// Client-local, unnetworked record of a "check hypothesis" result: pre-formatted text (either the
/// distance or a sad face if nothing was found within range) and when it should finish fading out.
/// Never sent over the network - see <see cref="CEResearchTableHypothesisResultMessage"/>.
/// </summary>
public readonly record struct CEScienceHypothesisDisplay(string Text, TimeSpan ExpiresAt, TimeSpan Duration);

[GenerateTypedNameReferences]
public sealed partial class CEResearchTableWindow : DefaultWindow
{
    private const int PointsIconSize = 24;

    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IGameTiming _timing = default!;

    private CEResearchTableState? _state;
    private ProtoId<CEScienceAreaPrototype>? _currentArea;
    private readonly Dictionary<ProtoId<CEScienceAreaPrototype>, Vector2i> _selectedPerArea = new();
    private readonly Dictionary<ProtoId<CEScienceAreaPrototype>, Dictionary<Vector2i, CEScienceHypothesisDisplay>> _hypotheses = new();

    public event Action<ProtoId<CEScienceAreaPrototype>, Vector2i, ProtoId<CEResearchActionPrototype>>? OnResearch;

    public CEResearchTableWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        MapControl.OnCellSelected += OnCellSelected;
        MapControl.OnViewChanged += OnMapViewChanged;
        CellInfo.OnAction += OnActionPressed;

        foreach (var area in _prototype.EnumeratePrototypes<CEScienceAreaPrototype>())
        {
            var areaId = area.ID;
            var button = new CEScienceAreaButtonControl(area.Color, Loc.GetString(area.Name));
            button.OnPressed += () => SwitchArea(areaId);

            AreaTabsContainer.AddChild(button);
        }
    }

    public void UpdateState(CEResearchTableState state)
    {
        var firstState = _state is null;
        _state = state;

        if (_currentArea is null)
        {
            var first = _prototype.EnumeratePrototypes<CEScienceAreaPrototype>().FirstOrDefault();
            if (first is not null)
                _currentArea = first.ID;
        }

        if (_currentArea is { } area)
            SwitchArea(area);

        // Only snap the view to the selected cell the very first time the window opens -
        // subsequent refreshes (e.g. after researching a cell) must not move the view.
        if (firstState)
            MapControl.CenterOnSelected();
    }

    private void SwitchArea(ProtoId<CEScienceAreaPrototype> area)
    {
        if (!_prototype.TryIndex(area, out var indexedArea))
            return;

        _currentArea = area;

        // Empty means "no parallax" - never ask the parallax manager to load that.
        if (!string.IsNullOrEmpty(indexedArea.Parallax))
            ParallaxBackground.ParallaxPrototype = indexedArea.Parallax;

        var selected = _selectedPerArea.GetValueOrDefault(area, default);
        MapControl.SetSelected(selected);

        if (_state is not null && _state.Areas.TryGetValue(area, out var data))
            MapControl.UpdateState(data.Cells, data.Researched, indexedArea);
        else
            MapControl.UpdateState(new Dictionary<Vector2i, CEScienceMapCell>(), new HashSet<Vector2i>(), indexedArea);

        var areaHypotheses = _hypotheses.TryGetValue(area, out var existing)
            ? existing
            : new Dictionary<Vector2i, CEScienceHypothesisDisplay>();
        MapControl.UpdateHypotheses(areaHypotheses);

        UpdateInfoPanel();
    }

    /// <summary>
    /// Records a "check hypothesis" result locally so the map can fade it in over
    /// <see cref="CEResearchTableHypothesisResultMessage.Duration"/> - this never touches
    /// <see cref="_state"/>, it's purely a client-side visual.
    /// </summary>
    public void HandleHypothesisResult(CEResearchTableHypothesisResultMessage message)
    {
        if (!_hypotheses.TryGetValue(message.Area, out var areaHypotheses))
        {
            areaHypotheses = new Dictionary<Vector2i, CEScienceHypothesisDisplay>();
            _hypotheses[message.Area] = areaHypotheses;
        }

        var text = message.Distance is { } distance
            ? distance.ToString("F1", CultureInfo.InvariantCulture)
            : "x";

        areaHypotheses[message.Coordinate] = new CEScienceHypothesisDisplay(text, _timing.CurTime + message.Duration, message.Duration);

        if (_currentArea == message.Area)
            MapControl.UpdateHypotheses(areaHypotheses);
    }

    /// <summary>
    /// Refreshes the left-hand info panel for whichever cell is currently selected in the current area.
    /// </summary>
    private void UpdateInfoPanel()
    {
        if (_currentArea is not { } area)
            return;

        var coordinate = _selectedPerArea.GetValueOrDefault(area, default);

        CEScienceMapCell? cell = null;
        if (_state is not null && _state.Areas.TryGetValue(area, out var data))
            data.Cells.TryGetValue(coordinate, out cell);

        var points = _state?.Points ?? new Dictionary<ProtoId<CEMagicEssenceTypePrototype>, int>();

        PointsContainer.RemoveAllChildren();
        foreach (var (essence, amount) in points)
        {
            var control = new CEEssenceAmountControl { SetSize = new Vector2(PointsIconSize, PointsIconSize) };
            control.SetEssence(essence, amount);
            PointsContainer.AddChild(control);
        }

        CellInfo.UpdateCell(cell, points);
    }

    /// <summary>
    /// Keeps the parallax background moving with the map's pan and zoom, but at a fraction of
    /// the rate, for a parallax depth effect.
    /// </summary>
    private void OnMapViewChanged(Vector2 offset, float scale)
    {
        const float lag = 0.25f;

        ParallaxBackground.Offset = -offset * lag + new Vector2(1000, 1000);

        var parallaxScale = 1f + (scale - 1f) * lag;
        ParallaxBackground.ScaleX = parallaxScale;
        ParallaxBackground.ScaleY = parallaxScale;
    }

    private void OnCellSelected(Vector2i coordinate)
    {
        if (_currentArea is not { } area)
            return;

        _selectedPerArea[area] = coordinate;
        UpdateInfoPanel();
    }

    private void OnActionPressed(ProtoId<CEResearchActionPrototype> action)
    {
        if (_currentArea is not { } area)
            return;

        var coordinate = _selectedPerArea.GetValueOrDefault(area, default);
        OnResearch?.Invoke(area, coordinate, action);
    }
}
