using System.Numerics;
using Content.Client._CE.MagicEssence.Controls;
using Content.Shared._CE.MagicEssence.Prototypes;
using Content.Shared._CE.Science;
using Content.Shared._CE.Science.Components;
using Content.Shared._CE.Science.Prototypes;
using Content.Shared.Containers.ItemSlots;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Science;

[GenerateTypedNameReferences]
public sealed partial class CEResearchTableWindow : DefaultWindow
{
    private const int CostIconSize = 28;

    private static readonly Dictionary<ProtoId<CEMagicEssenceTypePrototype>, int> EmptyPoints = new();

    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    private readonly ItemSlotsSystem _itemSlots = default!;

    private readonly Dictionary<ProtoId<CEScienceAreaPrototype>, CEScienceAreaCardControl> _areaCards = new();

    private EntityUid _owner;
    private ProtoId<CEScienceAreaPrototype>? _selectedArea;

    public event Action<ProtoId<CEMagicEssenceTypePrototype>, ProtoId<CEMagicEssenceTypePrototype>>? OnMergeAspects;

    public CEResearchTableWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _itemSlots = _entityManager.System<ItemSlotsSystem>();

        KnowledgeControl.OnMerge += (first, second) => OnMergeAspects?.Invoke(first, second);

        foreach (var area in _prototype.EnumeratePrototypes<CEScienceAreaPrototype>())
        {
            var card = new CEScienceAreaCardControl(area);
            card.OnSelect += areaId =>
            {
                if (_selectedArea is { } previous && _areaCards.TryGetValue(previous, out var previousCard))
                    previousCard.SetSelected(false);

                _selectedArea = areaId;
                _areaCards[areaId].SetSelected(true);

                UpdateUi();
            };

            _areaCards[area.ID] = card;
            AreaCardsContainer.AddChild(card);
        }
    }

    public void SetEntity(EntityUid owner)
    {
        _owner = owner;
        UpdateUi();
    }

    public void UpdateUi()
    {
        var points = EmptyPoints;
        if (_player.LocalEntity is { } player &&
            _entityManager.TryGetComponent<CEScienceResearchDataComponent>(player, out var researchData))
            points = researchData.Points;

        KnowledgeControl.UpdateKnowledge(points);

        CostContainer.RemoveAllChildren();
        if (_selectedArea is { } areaId && _prototype.TryIndex(areaId, out var area))
        {
            foreach (var (essence, amount) in area.Cost)
            {
                var control = new CEEssenceAmountControl { SetSize = new Vector2(CostIconSize, CostIconSize) };
                control.SetEssence(essence, amount);
                CostContainer.AddChild(control);
            }

            StartResearchButton.Disabled = !CESharedScienceSystem.CanAfford(points, area.Cost);
        }
        else
        {
            StartResearchButton.Disabled = true;
        }

        if (!_entityManager.TryGetComponent<CEResearchTableComponent>(_owner, out var table))
            return;

        var hasPaper = _itemSlots.GetItemOrNull(_owner, table.PaperSlotId) is not null;

        NoPaperLabel.Visible = !hasPaper;
        ActiveContainer.Visible = hasPaper;
    }
}
