using Content.Shared._CE.Science.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Science;

[GenerateTypedNameReferences]
public sealed partial class CEScienceAreaCardControl : PanelContainer
{
    private static readonly StyleBoxFlat SelectedBox = new()
    {
        BorderThickness = new Thickness(2),
        BorderColor = Color.FromHex("#53b58b"),
    };

    [Dependency] private IEntityManager _entity = default!;

    public readonly ProtoId<CEScienceAreaPrototype> AreaId;

    public event Action<ProtoId<CEScienceAreaPrototype>>? OnSelect;

    private readonly StyleBox? _normalBox;

    public CEScienceAreaCardControl(CEScienceAreaPrototype area)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _normalBox = PanelOverride;

        AreaId = area.ID;

        HeaderPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = area.Color };
        NameLabel.Text = Loc.GetString(area.Name);
        DescLabel.Text = area.Desc is { } desc ? Loc.GetString(desc) : string.Empty;
        IconTexture.Texture = _entity.System<SpriteSystem>().Frame0(area.Icon);

        OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            args.Handle();
            OnSelect?.Invoke(AreaId);
        };
    }

    public void SetSelected(bool selected)
    {
        PanelOverride = selected ? SelectedBox : _normalBox;
    }
}
