using System.Linq;
using System.Numerics;
using Content.Client._CE.MagicEssence.Controls;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._CE.MagicEssence.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Science;

/// <summary>
/// Every essence type of research points a character currently holds, one icon+amount per essence
/// (see <see cref="CEEssenceAmountControl"/>), wrapped at <see cref="MaxPerRow"/> per row and
/// grouped into a scrollable column with a divider between each thaumaturgical tier.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEScienceKnowledgeControl : BoxContainer
{
    private const int IconSize = 28;
    private const int MaxPerRow = 6;

    [Dependency] private IPrototypeManager _prototype = default!;

    public CEScienceKnowledgeControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void UpdateKnowledge(IReadOnlyDictionary<ProtoId<CEMagicEssenceTypePrototype>, int> points)
    {
        RowsContainer.RemoveAllChildren();

        var byTier = new SortedDictionary<int, List<(ProtoId<CEMagicEssenceTypePrototype> Essence, int Amount)>>();
        foreach (var (essence, amount) in points)
        {
            var tier = _prototype.TryIndex(essence, out CEMagicEssenceTypePrototype? proto) ? proto.Tier : 0;
            if (!byTier.TryGetValue(tier, out var entries))
            {
                entries = new List<(ProtoId<CEMagicEssenceTypePrototype>, int)>();
                byTier[tier] = entries;
            }

            entries.Add((essence, amount));
        }

        var firstTier = true;
        foreach (var entries in byTier.Values)
        {
            // Most plentiful aspects first.
            entries.Sort((a, b) =>
            {
                var byAmount = b.Amount.CompareTo(a.Amount);
                return byAmount != 0 ? byAmount : string.CompareOrdinal(a.Essence.Id, b.Essence.Id);
            });

            if (!firstTier)
                RowsContainer.AddChild(new HSeparator { Margin = new Thickness(0, 4, 0, 4) });
            firstTier = false;

            foreach (var rowEntries in entries.Chunk(MaxPerRow))
            {
                var row = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    SeparationOverride = 4,
                };

                foreach (var (essence, amount) in rowEntries)
                {
                    var control = new CEEssenceAmountControl { SetSize = new Vector2(IconSize, IconSize) };
                    control.SetEssence(essence, amount);
                    row.AddChild(control);
                }

                RowsContainer.AddChild(row);
            }
        }
    }
}
