using System.Numerics;
using Content.Client._CE.MagicEssence.Controls;
using Content.Shared._CE.Knowledge;
using Content.Shared._CE.Knowledge.Prototypes;
using Content.Shared._CE.MagicEssence.Prototypes;
using Content.Shared._CE.Science;
using Content.Shared._CE.Science.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._CE.Science;

/// <summary>
/// One candidate card in an opened star's 3-choice offer: the discovery's icon/name/description
/// (via its linked knowledge), its rarity's colour, its cost, and a "choose" button disabled if
/// the local player can't afford it.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEScienceDiscoveryCardControl : BoxContainer
{
    private const int CostIconSize = 18;

    /// <summary>
    /// Raised when the "Choose" button is pressed.
    /// </summary>
    public event Action? OnPressed;

    public CEScienceDiscoveryCardControl(
        CEScienceDiscoveryPrototype discovery,
        CEKnowledgePrototype knowledge,
        CEScienceDiscoveryDifficultyPrototype rarity,
        CEKnowledgeSystem knowledgeSystem,
        IReadOnlyDictionary<ProtoId<CEMagicEssenceTypePrototype>, int> points)
    {
        RobustXamlLoader.Load(this);

        Background.ModulateSelfOverride = rarity.Color;
        NameLabel.Text = Loc.GetString(knowledge.Name);
        RarityLabel.Text = Loc.GetString(rarity.Name);
        IconTexture.Texture = knowledge.Icon.Frame0();

        var effects = knowledgeSystem.GetKnowledgeEffectDescription(discovery.Knowledge);
        DescLabel.SetMessage(FormattedMessage.FromMarkupPermissive(effects));

        CostContainer.RemoveAllChildren();
        foreach (var (essence, amount) in discovery.Cost)
        {
            var control = new CEEssenceAmountControl { SetSize = new Vector2(CostIconSize, CostIconSize) };
            control.SetEssence(essence, amount);
            CostContainer.AddChild(control);
        }

        ChooseButton.Disabled = !CESharedScienceSystem.CanAfford(points, discovery.Cost);
        ChooseButton.OnPressed += _ => OnPressed?.Invoke();
    }
}
