using System.Numerics;
using Content.Shared._CE.Knowledge.Components;
using Content.Shared._CE.Science;
using Content.Shared._CE.Science.Components;
using Content.Shared._CE.Science.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._CE.Science;

/// <summary>
/// Draggable, zoomable grid view of a science area's research map. Draws a checkerboard square
/// for every coordinate the player has researched, an icon on top for tiles with content (dead
/// zones, stars, discoveries, ...), and an outline around the perimeter of the researched zone.
/// All theme sprites (background, dead zone, unknown) and the tint colour come from the current
/// <see cref="CEScienceAreaPrototype"/>. If the area has no parallax configured, a plain black
/// background is drawn instead.
/// Every texture is drawn at its own native pixel size (scaled only by zoom) rather than being
/// stretched to fit a uniform tile box.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEScienceMapControl : BoxContainer
{
    private const float LocalScaleDefault = 3f;
    private const float LocalScaleMin = 0.5f;
    private const float LocalScaleMax = 6f;

    /// <summary>
    /// Distance between adjacent tiles, matching the native size of bg.rsi.
    /// </summary>
    private const float TileSpacing = 9f;

    private static readonly SpriteSpecifier StarIcon = new SpriteSpecifier.Rsi(new ResPath("/Textures/_CE/Interface/Science/science_point.rsi"), "star");
    private static readonly SpriteSpecifier OfferedStarIcon = new SpriteSpecifier.Rsi(new ResPath("/Textures/_CE/Interface/Science/science_point.rsi"), "star_offered");

    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPlayerManager _player = default!;

    private Dictionary<Vector2i, CEScienceMapTile> _tiles = new();
    private HashSet<Vector2i> _researched = new();
    private Vector2i _selected;
    private CEScienceAreaPrototype? _area;

    private bool _dragging;
    private bool _needsRecenter;
    private Vector2 _previousMousePosition;
    private Vector2 _globalOffset;
    private float _localScale = LocalScaleDefault;

    private float Scale => UIScale * _localScale;

    /// <summary>
    /// Raised when the player clicks a tile. Does not imply the tile gets researched.
    /// </summary>
    public event Action<Vector2i>? OnTileSelected;

    /// <summary>
    /// Raised every draw with the current pan offset and zoom, so a background
    /// <see cref="Content.Client.Parallax.ParallaxControl"/> can be kept in sync (with a lag,
    /// for a parallax effect).
    /// </summary>
    public event Action<Vector2, float>? OnViewChanged;

    public CEScienceMapControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Sets the selected tile without moving the view. Does not imply the tile gets researched.
    /// </summary>
    public void SetSelected(Vector2i coordinate)
    {
        _selected = coordinate;
    }

    /// <summary>
    /// Re-centers the view on the currently selected tile. Only call this for the very first
    /// time the map is shown (or an explicit "reset view" action) - not on every state refresh.
    /// </summary>
    public void CenterOnSelected()
    {
        _needsRecenter = true;
    }

    public void UpdateState(Dictionary<Vector2i, CEScienceMapTile> tiles, HashSet<Vector2i> researched, CEScienceAreaPrototype area)
    {
        _tiles = tiles;
        _researched = researched;
        _area = area;
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        if (args.Handled)
            return;

        var cursor = (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;
        var oldScale = Scale;

        _localScale = MathHelper.Clamp(_localScale + 0.1f * args.Delta.Y, LocalScaleMin, LocalScaleMax);

        // Keep the point under the cursor fixed on screen instead of zooming from the corner.
        var newScale = Scale;
        _globalOffset = cursor - (cursor - _globalOffset) * (newScale / oldScale);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Handled)
            return;

        if (args.Function == EngineKeyFunctions.UIClick)
        {
            _dragging = true;

            var cursor = (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;
            var tile = ScreenToTile(cursor);

            // Only already-researched tiles can be selected - clicking into the fog does nothing.
            if (_researched.Contains(tile))
            {
                _selected = tile;
                OnTileSelected?.Invoke(_selected);
                UserInterfaceManager.ClickSound();
            }
        }

        if (args.Function == EngineKeyFunctions.UIRightClick)
        {
            _localScale = LocalScaleDefault;
            CenterOnSelected();
        }
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Handled || args.Function != EngineKeyFunctions.UIClick)
            return;

        _dragging = false;
    }

    private Vector2 TileToScreen(Vector2i coordinate)
    {
        return TileToScreen(new Vector2(coordinate.X, coordinate.Y));
    }

    private Vector2 TileToScreen(Vector2 coordinate)
    {
        return new Vector2(coordinate.X, -coordinate.Y) * TileSpacing * Scale + _globalOffset;
    }

    private Vector2i ScreenToTile(Vector2 screen)
    {
        var local = (screen - _globalOffset) / (TileSpacing * Scale);
        return new Vector2i((int) MathF.Round(local.X), (int) MathF.Round(-local.Y));
    }

    private void DrawCentered(DrawingHandleScreen handle, Texture texture, Vector2 center, Color? tint = null)
    {
        var size = new Vector2(texture.Width, texture.Height) * Scale;
        var quad = new UIBox2(center - size / 2, center + size / 2);
        handle.DrawTextureRect(texture, quad, tint ?? Color.White);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (_needsRecenter)
        {
            _globalOffset = PixelSize / 2 - new Vector2(_selected.X, -_selected.Y) * TileSpacing * Scale;
            _needsRecenter = false;
        }

        var cursor = (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;

        if (_dragging)
        {
            var delta = cursor - _previousMousePosition;
            _globalOffset += delta;
        }

        _previousMousePosition = cursor;

        OnViewChanged?.Invoke(_globalOffset, _localScale);

        if (_area is null)
            return;

        // No parallax configured for this area - draw a plain black background instead.
        if (string.IsNullOrEmpty(_area.Parallax))
            handle.DrawRect(PixelSizeBox, Color.Black);

        var areaColor = _area.Color;

        // Pass 1: backgrounds for every researched tile, so a neighbour's oversized icon can
        // never get painted over by a later tile's background square.
        foreach (var coordinate in _researched)
        {
            var pos = TileToScreen(coordinate);

            var parity = ((coordinate.X + coordinate.Y) % 2 + 2) % 2;
            var bg = parity == 0 ? _area.MapBgLight : _area.MapBgDark;
            DrawCentered(handle, bg.Frame0(), pos);
        }

        // Pass 2: icons on top of every background.
        _entity.TryGetComponent<CEKnowledgeComponent>(_player.LocalEntity, out var knowledgeComp);

        foreach (var coordinate in _researched)
        {
            if (!_tiles.TryGetValue(coordinate, out var tile))
                continue;

            switch (tile)
            {
                case CEScienceDeadZoneTile:
                    DrawCentered(handle, _area.MapDeadZoneIcon.Frame0(), TileToScreen(coordinate));
                    break;
                case CEScienceStarTile starTile:
                {
                    var tint = _prototype.TryIndex(starTile.Rarity, out var rarity) ? rarity.Color : Color.White;
                    DrawCentered(handle, StarIcon.Frame0(), TileToScreen(coordinate), tint);
                    break;
                }
                case CEScienceOfferedStarTile offeredTile:
                {
                    var tint = _prototype.TryIndex(offeredTile.Rarity, out var rarity) ? rarity.Color : Color.White;
                    DrawCentered(handle, OfferedStarIcon.Frame0(), TileToScreen(coordinate), tint);
                    break;
                }
                case CEScienceDiscoveryTile discoveryTile:
                {
                    SpriteSpecifier? icon = null;
                    if (_prototype.TryIndex(discoveryTile.Discovery, out var discovery) &&
                        _prototype.TryIndex(discovery.Knowledge, out var knowledge))
                        icon = knowledge.Icon;

                    var texture = icon?.Frame0() ?? _area.MapUnknownIcon.Frame0();
                    var discovered = discovery is not null && (knowledgeComp?.Known.Contains(discovery.Knowledge) ?? false);

                    if (!discovered)
                        // Undiscovered discoveries are drawn tinted translucent white, whatever their icon.
                        DrawCentered(handle, texture, TileToScreen(coordinate), Color.White.WithAlpha(0.5f));
                    else if (icon is not null)
                        DrawCentered(handle, texture, TileToScreen(coordinate));
                    else
                        // Tinted with the area's colour - the fallback sprite is a plain white "?".
                        DrawCentered(handle, texture, TileToScreen(coordinate), areaColor);

                    break;
                }
            }
        }

        // Outline around the perimeter of the researched zone, one native pixel thick, drawn
        // just outside the tile's edge.
        var half = TileSpacing * Scale / 2f;
        var thickness = Scale;

        foreach (var coordinate in _researched)
        {
            var pos = TileToScreen(coordinate);
            var left = pos.X - half;
            var right = pos.X + half;
            var top = pos.Y - half;
            var bottom = pos.Y + half;

            if (!_researched.Contains(coordinate + new Vector2i(0, 1)))
                handle.DrawRect(new UIBox2(left, top - thickness, right, top), areaColor);

            if (!_researched.Contains(coordinate + new Vector2i(0, -1)))
                handle.DrawRect(new UIBox2(left, bottom, right, bottom + thickness), areaColor);

            if (!_researched.Contains(coordinate + new Vector2i(-1, 0)))
                handle.DrawRect(new UIBox2(left - thickness, top, left, bottom), areaColor);

            if (!_researched.Contains(coordinate + new Vector2i(1, 0)))
                handle.DrawRect(new UIBox2(right, top, right + thickness, bottom), areaColor);
        }
    }
}
