using System.Numerics;
using Content.Client.Resources;
using Content.Shared._CE.Science;
using Content.Shared._CE.Science.Components;
using Content.Shared._CE.Science.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._CE.Science;

/// <summary>
/// Draggable, zoomable grid view of a science area's research map. Draws a checkerboard square
/// for every coordinate the player has researched, an icon on top for cells with content (dead
/// zones, achievements, ...), an outline around the perimeter of the researched zone, and a
/// cursor on the selected cell. All theme sprites (background, dead zone, unknown) and the tint
/// colour come from the current <see cref="CEScienceAreaPrototype"/>. If the area has no
/// parallax configured, a plain black background is drawn instead.
/// Every texture is drawn at its own native pixel size (scaled only by zoom) rather than being
/// stretched to fit a uniform cell box.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEScienceMapControl : BoxContainer
{
    private const float LocalScaleDefault = 3f;
    private const float LocalScaleMin = 0.5f;
    private const float LocalScaleMax = 6f;

    /// <summary>
    /// How quickly the visual cursor catches up to the selected cell. Higher is faster.
    /// </summary>
    private const float CursorLerpSpeed = 12f;

    /// <summary>
    /// Distance between adjacent cells, matching the native size of bg.rsi.
    /// </summary>
    private const float CellSpacing = 9f;

    private const int HypothesisFontSize = 24;

    private static readonly SpriteSpecifier CursorIcon = new SpriteSpecifier.Rsi(new ResPath("/Textures/_CE/Interface/Science/cursor.rsi"), "cursor");

    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IResourceCache _resourceCache = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPlayerManager _player = default!;

    private readonly Font _hypothesisFont;

    private Dictionary<Vector2i, CEScienceMapCell> _cells = new();
    private HashSet<Vector2i> _researched = new();
    private Dictionary<Vector2i, CEScienceHypothesisDisplay> _hypotheses = new();
    private Vector2i _selected;
    private Vector2 _cursorPos;
    private CEScienceAreaPrototype? _area;

    private bool _dragging;
    private bool _needsRecenter;
    private Vector2 _previousMousePosition;
    private Vector2 _globalOffset;
    private float _localScale = LocalScaleDefault;

    private float Scale => UIScale * _localScale;

    /// <summary>
    /// Raised when the player clicks a cell. Does not imply the cell gets researched.
    /// </summary>
    public event Action<Vector2i>? OnCellSelected;

    /// <summary>
    /// Raised every draw with the current pan offset and zoom, so a background
    /// <see cref="Content.Client.Parallax.ParallaxControl"/> can be kept in sync (with a lag,
    /// for a parallax effect).
    /// </summary>
    public event Action<Vector2, float>? OnViewChanged;

    public CEScienceMapControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _hypothesisFont = _resourceCache.GetFont("/Fonts/_CE/Volkorn/VollkornSC-Regular.ttf", HypothesisFontSize);
    }

    /// <summary>
    /// Sets the selected cell without moving the view. Does not imply the cell gets researched.
    /// </summary>
    public void SetSelected(Vector2i coordinate)
    {
        _selected = coordinate;
    }

    /// <summary>
    /// Re-centers the view on the currently selected cell. Only call this for the very first
    /// time the map is shown (or an explicit "reset view" action) - not on every state refresh.
    /// </summary>
    public void CenterOnSelected()
    {
        _needsRecenter = true;
    }

    public void UpdateState(Dictionary<Vector2i, CEScienceMapCell> cells, HashSet<Vector2i> researched, CEScienceAreaPrototype area)
    {
        _cells = cells;
        _researched = researched;
        _area = area;
    }

    /// <summary>
    /// Replaces the currently displayed "check hypothesis" readouts. Kept separate from
    /// <see cref="UpdateState"/> since these are purely client-local and update independently of
    /// the server's authoritative map state.
    /// </summary>
    public void UpdateHypotheses(Dictionary<Vector2i, CEScienceHypothesisDisplay> hypotheses)
    {
        _hypotheses = hypotheses;
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        if (args.Handled)
            return;

        var cursor = (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;
        var oldScale = Scale;

        _localScale = MathHelper.Clamp(_localScale + 0.1f * args.Delta.Y, LocalScaleMin, LocalScaleMax);

        // Keep the point under the cursor fixed on screen instead of zooming from the corner.
        var newScale = Scale;
        _globalOffset = cursor - (cursor - _globalOffset) * (newScale / oldScale);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Handled)
            return;

        if (args.Function == EngineKeyFunctions.UIClick)
        {
            _dragging = true;

            var cursor = (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;
            var cell = ScreenToCell(cursor);

            // Only already-researched cells can be selected - clicking into the fog does nothing.
            if (_researched.Contains(cell))
            {
                _selected = cell;
                OnCellSelected?.Invoke(_selected);
                UserInterfaceManager.ClickSound();
            }
        }

        if (args.Function == EngineKeyFunctions.UIRightClick)
        {
            _localScale = LocalScaleDefault;
            CenterOnSelected();
        }
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Handled || args.Function != EngineKeyFunctions.UIClick)
            return;

        _dragging = false;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var target = new Vector2(_selected.X, _selected.Y);
        var t = MathF.Min(1f, CursorLerpSpeed * args.DeltaSeconds);
        _cursorPos = Vector2.Lerp(_cursorPos, target, t);
    }

    private Vector2 CellToScreen(Vector2i coordinate)
    {
        return CellToScreen(new Vector2(coordinate.X, coordinate.Y));
    }

    private Vector2 CellToScreen(Vector2 coordinate)
    {
        return new Vector2(coordinate.X, -coordinate.Y) * CellSpacing * Scale + _globalOffset;
    }

    private Vector2i ScreenToCell(Vector2 screen)
    {
        var local = (screen - _globalOffset) / (CellSpacing * Scale);
        return new Vector2i((int) MathF.Round(local.X), (int) MathF.Round(-local.Y));
    }

    private void DrawCentered(DrawingHandleScreen handle, Texture texture, Vector2 center, Color? tint = null)
    {
        var size = new Vector2(texture.Width, texture.Height) * Scale;
        var quad = new UIBox2(center - size / 2, center + size / 2);
        handle.DrawTextureRect(texture, quad, tint ?? Color.White);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (_needsRecenter)
        {
            _globalOffset = PixelSize / 2 - new Vector2(_selected.X, -_selected.Y) * CellSpacing * Scale;
            _needsRecenter = false;
        }

        var cursor = (UserInterfaceManager.MousePositionScaled.Position * UIScale) - GlobalPixelPosition;

        if (_dragging)
        {
            var delta = cursor - _previousMousePosition;
            _globalOffset += delta;
        }

        _previousMousePosition = cursor;

        OnViewChanged?.Invoke(_globalOffset, _localScale);

        if (_area is null)
            return;

        // No parallax configured for this area - draw a plain black background instead.
        if (string.IsNullOrEmpty(_area.Parallax))
            handle.DrawRect(PixelSizeBox, Color.Black);

        var areaColor = _area.Color;

        // Pass 1: backgrounds for every researched cell, so a neighbour's oversized icon can
        // never get painted over by a later cell's background square.
        foreach (var coordinate in _researched)
        {
            var pos = CellToScreen(coordinate);

            var parity = ((coordinate.X + coordinate.Y) % 2 + 2) % 2;
            var bg = parity == 0 ? _area.MapBgLight : _area.MapBgDark;
            DrawCentered(handle, bg.Frame0(), pos);
        }

        // Pass 2: icons on top of every background.
        _entity.TryGetComponent<CEScienceResearchDataComponent>(_player.LocalEntity, out var researchData);

        foreach (var coordinate in _researched)
        {
            if (!_cells.TryGetValue(coordinate, out var cell))
                continue;

            switch (cell)
            {
                case CEScienceDeadZoneCell:
                    DrawCentered(handle, _area.MapDeadZoneIcon.Frame0(), CellToScreen(coordinate));
                    break;
                case CEScienceAchievementCell achievementCell:
                {
                    _prototype.TryIndex(achievementCell.Achievement, out var achievement);
                    var icon = achievement?.Icon;
                    var texture = icon?.Frame0() ?? _area.MapUnknownIcon.Frame0();
                    var discovered = researchData?.DiscoveredAchievements.Contains(achievementCell.Achievement) ?? false;

                    if (!discovered)
                        // Undiscovered achievements are drawn tinted translucent white, whatever their icon.
                        DrawCentered(handle, texture, CellToScreen(coordinate), Color.White.WithAlpha(0.5f));
                    else if (icon is not null)
                        DrawCentered(handle, texture, CellToScreen(coordinate));
                    else
                        // Tinted with the area's colour - the fallback sprite is a plain white "?".
                        DrawCentered(handle, texture, CellToScreen(coordinate), areaColor);

                    break;
                }
            }
        }

        // Pass 3: fading "check hypothesis" distance readouts, drawn on top of any cell icon.
        var now = _timing.CurTime;
        foreach (var (coordinate, hypothesis) in _hypotheses)
        {
            var remaining = (float) (hypothesis.ExpiresAt - now).TotalSeconds;
            var duration = (float) hypothesis.Duration.TotalSeconds;

            if (remaining <= 0f || duration <= 0f)
                continue;

            var alpha = MathHelper.Clamp(remaining / duration, 0f, 1f);
            var dims = handle.GetDimensions(_hypothesisFont, hypothesis.Text, 1f);
            var pos = CellToScreen(coordinate) - dims / 2f;

            handle.DrawString(_hypothesisFont, pos, hypothesis.Text, Color.White.WithAlpha(alpha));
        }

        // Outline around the perimeter of the researched zone, one native pixel thick, drawn
        // just outside the cell's edge.
        var half = CellSpacing * Scale / 2f;
        var thickness = Scale;

        foreach (var coordinate in _researched)
        {
            var pos = CellToScreen(coordinate);
            var left = pos.X - half;
            var right = pos.X + half;
            var top = pos.Y - half;
            var bottom = pos.Y + half;

            if (!_researched.Contains(coordinate + new Vector2i(0, 1)))
                handle.DrawRect(new UIBox2(left, top - thickness, right, top), areaColor);

            if (!_researched.Contains(coordinate + new Vector2i(0, -1)))
                handle.DrawRect(new UIBox2(left, bottom, right, bottom + thickness), areaColor);

            if (!_researched.Contains(coordinate + new Vector2i(-1, 0)))
                handle.DrawRect(new UIBox2(left - thickness, top, left, bottom), areaColor);

            if (!_researched.Contains(coordinate + new Vector2i(1, 0)))
                handle.DrawRect(new UIBox2(right, top, right + thickness, bottom), areaColor);
        }

        // Cursor eases towards the selected cell rather than snapping instantly.
        DrawCentered(handle, CursorIcon.Frame0(), CellToScreen(_cursorPos));
    }
}
