using Content.Shared._CE.Knowledge.Prototypes;
using Content.Shared._CE.Science.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Science;

[GenerateTypedNameReferences]
public sealed partial class CEScienceDiscoveryCardControl : PanelContainer
{
    private static readonly StyleBoxFlat SelectedBox = new()
    {
        BorderThickness = new Thickness(2),
        BorderColor = Color.FromHex("#53b58b"),
    };

    [Dependency] private IEntityManager _entity = default!;

    public readonly ProtoId<CEScienceDiscoveryPrototype> DiscoveryId;

    public event Action<ProtoId<CEScienceDiscoveryPrototype>>? OnSelect;

    private readonly StyleBox? _normalBox;

    public CEScienceDiscoveryCardControl(CEScienceDiscoveryPrototype discovery, CEKnowledgePrototype knowledge, Color headerColor)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _normalBox = PanelOverride;

        DiscoveryId = discovery.ID;

        HeaderPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = headerColor };
        NameLabel.Text = Loc.GetString(knowledge.Name);
        IconTexture.Texture = _entity.System<SpriteSystem>().Frame0(knowledge.Icon);

        OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            args.Handle();
            OnSelect?.Invoke(DiscoveryId);
        };
    }

    public void SetSelected(bool selected)
    {
        PanelOverride = selected ? SelectedBox : _normalBox;
    }
}
