using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.Science;

[GenerateTypedNameReferences]
public sealed partial class CEScienceAreaButtonControl : Control
{
    public event Action? OnPressed;

    public CEScienceAreaButtonControl(Color color, string label)
    {
        RobustXamlLoader.Load(this);

        ColorPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
        AreaLabel.Text = label;

        MainButton.OnPressed += _ => OnPressed?.Invoke();
    }
}
