using Content.Client._CE.Skill;
using Content.Shared._CE.Science.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Science;

[GenerateTypedNameReferences]
public sealed partial class CEScienceDiscoveryCardControl : PanelContainer
{
    private static readonly StyleBoxFlat SelectedBox = new()
    {
        BorderThickness = new Thickness(2),
        BorderColor = Color.FromHex("#53b58b"),
    };

    [Dependency] private IEntityManager _entity = default!;

    public readonly ProtoId<CEScienceDiscoveryPrototype> DiscoveryId;

    public event Action<ProtoId<CEScienceDiscoveryPrototype>>? OnSelect;

    private readonly StyleBox? _normalBox;

    public CEScienceDiscoveryCardControl(CEScienceDiscoveryPrototype discovery, Color headerColor)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _normalBox = PanelOverride;

        DiscoveryId = discovery.ID;

        var skillSystem = _entity.System<CEClientSkillSystem>();

        HeaderPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = headerColor };
        NameLabel.Text = skillSystem.GetSkillName(discovery.Skill);
        ToolTip = skillSystem.GetSkillDescription(discovery.Skill);

        var texture = skillSystem.GetSkillIcon(discovery.Skill);
        if (texture is not null)
        {
            IconTexture.Visible = true;
            IconTexture.Texture = _entity.System<SpriteSystem>().Frame0(texture);
        }
        else if (skillSystem.GetSkillPreviewEntity(discovery.Skill) is { } previewEntity)
        {
            EntityView.Visible = true;
            EntityView.SetPrototype(previewEntity);
        }

        DescLabel.Text = skillSystem.GetSkillEffectDescription(discovery.Skill);

        OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            args.Handle();
            OnSelect?.Invoke(DiscoveryId);
        };
    }

    public void SetSelected(bool selected)
    {
        PanelOverride = selected ? SelectedBox : _normalBox;
    }
}
