using System.Linq;
using System.Numerics;
using Content.Client._CE.MagicEssence.Controls;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._CE.MagicEssence.Prototypes;
using Content.Shared._CE.MagicEssence.Systems;
using Content.Shared._CE.Science;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Science;

/// <summary>
/// Every essence type of research points a character currently holds, one icon+amount per essence
/// (see <see cref="CEEssenceAmountControl"/>), wrapped at <see cref="MaxPerRow"/> per row and
/// grouped into a scrollable column with a divider between each thaumaturgical tier. Also hosts the
/// "merge 2 aspects into a higher-tier one" picker at the bottom - see <see cref="OnEssenceClicked"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEScienceKnowledgeControl : BoxContainer
{
    private const int IconSize = 28;
    private const int MaxPerRow = 6;

    private static readonly Color DimColor = Color.White.WithAlpha(0.12f);

    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IEntityManager _entity = default!;

    private CEMagicEssenceSystem _essence = default!;

    private IReadOnlyDictionary<ProtoId<CEMagicEssenceTypePrototype>, int> _points =
        new Dictionary<ProtoId<CEMagicEssenceTypePrototype>, int>();

    private readonly Dictionary<ProtoId<CEMagicEssenceTypePrototype>, CEEssenceAmountControl> _essenceControls = new();

    private ProtoId<CEMagicEssenceTypePrototype>? _slot1;
    private ProtoId<CEMagicEssenceTypePrototype>? _slot2;

    private bool _mergeSelected = true;

    /// <summary>
    /// Raised when the merge button is pressed with two compatible, affordable aspects selected.
    /// </summary>
    public event Action<ProtoId<CEMagicEssenceTypePrototype>, ProtoId<CEMagicEssenceTypePrototype>>? OnMerge;

    /// <summary>Raised when "Combine Aspects" is pressed, asking to become the placement target again.</summary>
    public event Action? OnMergeWindowSelected;

    /// <summary>Raised when an essence is clicked while the merge window is not the selected target.</summary>
    public event Action<ProtoId<CEMagicEssenceTypePrototype>>? OnEssenceSelectedForPlacement;

    public CEScienceKnowledgeControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _essence = _entity.System<CEMagicEssenceSystem>();

        MergeButton.OnPressed += _ =>
        {
            if (_slot1 is { } first && _slot2 is { } second)
                OnMerge?.Invoke(first, second);
        };

        Slot1Panel.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick || _slot1 is null)
                return;

            args.Handle();
            _slot1 = null;
            UpdateMergeUi();
        };

        Slot2Panel.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick || _slot2 is null)
                return;

            args.Handle();
            _slot2 = null;
            UpdateMergeUi();
        };

        CombineButton.OnPressed += _ => OnMergeWindowSelected?.Invoke();
    }

    public void UpdateKnowledge(IReadOnlyDictionary<ProtoId<CEMagicEssenceTypePrototype>, int> points)
    {
        _points = points;

        RowsContainer.RemoveAllChildren();
        _essenceControls.Clear();

        var byTier = new SortedDictionary<int, List<(ProtoId<CEMagicEssenceTypePrototype> Essence, int Amount)>>();
        foreach (var (essence, amount) in points)
        {
            var tier = _prototype.TryIndex(essence, out CEMagicEssenceTypePrototype? proto) ? proto.Tier : 0;
            if (!byTier.TryGetValue(tier, out var entries))
            {
                entries = new List<(ProtoId<CEMagicEssenceTypePrototype>, int)>();
                byTier[tier] = entries;
            }

            entries.Add((essence, amount));
        }

        var firstTier = true;
        foreach (var entries in byTier.Values)
        {
            // Most plentiful aspects first.
            entries.Sort((a, b) =>
            {
                var byAmount = b.Amount.CompareTo(a.Amount);
                return byAmount != 0 ? byAmount : string.CompareOrdinal(a.Essence.Id, b.Essence.Id);
            });

            if (!firstTier)
                RowsContainer.AddChild(new HSeparator { Margin = new Thickness(0, 4, 0, 4) });
            firstTier = false;

            foreach (var rowEntries in entries.Chunk(MaxPerRow))
            {
                var row = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    SeparationOverride = 4,
                };

                foreach (var (essence, amount) in rowEntries)
                {
                    var control = new CEEssenceAmountControl { SetSize = new Vector2(IconSize, IconSize) };
                    control.SetEssence(essence, amount);
                    control.OnPressed += () => OnEssenceClicked(essence);
                    _essenceControls[essence] = control;
                    row.AddChild(control);
                }

                RowsContainer.AddChild(row);
            }
        }

        UpdateMergeUi();
    }

    /// <summary>
    /// Switches whether the merge window is the active placement target - see
    /// <see cref="OnEssenceSelectedForPlacement"/>. Toggled externally whenever a hex grid tile
    /// gets selected instead (or "Combine Aspects" is pressed to reclaim the target).
    /// </summary>
    public void SetMergeSelected(bool selected)
    {
        _mergeSelected = selected;
        MergePanel.Visible = selected;
        CombineButton.Visible = !selected;

        if (selected)
            UpdateMergeUi();
    }

    /// <summary>
    /// Dims every held aspect that <paramref name="isLegal"/> rejects - used while a hex grid tile
    /// is the placement target, to preview which aspects could actually go there. Null clears all
    /// dimming (full opacity for everyone).
    /// </summary>
    public void SetPlacementLegality(Func<ProtoId<CEMagicEssenceTypePrototype>, bool>? isLegal)
    {
        foreach (var (essence, control) in _essenceControls)
            control.Modulate = isLegal is null || isLegal(essence) ? Color.White : DimColor;
    }

    /// <summary>
    /// If the merge window is the current target: clicking an already-selected aspect deselects
    /// it, clicking an unselected one fills whichever merge slot is free (ignored if both are
    /// taken). Otherwise the click is forwarded as a placement request for whatever else is
    /// currently targeted (e.g. a hex grid tile).
    /// </summary>
    private void OnEssenceClicked(ProtoId<CEMagicEssenceTypePrototype> essence)
    {
        if (!_mergeSelected)
        {
            OnEssenceSelectedForPlacement?.Invoke(essence);
            return;
        }

        if (_slot1 == essence)
            _slot1 = null;
        else if (_slot2 == essence)
            _slot2 = null;
        else if (_slot1 is null)
            _slot1 = essence;
        else if (_slot2 is null)
            _slot2 = essence;
        else
            return;

        UpdateMergeUi();
    }

    private void UpdateMergeUi()
    {
        Slot1Icon.Texture = GetIcon(_slot1);
        Slot2Icon.Texture = GetIcon(_slot2);

        if (_slot1 is { } first && _slot2 is { } second && _essence.TryGetMergeResult(first, second, out var result))
        {
            // The preview icon and the "><" text would otherwise overlap in the same spot.
            MergeButton.Text = string.Empty;
            MergePreviewIcon.Visible = true;
            MergePreviewIcon.Texture = GetIcon(result);

            var cost = new Dictionary<ProtoId<CEMagicEssenceTypePrototype>, int> { [first] = 1, [second] = 1 };
            MergeButton.Disabled = !CESharedScienceSystem.CanAfford(_points, cost);
        }
        else
        {
            MergeButton.Text = "><";
            MergePreviewIcon.Visible = false;
            MergeButton.Disabled = true;
        }

        if (_mergeSelected)
            UpdateMergeDimming();
    }

    // Dims every held aspect that couldn't merge with the lone filled slot - no dimming once both
    // slots are filled (the pair is already decided) or neither is.
    private void UpdateMergeDimming()
    {
        var lone = _slot1 is null ? _slot2 : (_slot2 is null ? _slot1 : null);
        if (lone is { } selected)
            SetPlacementLegality(essence => essence == selected || _essence.TryGetMergeResult(selected, essence, out _));
        else
            SetPlacementLegality(null);
    }

    private Texture? GetIcon(ProtoId<CEMagicEssenceTypePrototype>? essence)
    {
        return essence is { } id && _prototype.TryIndex(id, out CEMagicEssenceTypePrototype? proto)
            ? proto.Icon.Frame0()
            : null;
    }
}
