using Content.Shared._CE.Science.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Science;

[GenerateTypedNameReferences]
public sealed partial class CEScienceAreaCardControl : PanelContainer
{
    private static readonly StyleBoxFlat SelectedBox = new()
    {
        BorderThickness = new Thickness(2),
        BorderColor = Color.FromHex("#53b58b"),
    };

    private static readonly Color StudiedColor = Color.FromHex("#53b58b");
    private static readonly Color ExhaustedModulate = new(1f, 1f, 1f, 0.4f);

    [Dependency] private IEntityManager _entity = default!;

    public readonly ProtoId<CEScienceAreaPrototype> AreaId;

    public event Action<ProtoId<CEScienceAreaPrototype>>? OnSelect;

    private readonly StyleBox? _normalBox;
    private bool _exhausted;

    public CEScienceAreaCardControl(CEScienceAreaPrototype area)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _normalBox = PanelOverride;

        AreaId = area.ID;

        HeaderPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = area.Color };
        NameLabel.Text = Loc.GetString(area.Name);
        DescLabel.Text = area.Desc is { } desc ? Loc.GetString(desc) : string.Empty;
        IconTexture.Texture = _entity.System<SpriteSystem>().Frame0(area.Icon);

        OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick || _exhausted)
                return;

            args.Handle();
            OnSelect?.Invoke(AreaId);
        };
    }

    public void SetSelected(bool selected)
    {
        PanelOverride = selected ? SelectedBox : _normalBox;
    }

    /// <summary>
    /// Updates the study-progress readout from a viewer's known/unlockable discovery counts in this
    /// area. Unlockable == 0 means nothing is left to research here - the card dims and stops
    /// accepting clicks, and shows the studied label instead of a percentage.
    /// </summary>
    public void SetProgress(int known, int unlockable)
    {
        _exhausted = unlockable == 0;
        Modulate = _exhausted ? ExhaustedModulate : Color.White;

        if (_exhausted)
        {
            ProgressLabel.Text = Loc.GetString("ce-research-table-area-studied");
            ProgressLabel.FontColorOverride = StudiedColor;
        }
        else
        {
            var total = known + unlockable;
            var percent = total == 0 ? 100 : known * 100 / total;
            ProgressLabel.Text = Loc.GetString("ce-research-table-area-progress", ("percent", percent));
            ProgressLabel.FontColorOverride = null;
        }
    }
}
