using System.Linq;
using System.Numerics;
using Content.Client._CE.MagicEssence.Controls;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._CE.MagicEssence.Prototypes;
using Content.Shared._CE.MagicEssence.Systems;
using Content.Shared._CE.Science;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Science;

/// <summary>
/// Every essence type of research points a character currently holds, one icon+amount per essence
/// (see <see cref="CEEssenceAmountControl"/>), wrapped at <see cref="MaxPerRow"/> per row and
/// grouped into a scrollable column with a divider between each thaumaturgical tier. Also hosts the
/// "merge 2 aspects into a higher-tier one" picker at the bottom - see <see cref="OnEssenceClicked"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEScienceKnowledgeControl : BoxContainer
{
    private const int IconSize = 28;
    private const int MaxPerRow = 6;

    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IEntityManager _entity = default!;

    private CEMagicEssenceSystem _essence = default!;

    private IReadOnlyDictionary<ProtoId<CEMagicEssenceTypePrototype>, int> _points =
        new Dictionary<ProtoId<CEMagicEssenceTypePrototype>, int>();

    private ProtoId<CEMagicEssenceTypePrototype>? _slot1;
    private ProtoId<CEMagicEssenceTypePrototype>? _slot2;

    /// <summary>
    /// Raised when the merge button is pressed with two compatible, affordable aspects selected.
    /// </summary>
    public event Action<ProtoId<CEMagicEssenceTypePrototype>, ProtoId<CEMagicEssenceTypePrototype>>? OnMerge;

    public CEScienceKnowledgeControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _essence = _entity.System<CEMagicEssenceSystem>();

        MergeButton.OnPressed += _ =>
        {
            if (_slot1 is { } first && _slot2 is { } second)
                OnMerge?.Invoke(first, second);
        };
    }

    public void UpdateKnowledge(IReadOnlyDictionary<ProtoId<CEMagicEssenceTypePrototype>, int> points)
    {
        _points = points;

        RowsContainer.RemoveAllChildren();

        var byTier = new SortedDictionary<int, List<(ProtoId<CEMagicEssenceTypePrototype> Essence, int Amount)>>();
        foreach (var (essence, amount) in points)
        {
            var tier = _prototype.TryIndex(essence, out CEMagicEssenceTypePrototype? proto) ? proto.Tier : 0;
            if (!byTier.TryGetValue(tier, out var entries))
            {
                entries = new List<(ProtoId<CEMagicEssenceTypePrototype>, int)>();
                byTier[tier] = entries;
            }

            entries.Add((essence, amount));
        }

        var firstTier = true;
        foreach (var entries in byTier.Values)
        {
            // Most plentiful aspects first.
            entries.Sort((a, b) =>
            {
                var byAmount = b.Amount.CompareTo(a.Amount);
                return byAmount != 0 ? byAmount : string.CompareOrdinal(a.Essence.Id, b.Essence.Id);
            });

            if (!firstTier)
                RowsContainer.AddChild(new HSeparator { Margin = new Thickness(0, 4, 0, 4) });
            firstTier = false;

            foreach (var rowEntries in entries.Chunk(MaxPerRow))
            {
                var row = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    SeparationOverride = 4,
                };

                foreach (var (essence, amount) in rowEntries)
                {
                    var control = new CEEssenceAmountControl { SetSize = new Vector2(IconSize, IconSize) };
                    control.SetEssence(essence, amount);
                    control.OnPressed += () => OnEssenceClicked(essence);
                    row.AddChild(control);
                }

                RowsContainer.AddChild(row);
            }
        }

        UpdateMergeUi();
    }

    /// <summary>
    /// Clicking an already-selected aspect deselects it. Clicking an unselected aspect fills
    /// whichever slot is free; if both are already taken, the click is ignored - a slot has to be
    /// freed first by clicking its current aspect.
    /// </summary>
    private void OnEssenceClicked(ProtoId<CEMagicEssenceTypePrototype> essence)
    {
        if (_slot1 == essence)
            _slot1 = null;
        else if (_slot2 == essence)
            _slot2 = null;
        else if (_slot1 is null)
            _slot1 = essence;
        else if (_slot2 is null)
            _slot2 = essence;
        else
            return;

        UpdateMergeUi();
    }

    private void UpdateMergeUi()
    {
        Slot1Icon.Texture = GetIcon(_slot1);
        Slot2Icon.Texture = GetIcon(_slot2);

        if (_slot1 is { } first && _slot2 is { } second && _essence.TryGetMergeResult(first, second, out var result))
        {
            // The preview icon and the "><" text would otherwise overlap in the same spot.
            MergeButton.Text = string.Empty;
            MergePreviewIcon.Visible = true;
            MergePreviewIcon.Texture = GetIcon(result);

            var cost = new Dictionary<ProtoId<CEMagicEssenceTypePrototype>, int> { [first] = 1, [second] = 1 };
            MergeButton.Disabled = !CESharedScienceSystem.CanAfford(_points, cost);
        }
        else
        {
            MergeButton.Text = "><";
            MergePreviewIcon.Visible = false;
            MergeButton.Disabled = true;
        }
    }

    private Texture? GetIcon(ProtoId<CEMagicEssenceTypePrototype>? essence)
    {
        return essence is { } id && _prototype.TryIndex(id, out CEMagicEssenceTypePrototype? proto)
            ? proto.Icon.Frame0()
            : null;
    }
}
