using Content.Client.Message;
using Content.Shared._CE.Roadmap;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.Roadmap;

[GenerateTypedNameReferences]
public sealed partial class CERoadmapItem : Control
{
    private CERoadmapItemCategory? _itemCategory;

    public CERoadmapItemCategory? ItemScope
    {
        get => _itemCategory;
        set
        {
            _itemCategory = value;
            var panel = (StyleBoxFlat) StateColor.PanelOverride!;
            panel.BackgroundColor = _itemCategory?.Color ?? Color.White;

            StateText.Text = Loc.GetString(_itemCategory?.Title ?? "?");
            StateText.ModulateSelfOverride = panel.BackgroundColor;
        }
    }

    public string? HeaderText
    {
        get => HeaderButton.Text;
        set => HeaderButton.Text = value;
    }

    public string? Text
    {
        get => Contents.GetMessage();
        set => Contents.SetMarkup($"[font size=11]{value ?? string.Empty}[/font]");
    }

    public CERoadmapItem()
    {
        RobustXamlLoader.Load(this);
        HeaderButton.OnPressed += _ => ContentsContainer.Visible = !ContentsContainer.Visible;
    }
}
