using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.Roadmap;

[GenerateTypedNameReferences]
public sealed partial class CERoadmapVersionHeader : BoxContainer
{
    public string? Text
    {
        get => Version.Text;
        set => Version.Text = value;
    }

    public CERoadmapVersionHeader()
    {
        RobustXamlLoader.Load(this);
    }
}
