using Content.Client.Pinpointer.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._CE.Power.PowerMonitoring;
using Content.Shared.Power;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._CE.Power.PowerMonitoring;

/// <summary>
/// CE fork of <c>Content.Client.Power.PowerMonitoringWindow</c>, driving the multi z-level
/// <see cref="CEPowerMonitoringConsoleNavMapControl"/> and surfacing the extra energy-leak alert.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEPowerMonitoringWindow : FancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IGameTiming _gameTiming = default!;
    private readonly SpriteSystem _spriteSystem;

    private const float BlinkFrequency = 1f;

    private NetEntity? _focusEntity;

    public event Action<NetEntity?, PowerMonitoringConsoleGroup>? SendPowerMonitoringConsoleMessageAction;

    private readonly Dictionary<PowerMonitoringConsoleGroup, (SpriteSpecifier.Texture, Color)> _groupBlips = new()
    {
        {
            PowerMonitoringConsoleGroup.Generator,
            (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")), Color.Purple)
        },
        {
            PowerMonitoringConsoleGroup.SMES,
            (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_hexagon.png")),
                Color.OrangeRed)
        },
        {
            PowerMonitoringConsoleGroup.APC,
            (new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_triangle.png")),
                Color.LimeGreen)
        },
    };

    private static readonly SpriteSpecifier.Texture LeakBlip =
        new(new ResPath("/Textures/Interface/NavMap/beveled_triangle.png"));

    public EntityUid Entity;

    public CEPowerMonitoringWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entManager.System<SpriteSystem>();

        NavMap.TrackedEntitySelectedAction += SetTrackedEntityFromNavMap;
        NavMap.ForceNavMapUpdate();

        MasterTabContainer.SetTabTitle(0, Loc.GetString("ce-power-monitoring-window-tab-generators"));
        MasterTabContainer.SetTabTitle(1, Loc.GetString("ce-power-monitoring-window-tab-accumulators"));
        MasterTabContainer.SetTabTitle(2, Loc.GetString("ce-power-monitoring-window-tab-distributors"));

        MasterTabContainer.OnTabChanged += OnTabChanged;

        // Big brass pipe = HighVoltage bucket, medium brass pipe = Apc bucket.
        ShowHVCable.OnToggled += _ => OnShowCableToggled(CEPowerMonitoringConsoleLineGroup.HighVoltage);
        ShowLVCable.OnToggled += _ => OnShowCableToggled(CEPowerMonitoringConsoleLineGroup.Apc);
    }

    public void SetEntity(EntityUid uid)
    {
        Entity = uid;
        NavMap.Owner = uid;

        var islandName = Loc.GetString("ce-power-monitoring-window-unknown-location");

        if (_entManager.TryGetComponent<TransformComponent>(uid, out var xform))
        {
            // The stacked control resolves the whole z-network from any of its maps.
            NavMap.MapUid = xform.MapUid;

            if (_entManager.TryGetComponent<MetaDataComponent>(xform.GridUid, out var stationMetaData))
                islandName = stationMetaData.EntityName;

            var msg = new FormattedMessage();
            msg.AddMarkupOrThrow(Loc.GetString("ce-power-monitoring-window-island-name", ("islandName", islandName)));
            StationName.SetMessage(msg);
        }
        else
        {
            StationName.SetMessage(islandName);
            NavMap.Visible = false;
        }
    }

    private void OnTabChanged(int tab)
    {
        SendPowerMonitoringConsoleMessageAction?.Invoke(_focusEntity, GetCurrentPowerMonitoringConsoleGroup());
    }

    private void OnShowCableToggled(CEPowerMonitoringConsoleLineGroup lineGroup)
    {
        if (!NavMap.HiddenLineGroups.Remove(lineGroup))
            NavMap.HiddenLineGroups.Add(lineGroup);
    }

    public void ShowEntities(
        double totalSources,
        double totalBatteryUsage,
        double totalLoads,
        PowerMonitoringConsoleEntry[] allEntries,
        PowerMonitoringConsoleEntry[] focusSources,
        PowerMonitoringConsoleEntry[] focusLoads)
    {
        if (!_entManager.TryGetComponent<CEPowerMonitoringConsoleComponent>(Entity, out var console))
            return;

        TotalSources.Text = Loc.GetString("ce-power-monitoring-window-value",
            ("value", Math.Round(totalSources).ToString("N0")));
        TotalBatteryUsage.Text = Loc.GetString("ce-power-monitoring-window-value",
            ("value", Math.Round(totalBatteryUsage).ToString("N0")));
        TotalLoads.Text = Loc.GetString("ce-power-monitoring-window-value",
            ("value", Math.Round(totalLoads).ToString("N0")));

        TotalBatteryUsage.FontColorOverride =
            (totalSources * 0.1111f) < totalBatteryUsage ? new Color(180, 0, 0) : Color.White;

        TotalLoads.FontColorOverride = (totalSources + totalBatteryUsage) < totalLoads &&
                                       !MathHelper.CloseToPercent(totalSources + totalBatteryUsage, totalLoads, 0.1f)
            ? new Color(180, 0, 0)
            : Color.White;

        UpdateWarningLabel(console.Flags);

        NavMap.TrackedCoordinates.Clear();
        NavMap.TrackedEntities.Clear();

        var entitiesOfInterest = new List<NetEntity>();

        if (_focusEntity != null)
        {
            entitiesOfInterest.Add(_focusEntity.Value);

            foreach (var entry in focusSources)
            {
                entitiesOfInterest.Add(entry.NetEntity);
            }

            foreach (var entry in focusLoads)
            {
                entitiesOfInterest.Add(entry.NetEntity);
            }
        }

        foreach (var (netEntity, metaData) in console.PowerMonitoringDeviceMetaData)
        {
            if (NavMap.Visible)
                AddTrackedEntityToNavMap(netEntity, metaData, entitiesOfInterest);
        }

        // Energy leaks - the map-side of the alert.
        if (NavMap.Visible)
        {
            foreach (var (netEntity, netCoords) in console.EnergyLeaks)
            {
                var coords = _entManager.GetCoordinates(netCoords);
                NavMap.TrackedEntities[netEntity] = new NavMapBlip(coords,
                    _spriteSystem.Frame0(LeakBlip),
                    new Color(255, 48, 48),
                    true,
                    false);
            }
        }

        // Show monitor location
        var mon = _entManager.GetNetEntity(Entity);

        if (mon.IsValid() && _entManager.TryGetComponent<TransformComponent>(Entity, out var monXform))
        {
            var texture =
                _spriteSystem.Frame0(
                    new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));
            NavMap.TrackedEntities[mon] = new NavMapBlip(monXform.Coordinates, texture, Color.Cyan, true, false);
        }

        if (allEntries.Length > 0 && allEntries[0].Group != GetCurrentPowerMonitoringConsoleGroup())
            return;

        allEntries = GetUpdatedPowerMonitoringConsoleEntries(allEntries, console);
        focusSources = GetUpdatedPowerMonitoringConsoleEntries(focusSources, console);
        focusLoads = GetUpdatedPowerMonitoringConsoleEntries(focusLoads, console);

        var currentContainer = GetCurrentPowerMonitoringConsoleGroup() switch
        {
            PowerMonitoringConsoleGroup.SMES => SMESList,
            PowerMonitoringConsoleGroup.APC => ApcList,
            _ => SourcesList
        };

        while (currentContainer.ChildCount > allEntries.Length)
        {
            currentContainer.RemoveChild(currentContainer.GetChild(currentContainer.ChildCount - 1));
        }

        for (var index = 0; index < allEntries.Length; index++)
        {
            var entry = allEntries[index];

            if (entry.NetEntity == _focusEntity)
                UpdateWindowConsoleEntry(currentContainer, index, entry, focusSources, focusLoads);
            else
                UpdateWindowConsoleEntry(currentContainer, index, entry);
        }

        if (_autoScrollAwaitsUpdate)
        {
            _autoScrollActive = true;
            _autoScrollAwaitsUpdate = false;
        }
    }

    private void AddTrackedEntityToNavMap(NetEntity netEntity,
        PowerMonitoringDeviceMetaData metaData,
        List<NetEntity> entitiesOfInterest)
    {
        if (!_groupBlips.TryGetValue(metaData.Group, out var data))
            return;

        var usedEntity = metaData.CollectionMaster ?? netEntity;
        var coords = _entManager.GetCoordinates(metaData.Coordinates);
        var color = data.Item2;
        var blink = usedEntity == _focusEntity;
        var modulator = Color.White;

        if (_focusEntity != null && usedEntity != _focusEntity && !entitiesOfInterest.Contains(usedEntity))
            modulator = Color.DimGray;

        var blip = new NavMapBlip(coords, _spriteSystem.Frame0(data.Item1), color * modulator, blink);
        NavMap.TrackedEntities[netEntity] = blip;
    }

    private void SetTrackedEntityFromNavMap(NetEntity? netEntity)
    {
        if (netEntity == null)
            return;

        if (!_entManager.TryGetComponent<CEPowerMonitoringConsoleComponent>(Entity, out var console))
            return;

        if (!console.PowerMonitoringDeviceMetaData.TryGetValue(netEntity.Value, out var metaData))
            return;

        if (metaData.CollectionMaster != null)
            netEntity = metaData.CollectionMaster;

        _focusEntity = netEntity;

        SwitchTabsBasedOnPowerMonitoringConsoleGroup(metaData.Group);
        ActivateAutoScrollToFocus();

        SendPowerMonitoringConsoleMessageAction?.Invoke(_focusEntity, metaData.Group);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        AutoScrollToFocus();

        var lit = _gameTiming.RealTime.TotalSeconds % BlinkFrequency > BlinkFrequency / 2f;
        SystemWarningPanel.Modulate = lit ? Color.White : new Color(178, 178, 178);
    }

    private PowerMonitoringConsoleEntry[] GetUpdatedPowerMonitoringConsoleEntries(PowerMonitoringConsoleEntry[] entries,
        CEPowerMonitoringConsoleComponent console)
    {
        for (var i = 0; i < entries.Length; i++)
        {
            if (!console.PowerMonitoringDeviceMetaData.TryGetValue(entries[i].NetEntity, out var metaData))
                continue;

            entries[i].MetaData = metaData;
        }

        Array.Sort(entries, AlphabeticalSort);
        return entries;
    }

    private int AlphabeticalSort(PowerMonitoringConsoleEntry x, PowerMonitoringConsoleEntry y)
    {
        if (x.MetaData?.EntityName == null)
            return -1;

        if (y.MetaData?.EntityName == null)
            return 1;

        return string.CompareOrdinal(x.MetaData.Value.EntityName, y.MetaData.Value.EntityName);
    }
}
