- type: job
  id: CEGuard
  setPreference: true
  name: ce-job-name-guard
  description: ce-job-desc-guard
  playTimeTracker: CEJobGuard
  startingGear: CEGuardGear
  icon: CEJobIconGuard
  supervisors: ce-job-supervisors-guard-commander
  special:
    - !type:AddComponentSpecial
      components:
      - type: CESalaryCounter
        salary: 50

- type: startingGear
  id: CEGuardGear
  equipment:
    belt: CEKeyRingGuard
    pocket1: CEWalletFilledGuard
  storage:
    back:
    - CEGuidebookImperialLaws
    - CEGunJustice


- type: entity
  id: CEWalletFilledGuard
  parent: CEWallet
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents: #100cp total
    - id: CECoinSilver5
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinCopper10

- type: entity
  id: CEChestFilledGuard
  parent: CEWoodenChest
  suffix: Filled, Guard
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: CEGunJustice
        - id: CERope
        - id: CERope
        - id: CERope

- type: entity
  id: CEBedsideTableFilledGuard
  parent: CEBedsideTableWooden
  suffix: Filled, Guard
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:GroupSelector
        rolls: !type:RangeNumberSelector
          range: 2, 3
        children:
        - id: CEClothingCloakRaincoatGuard
        - id: CEClothingHeadHelmetGuard
        - id: CEClothingHeadHelmetGuardCorinthian
        - id: CEClothingHeadCapGuard
        - id: CEClothingHeadFedoraGuard
        - id: CEClothingShirtGuard
        - id: CEClothingShirtSyurkoGuard
        - id: CEClothingPantsGuard

- type: entity
  id: CEKeyRingGuard
  parent: CEBaseKeyRing
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: CEKeyGuardHall
    - id: CEKeyGuardStaff
