- type: entity
  abstract: true
  id: CEClothingBaseContainer
  categories: [ ForkFiltered ]
  components:
  - type: ContainerContainer
    containers:
      storagebase: !type:Container
        ents: []
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
