using Content.Client.CharacterInfo;
using Content.Client.UserInterface.Controls;
using Content.Shared._CE.Ambitions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.Ambitions;

[GenerateTypedNameReferences]
public sealed partial class CEAmbitionsMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    private CharacterInfoSystem? _characterInfo;

    public event Action? OnNewAmbitionRequest;
    public event Action? OnLockAmbitionRequest;
    public event Action<int>? OnDeleteAmbitionRequest;

    public CEAmbitionsMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AddAmbitionButton.OnPressed += AddAmbitionButton_OnPressed;
        LockAmbitionButton.OnPressed += LockAmbitionButton_OnPressed;
    }

    private void LockAmbitionButton_OnPressed(BaseButton.ButtonEventArgs obj)
    {
        OnLockAmbitionRequest?.Invoke();
        Close();
    }

    private void AddAmbitionButton_OnPressed(BaseButton.ButtonEventArgs obj)
    {
        OnNewAmbitionRequest?.Invoke();
    }

    public void Update(EntityUid uid, CEAmbitionsBuiState state)
    {
        AmbitionsContainer.Children.Clear();

        AddAmbitionButton.Text = $"{Loc.GetString("ce-ambitions-buttons-add")} ({state.Ambitions.Count}/{state.MaxAmbitions}) [{state.Rerolls}]";
        AddAmbitionButton.Disabled = state.Ambitions.Count >= state.MaxAmbitions || state.Rerolls <= 0;

        var index = 0;
        foreach (var (name, desc) in state.Ambitions)
        {
            var control = new CEAmbitionControl(uid, index, name, desc, state.Rerolls <= 0);

            control.OnDeleteAmbitionRequest += () => OnDelete(control.Index);

            AmbitionsContainer.AddChild(control);
            index++;
        }

        _characterInfo ??= _entMan.System<CharacterInfoSystem>();
        _characterInfo.RequestCharacterInfo();
    }

    private void OnDelete(int index)
    {
        OnDeleteAmbitionRequest?.Invoke(index);
    }
}
