using Content.Client.UserInterface.Controls;
using Content.Shared._CE.Ambitions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.Ambitions;

[GenerateTypedNameReferences]
public sealed partial class CEAmbitionsMenu : FancyWindow
{
    public event Action? OnNewAmbitionRequest;
    public event Action<string>? OnRerollAmbitionRequest;

    public CEAmbitionsMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AddAmbitionButton.OnPressed += AddAmbitionButton_OnPressed;
    }

    private void AddAmbitionButton_OnPressed(BaseButton.ButtonEventArgs obj)
    {
        OnNewAmbitionRequest?.Invoke();
    }

    public void Update(EntityUid uid, CEAmbitionsBuiState state)
    {
        state.Ambitions.Sort();
        AmbitionsContainer.Children.Clear();

        AddAmbitionButton.Text = $"{Loc.GetString("ce-ambitions-buttons-add")} ({state.Ambitions.Count}/{state.MaxAmbitions})";
        AddAmbitionButton.Disabled = state.Ambitions.Count >= state.MaxAmbitions;

        foreach (var (name, desc) in state.Ambitions)
        {
            var control = new CEAmbitionControl(uid, name, desc, state.Rerolls > 0);

            control.OnRerollAmbitionRequest += () => OnReroll(name);

            AmbitionsContainer.AddChild(control);
        }
    }

    private void OnReroll(string title)
    {
        OnRerollAmbitionRequest?.Invoke(title);
    }
}
