using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.Ambitions;

[GenerateTypedNameReferences]
public sealed partial class CEAmbitionControl : Control
{
    public int Index;
    public event Action? OnDeleteAmbitionRequest;

    public CEAmbitionControl(EntityUid owner, int index, string title, string desc, bool disabled)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Index = index;

        TitleLabel.SetMarkup(title);
        DescLabel.SetMessage(desc);

        DeleteButton.OnPressed += _ => OnDeleteAmbitionRequest?.Invoke();
    }
}
