using Content.Client.Chat.Managers;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._CE.Ambitions;

[GenerateTypedNameReferences]
public sealed partial class CEAmbitionControl : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IChatManager _chatManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly EntityManager _entityManager = default!;

    public CEAmbitionControl(EntityUid owner, string title, string desc)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TitleLabel.SetMarkup(title);
        DescLabel.SetMessage(desc);
    }
}
