- type: job
  id: CEBrigadier
  setPreference: true
  name: ce-job-name-brigadier
  description: ce-job-desc-brigadier
  playTimeTracker: CEJobBrigadier
  startingGear: CEBrigadierGear
  icon: CEJobIconBrigadier
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: ce-job-supervisors-empire
  requirements:
    - !type:DepartmentTimeRequirement
      department: CEEngineering
      time: 4h

- type: startingGear
  id: CEBrigadierGear
  equipment:
    belt: CEKeyRingBrigadier
    pocket1: CEWalletFilledBrigadier

- type: entity
  id: CEWalletFilledBrigadier
  parent: CEWallet
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents: #200cp total
    - id: CECoinGold1
    - id: CECoinSilver5
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinCopper10

- type: entity
  id: CEChestFilledBrigadier
  parent: CEGoldChest
  suffix: Filled, Brigadier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: CEClothingEyesMiningGlasses
        - id: CECrowbar
        - id: CEWrench
        - id: CEScrewdriver
        - id: CEBigBrassPipe30
        - id: CEMediumBrassPipe30
        - id: CEWeaponPickaxeIron
        - id: CEBrassBar10
        - id: CEIronBar10
        - id: CERubberStampApproved
        - id: CERubberStampDenied
        - id: CERubberStampEngineering
        - id: CEThirdArm
        - id: CEThirdArmModuleManipulation

- type: entity
  id: CEBedsideTableFilledBrigadier
  parent: CEBedsideTableWooden
  suffix: Filled, Brigadier
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:GroupSelector
        rolls: !type:RangeNumberSelector
          range: 2, 3
        children:
        - id: CEClothingCloakBrigadier
        - id: CEClothingHeadFedoraBrown
        - id: CEClothingHeadFedoraBlack
        - id: CEClothingHeadBowlerLeather
        - id: CEClothingShirtEngineeringShirt
        - id: CEClothingShirtEngineeringJacket
        - id: CEClothingShirtEngineeringDress
        - id: CEClothingPantsEngineering

- type: entity
  id: CEKeyRingBrigadier
  parent: CEBaseKeyRing
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: CEKeyEngineeringHall
    - id: CEKeyEngineeringStaff
    - id: CEKeyEngineeringGenerator
    - id: CEKeyEngineeringTunnels
    - id: CEKeyEngineeringBrigadier
    - id: CEKeyEngineeringStorage
