- type: job
  id: CETechnician
  setPreference: true
  name: ce-job-name-technician
  description: ce-job-desc-technician
  playTimeTracker: CEJobTechnician
  startingGear: CETechnicianGear
  icon: CEJobIconTechnician
  supervisors: ce-job-supervisors-brigadier

- type: startingGear
  id: CETechnicianGear
  equipment:
    belt: CEKeyRingTechnician
    pocket1: CEWalletFilledTechnician


- type: entity
  id: CEWalletFilledTechnician
  parent: CEWallet
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents: #100cp total
    - id: CECoinSilver5
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinCopper10

- type: entity
  id: CEChestFilledTechnician
  parent: CEWoodenChest
  suffix: Filled, Technician
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: CEClothingEyesMiningGlasses
        - id: CECrowbar
        - id: CEWrench
        - id: CEScrewdriver
        - id: CEBigBrassPipe30
        - id: CEMediumBrassPipe30
        - id: CEWeaponPickaxeIron

- type: entity
  id: CEBedsideTableFilledTechnician
  parent: CEBedsideTableWooden
  suffix: Filled, Technician
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:GroupSelector
        rolls: !type:RangeNumberSelector
          range: 2, 3
        children:
        - id: CEClothingHeadFedoraBrown
        - id: CEClothingHeadFedoraBlack
        - id: CEClothingHeadBowlerLeather
        - id: CEClothingShirtEngineeringShirt
        - id: CEClothingShirtEngineeringJacket
        - id: CEClothingShirtEngineeringDress
        - id: CEClothingPantsEngineering

- type: entity
  id: CEKeyRingTechnician
  parent: CEBaseKeyRing
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: CEKeyEngineeringHall
    - id: CEKeyEngineeringStaff
    - id: CEKeyEngineeringGenerator
    - id: CEKeyEngineeringTunnels
    - id: CEKeyEngineeringStorage
