- type: job
  id: CEAcademyDirector
  setPreference: true
  name: ce-job-name-academy-director
  description: ce-job-desc-academy-director
  playTimeTracker: CEJobAcademyDirector
  startingGear: CEAcademyDirectorGear
  icon: CEJobIconAcademyDirector
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: ce-job-supervisors-empire
  weight: 3
  special:
    - !type:CEResearchDataSpecial
      radius: 6

- type: startingGear
  id: CEAcademyDirectorGear
  equipment:
    pocket1: CEWalletFilledAcademyDirector

- type: entity
  id: CEWalletFilledAcademyDirector
  parent: CEWallet
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents: #200cp total
    - id: CECoinGold1
    - id: CECoinSilver5
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinCopper10
