- type: job
  id: CEAcademyProfessor
  setPreference: true
  name: ce-job-name-academy-professor
  description: ce-job-desc-academy-professor
  playTimeTracker: CEJobAcademyProfessor
  startingGear: CEAcademyProfessorGear
  icon: CEJobIconAcademyProfessor
  supervisors: ce-job-supervisors-academy-rector
  special:
    - !type:CEResearchPointsSpecial
      points:
        Earth: 20
        Fire: 20
        Water: 20
        Air: 20
        Order: 20
        Chaos: 20

- type: startingGear
  id: CEAcademyProfessorGear
  equipment:
    belt: CEKeyRingAcademyProfessor
    pocket1: CEWalletFilledAcademyProfessor

- type: entity
  id: CEWalletFilledAcademyProfessor
  parent: CEWallet
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents: #100cp total
    - id: CECoinSilver5
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinCopper10

- type: entity
  id: CEKeyRingAcademyProfessor
  parent: CEBaseKeyRing
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: CEKeyAcademyHall
    - id: CEKeyAcademyTechnical
    - id: CEKeyAcademyLab
