- type: job
  id: CEAcademyRector
  setPreference: true
  name: ce-job-name-academy-rector
  description: ce-job-desc-academy-rector
  playTimeTracker: CEJobAcademyRector
  startingGear: CEAcademyRectorGear
  icon: CEJobIconAcademyRector
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: ce-job-supervisors-empire
  weight: 3
  special:
    - !type:CEResearchPointsSpecial
      points:
        Earth: 30
        Fire: 30
        Water: 30
        Air: 30
        Order: 30
        Chaos: 30

- type: startingGear
  id: CEAcademyRectorGear
  equipment:
    belt: CEKeyRingAcademyRector
    pocket1: CEWalletFilledAcademyRector

- type: entity
  id: CEWalletFilledAcademyRector
  parent: CEWallet
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents: #200cp total
    - id: CECoinGold1
    - id: CECoinSilver5
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinCopper10

- type: entity
  id: CEKeyRingAcademyRector
  parent: CEBaseKeyRing
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: CEKeyAcademyHall
    - id: CEKeyAcademyTechnical
    - id: CEKeyAcademyLab
    - id: CEKeyAcademyRectorRoom
