- type: entity
  abstract: true
  parent: Clothing
  id: CEClothingShoesBase
  categories: [ ForkFiltered ]
  components:
  - type: Clothing
    equipDelay: 1
    unequipDelay: 1
    slots:
    - FEET
  - type: Sprite
    state: icon
  - type: Item
    size: Normal
  - type: ProtectedFromStepTriggers
