using Content.Client._CE.Objectives;
using Content.Client.Stylesheets;
using Content.Shared._CE.Character;
using Content.Shared._CE.Objectives.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics.RSI;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._CE.Objectives.Ui;

/// <summary>
/// A single CE objective's card in the character menu: icon, title, description, a full-width
/// progress bar (percent text drawn on top, matching <c>CEMurkSphereFixerMonitorWindow</c>'s
/// charge bar), and - if the objective has a <see cref="CEObjectiveDescriptorComponent"/> - a
/// colored badge naming its source.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEObjectiveControl : BoxContainer
{
    [Dependency] private EntityManager _ent = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    private readonly CEObjectiveSystem _objective;
    private readonly SpriteSystem _sprite;

    private EntityUid Objective { get; set; }

    public CEObjectiveControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _objective = _ent.System<CEObjectiveSystem>();
        _sprite = _ent.System<SpriteSystem>();

        _objective.OnObjectiveProgressChanged += OnProgressChanged;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            _objective.OnObjectiveProgressChanged -= OnProgressChanged;
    }

    private void OnProgressChanged(Entity<CEObjectiveComponent> obj)
    {
        if (obj.Owner != Objective)
            return;
        SetObjective(Objective); // update
    }

    public void SetObjective(EntityUid objective)
    {
        Objective = objective;

        var metaData = _ent.GetComponent<MetaDataComponent>(objective);
        TitleLabel.Text = metaData.EntityName;
        DescriptionLabel.Text = metaData.EntityDescription;

        Icon.Texture = _ent.TryGetComponent<SpriteComponent>(objective, out var sprite)
            ? sprite.Icon?.GetFrame(RsiDirection.South, 0)
            : null;

        var progress = _objective.GetProgress(objective);
        ProgressBar.Value = progress;
        ProgressLabel.Text = $"{(int) (progress * 100)}%";
        ProgressBar.ForegroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = progress >= 1f ? StyleNano.GoodGreenFore : StyleNano.ConcerningOrangeFore,
        };

        if (_ent.TryGetComponent<CEObjectiveDescriptorComponent>(objective, out var descriptor))
        {
            OwnerPanel.Visible = true;
            OwnerPanel.ModulateSelfOverride = descriptor.Color;

            var luminance = 0.2126f * descriptor.Color.R + 0.7152f * descriptor.Color.G + 0.0722f * descriptor.Color.B;
            OwnerLabel.Text = Loc.GetString(descriptor.Name);
            OwnerLabel.FontColorOverride = luminance > 0.5f ? Color.Black : Color.White;

            if (descriptor.Tooltip is { } tooltipId)
            {
                var tooltip = new Tooltip { MaxWidth = 400 };
                tooltip.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString(tooltipId)));
                TooltipSupplier = _ => tooltip;
            }
            else
            {
                TooltipSupplier = null;
            }
        }
        else
        {
            OwnerPanel.Visible = false;
            TooltipSupplier = null;
        }

        ResizeTitle();
    }

    /// <summary>
    /// Renders from pre-resolved display data instead of a live local objective entity - used for
    /// CEViewCharacterSystem's foreign-player objectives, whose actual entities are mind-owner-only
    /// and never networked to the viewing ghost (see CEObjectiveComponent's networking note).
    /// </summary>
    public void SetObjectiveInfo(CEObjectiveInfo info)
    {
        Objective = EntityUid.Invalid;

        TitleLabel.Text = info.Title;
        DescriptionLabel.Text = info.Description;

        Icon.Texture = info.PrototypeId is { } protoId && _prototypeManager.TryIndex<EntityPrototype>(protoId, out var proto)
            ? _sprite.Frame0(proto)
            : null;

        ProgressBar.Value = info.Progress;
        ProgressLabel.Text = $"{(int) (info.Progress * 100)}%";
        ProgressBar.ForegroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = info.Progress >= 1f ? StyleNano.GoodGreenFore : StyleNano.ConcerningOrangeFore,
        };

        if (info.DescriptorName is { } descriptorName)
        {
            OwnerPanel.Visible = true;
            var color = info.DescriptorColor ?? Color.White;
            OwnerPanel.ModulateSelfOverride = color;

            var luminance = 0.2126f * color.R + 0.7152f * color.G + 0.0722f * color.B;
            OwnerLabel.Text = descriptorName;
            OwnerLabel.FontColorOverride = luminance > 0.5f ? Color.Black : Color.White;

            if (info.DescriptorTooltip is { } tooltip)
            {
                var tooltipControl = new Tooltip { MaxWidth = 400 };
                tooltipControl.SetMessage(FormattedMessage.FromMarkupPermissive(tooltip));
                TooltipSupplier = _ => tooltipControl;
            }
            else
            {
                TooltipSupplier = null;
            }
        }
        else
        {
            OwnerPanel.Visible = false;
            TooltipSupplier = null;
        }

        ResizeTitle();
    }

    private void ResizeTitle()
    {
        TitleLabel.MaxWidth = Header.Width - OwnerPanel.Width - Icon.Width;
    }

    protected override void Resized()
    {
        base.Resized();

        ResizeTitle();
    }
}
