using Content.Client._CE.Objectives;
using Content.Client.Stylesheets;
using Content.Shared._CE.Objectives.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics.RSI;
using Robust.Shared.Utility;

namespace Content.Client._CE.Objectives.Ui;

/// <summary>
/// A single CE objective's card in the character menu: icon, title, description, a full-width
/// progress bar (percent text drawn on top, matching <c>CEMurkSphereFixerMonitorWindow</c>'s
/// charge bar), and - if the objective has a <see cref="CEObjectiveDescriptorComponent"/> - a
/// colored badge naming its source.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CEObjectiveControl : BoxContainer
{
    [Dependency] private EntityManager _ent = default!;
    private readonly CEObjectiveSystem _objective;

    private EntityUid Objective { get; set; }

    public CEObjectiveControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _objective = _ent.System<CEObjectiveSystem>();

        _objective.OnObjectiveProgressChanged += OnProgressChanged;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            _objective.OnObjectiveProgressChanged -= OnProgressChanged;
    }

    private void OnProgressChanged(Entity<CEObjectiveComponent> obj)
    {
        if (obj.Owner != Objective)
            return;
        SetObjective(Objective); // update
    }

    public void SetObjective(EntityUid objective)
    {
        Objective = objective;

        var metaData = _ent.GetComponent<MetaDataComponent>(objective);
        TitleLabel.Text = metaData.EntityName;
        DescriptionLabel.Text = metaData.EntityDescription;

        Icon.Texture = _ent.TryGetComponent<SpriteComponent>(objective, out var sprite)
            ? sprite.Icon?.GetFrame(RsiDirection.South, 0)
            : null;

        var progress = _objective.GetProgress(objective);
        ProgressBar.Value = progress;
        ProgressLabel.Text = $"{(int) (progress * 100)}%";
        ProgressBar.ForegroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = progress >= 1f ? StyleNano.GoodGreenFore : StyleNano.ConcerningOrangeFore,
        };

        if (_ent.TryGetComponent<CEObjectiveDescriptorComponent>(objective, out var descriptor))
        {
            OwnerPanel.Visible = true;
            OwnerPanel.ModulateSelfOverride = descriptor.Color;

            var luminance = 0.2126f * descriptor.Color.R + 0.7152f * descriptor.Color.G + 0.0722f * descriptor.Color.B;
            OwnerLabel.Text = Loc.GetString(descriptor.Name);
            OwnerLabel.FontColorOverride = luminance > 0.5f ? Color.Black : Color.White;

            if (descriptor.Tooltip is { } tooltipId)
            {
                var tooltip = new Tooltip { MaxWidth = 400 };
                tooltip.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString(tooltipId)));
                TooltipSupplier = _ => tooltip;
            }
            else
            {
                TooltipSupplier = null;
            }
        }
        else
        {
            OwnerPanel.Visible = false;
            TooltipSupplier = null;
        }

        ResizeTitle();
    }

    private void ResizeTitle()
    {
        TitleLabel.MaxWidth = Header.Width - OwnerPanel.Width - Icon.Width;
    }

    protected override void Resized()
    {
        base.Resized();

        ResizeTitle();
    }
}
