using System.Linq;
using Content.Client._CE.UserInterface;
using Content.Shared._CE.Trading;
using Content.Shared._CE.Trading.Components;
using Content.Shared._CE.Trading.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Trading.Selling;

[GenerateTypedNameReferences]
public sealed partial class CESellingPlatformWindow : DefaultWindow
{
    [Dependency] private readonly ILogManager _log = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntityManager _e = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly CEClientTradingPlatformSystem _tradingSystem;
    private readonly CEClientEconomySystem _economySystem;
    private Entity<CETradingReputationComponent>? _cachedUser;
    private Entity<CESellingPlatformComponent>? _cachedPlatform;

    private CETradingFactionPrototype? _selectedFaction;
    public event Action<(ProtoId<CETradingRequestPrototype>, ProtoId<CETradingFactionPrototype>)>? OnRequestSell;
    public event Action? OnSell;

    private ISawmill Sawmill { get; init; }

    public CESellingPlatformWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Sawmill = _log.GetSawmill("ce_selling");

        _tradingSystem = _e.System<CEClientTradingPlatformSystem>();
        _economySystem = _e.System<CEClientEconomySystem>();

        SellButton.OnPressed += _ => OnSell?.Invoke();
    }

    public void UpdateState(CESellingPlatformUiState state)
    {
        if (!_e.TryGetComponent<CETradingReputationComponent>(_player.LocalEntity, out var repComp))
            return;

        _cachedUser = (_player.LocalEntity.Value, repComp);

        var plat = _e.GetEntity(state.Platform);
        if (!_e.TryGetComponent<CESellingPlatformComponent>(plat, out var platComp))
            return;

        _cachedPlatform = (plat, platComp);

        //SpriteView
        SpriteView.SetEntity(_cachedPlatform);

        //SellPrice
        SellPriceHolder.RemoveAllChildren();
        SellPriceHolder.AddChild(new CEPriceControl(state.Price));
        SellButton.Disabled = state.Price == 0;

        //Faction tabs update
        TreeTabsContainer.RemoveAllChildren();
        foreach (var (faction, rep) in _cachedUser.Value.Comp.Reputation)
        {
            if (!_proto.TryIndex(faction, out var indexedFaction))
                continue;
            var factionButton = new CETradingFactionButtonControl(
                indexedFaction.Color,
                Loc.GetString(indexedFaction.Name),
                rep);

            factionButton.OnPressed += () =>
            {
                SelectFaction(indexedFaction);
            };

            TreeTabsContainer.AddChild(factionButton);
        }

        if (_selectedFaction == null)
        {
            var firstFaction = _cachedUser.Value.Comp.Reputation.Keys.First();
            if (_proto.TryIndex(firstFaction, out var indexedFaction))
                SelectFaction(indexedFaction);
        }
        else if (_selectedFaction != null)
        {
            SelectFaction(_selectedFaction);
        }
    }

    private void SelectFaction(CETradingFactionPrototype faction)
    {
        if (_cachedPlatform is null)
            return;

        _selectedFaction = faction;
        TreeName.Text = Loc.GetString("ce-trading-faction-request-prefix") + " " + Loc.GetString(faction.Name);

        //Update requests
        Requests.RemoveAllChildren();
        foreach (var request in _economySystem.GetRequests(faction))
        {
            var canFullfill = _tradingSystem.CanFulfillRequest(_cachedPlatform.Value, request);
            var requestControl = new CESellingRequestControl(request, _cachedPlatform.Value.Comp.PlatformMarkupProcent, canFullfill);

            requestControl.OnSellAttempt += () => OnRequestSell?.Invoke((request, faction));
            Requests.AddChild(requestControl);
        }
    }
}
