- type: job
  id: CEFarmer
  setPreference: true
  name: ce-job-name-farmer
  description: ce-job-desc-farmer
  playTimeTracker: CEJobFarmer
  startingGear: CEFarmerGear
  icon: CEJobIconFarmer
  supervisors: ce-job-supervisors-empire

- type: startingGear
  id: CEFarmerGear
  equipment:
    belt: CEKeyRingFarmer
    pocket1: CEWalletFilledFarmer


- type: entity
  id: CEWalletFilledFarmer
  parent: CEWallet
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents: #100cp total
    - id: CECoinSilver5
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinCopper10

- type: entity
  id: CEChestFilledFarmer
  parent: CEWoodenChest
  suffix: Filled, Farmer
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: CECoinCopper1

- type: entity
  id: CEBedsideTableFilledFarmer
  parent: CEBedsideTableWooden
  suffix: Filled, Farmer
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:GroupSelector
        rolls: !type:RangeNumberSelector
          range: 2, 3
        children:
        - id: CEClothingShirtGreenYellow
        - id: CEClothingPantsHakama
        - id: CEClothingCloakRaincoatGreen
        - id: CEClothingShoesLongLeatherBoots
        - id: CEClothingHeadStrawHat

- type: entity
  id: CEKeyRingFarmer
  parent: CEBaseKeyRing
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: CEKeyTavernHall
    - id: CEKeyTavernStaff
