- type: secretDepartment
  id: CECity
  name: ce-secret-department-city-name
  description: ce-secret-department-city-description
  color: "#87b7ff"
  weight: 10
  roles:
  - CECivilian
  - CEMurkwalker
  - CELover
  - CETormentor
  - CEBountyHunter
  objectives: !type:EntSelector
    id: CEObjectiveCityRestoreLucsonSphere

- type: entity
  id: CEObjectiveCityRestoreLucsonSphere
  name: Restore the Lucson sphere
  description: Perform the Restoration Ritual on the Lucson Sphere before the murk consumes the city.
  components:
  - type: Sprite
    sprite: _CE/Structures/LucsonSphere/core.rsi
    state: full
  - type: CEObjective
  - type: CEObjectiveLucsonSphereRestoreCondition
