- type: secretRole
  id: CECivilian
  name: ce-secret-role-name-civilian
  description: ce-secret-role-description-civilian
  icon: CESecretRoleIconCivilian
  briefing: ce-secret-role-briefing-civilian
