- type: secretRole
  id: CELover
  name: ce-secret-role-name-lover
  description: ce-secret-role-description-lover
  icon: CESecretRoleIconLover
  objectives: !type:AllSelector
    children:
    - !type:EntSelector
      id: CEObjectiveLoverAssist
    - !type:EntSelector
      id: CEObjectiveLoverSurvive
