- type: secretRole
  id: CEPriest
  name: ce-secret-role-name-priest
  description: ce-secret-role-description-priest
  icon: CESecretRoleIconPriest
  skills:
  - CureWounds
  - CEDivineShield
  objectives: !type:EntSelector
    id: CEObjectivePriestSurvive

- type: entity
  id: CEObjectivePriestSurvive
  name: Survive
  description: There are creatures in this city who crave my death.
  components:
  - type: Sprite
    sprite: _CE/Interface/Icons/SecretRoles/city.rsi
    state: priest
  - type: CEObjective
  - type: CETargetObjective
  - type: CETargetHolderObjective
  - type: CETargetSurviveCondition
    defaultProgress: 1
