- type: secretRole
  id: CEThief
  name: ce-secret-role-name-thief
  description: ce-secret-role-description-thief
  icon: CESecretRoleIconThief
  skills:
  - Pickpocketing
  objectives: !type:EntSelector
    id: CEObjectiveThiefCashOut

- type: entity
  id: CEObjectiveThiefCashOut
  name: Cash out
  description: Steal money from other players, sell useful equipment, and spend at least 10 gold coins at the black market.
  components:
  - type: Sprite
    sprite: _CE/Objects/Materials/Currency/coin_gp.rsi
    state: coin10
  - type: CEObjective
  - type: CEObjectiveBlackMarketSpendCondition
    targetGoldSteal: 10
