- type: secretRole
  id: CEThief
  name: ce-secret-role-name-thief
  description: ce-secret-role-description-thief
  icon: CESecretRoleIconThief
  skills:
  - Pickpocketing
  objectives: !type:EntSelector
    id: CEObjectiveThiefCashOut

- type: entity
  id: CEObjectiveThiefCashOut
  name: Squander 10 gold
  description: Spend 10 gold coins on purchases in the shadow shop.
  components:
  - type: Sprite
    sprite: _CE/Objects/Materials/Currency/coin_gp.rsi
    state: coin10
  - type: CEObjective
  - type: CEObjectiveTradeSpendCondition
    targetGoldSpend: 10
