using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.DiscordAuth;

[GenerateTypedNameReferences]
public sealed partial class DiscordAuthGui : Control
{
    [Dependency] private IClientConsoleHost _consoleHost = default!;
    [Dependency] private CEDiscordAuthManager _discordAuthManager = default!;

    private const string DiscordLink = "https://discord.gg/8BEPa9JbZ6";

    public DiscordAuthGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        var link = _discordAuthManager.AuthUrl;
        var errorMessage = _discordAuthManager.ErrorMessage;

        AuthLinkEdit.SetText(link);
        DLinkEdit.SetText(DiscordLink);
        InfoLabel.SetMessage(Loc.GetString("ce-discord-info"));

        var uriOpener = IoCManager.Resolve<IUriOpener>();

        QuitButton.OnPressed += _ =>
        {
            _consoleHost.ExecuteCommand("quit");
        };

        AuthorizeButton.OnPressed += _ =>
        {
            uriOpener.OpenUri(link);
        };

        DiscordButton.OnPressed += _ =>
        {
            uriOpener.OpenUri(DiscordLink);
        };

        if (errorMessage != "")
        {
            InfoLabel.Text = errorMessage;
        }
    }
}
