- type: entity
  id: CEPipeBrass
  name: brass pipe
  description: TODO
  categories: [ ForkFiltered ]
  parent:
  - BaseStructure
  placement:
    mode: SnapgridCenter
  components:
  - type: PlacementReplacement
    key: pipe
  - type: Sprite
    sprite: _CE/Structures/Pipes/brass.rsi
    state: pipe_0
    drawdepth: Mobs
  - type: Icon
    sprite: _CE/Structures/Pipes/brass.rsi
    state: pipe_15
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.3,-0.3,0.3,0.3"
        density: 55
        mask:
        - TableMask
        layer:
        - TableLayer
  - type: Climbable
  - type: Clickable
  - type: Transform
    anchored: true
    noRot: true
    # TODO: Remove both of these, same with CollideOnAnchor
  - type: Physics
    bodyType: Static
  - type: Appearance
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: Metallic
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:DoActsBehavior
        acts: ["Destruction"]
  - type: Cable
    cuttingDelay: 1
    cableDroppedOnCutPrototype: CableHVStack1
    cableType: HighVoltage
  - type: CableVis
    node: power
  - type: CableVisualizer
    statePrefix: pipe_
  - type: NodeContainer
    nodes:
      power:
        !type:CableNode
        nodeGroupID: HVPower
