- type: antag
  id: CEThief
  name: ce-roles-antag-thief-name
  antagonist: true
  setPreference: true
  objective: ce-roles-antag-thief-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 7200 # 2h
  #guides: TODO

- type: startingGear
  id: CEThiefGear
  storage:
    back:
    - CEMachineCoreTradingPlatformBlackMarket
    - CEThiefHideoutFlag

- type: antagSpecifier
  id: CEThief
  prefRoles:
  - CEThief
  startingGear: CEThiefGear
  mindRoles:
  - CEMindRoleThief
  briefing:
    text: ce-roles-antag-thief-briefing
    color: "#527c5e"
    sound: "/Audio/_CE/Ambience/Antag/vampire.ogg"
