# Guard

- type: playTimeTracker
  id: CEJobGuardCommander

- type: playTimeTracker
  id: CEJobGuard

- type: playTimeTracker
  id: CEJobInvestigator

# Citizens

- type: playTimeTracker
  id: CEJobMayor

- type: playTimeTracker
  id: CEJobTownfolk

# Mercenaries

- type: playTimeTracker
  id: CEJobGuildmaster

- type: playTimeTracker
  id: CEJobGuildWorker

- type: playTimeTracker
  id: CEJobMercenary

# Black Covenant

- type: playTimeTracker
  id: CEJobCovenantHead

- type: playTimeTracker
  id: CEJobCovenantAgent