using System.Numerics;
using Content.Client.UserInterface.Screens;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class CEMinimalismGameScreen : InGameScreen
{
    public CEMinimalismGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(TopLeft, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(CharacterMenuButton, LayoutPreset.BottomLeft, margin: 5);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        SetAnchorAndMarginPreset(Chat, LayoutPreset.BottomLeft, margin: 10);
        var chatClearance = 5 + CharacterMenuButton.MinSize.Y + 5;
        SetMarginTop(Chat, Chat.GetValue<float>(MarginTopProperty) - chatClearance);
        SetMarginBottom(Chat, Chat.GetValue<float>(MarginBottomProperty) - chatClearance);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.TopRight, margin: 10);

        TopBar.Visible = false;

        // Health/mana spheres, stamina bar, centered+lowered action bar
        var gap = 310f;
        var manaOffset = ManaBar.MinSize.X / 2f + gap;
        // Mirror health to the left so that HealthBar.Right == -ManaBar.Left.
        var healthOffset = -(HealthBar.MinSize.X + manaOffset);

        SetAnchorAndMarginPreset(HealthBar, LayoutPreset.CenterBottom);
        SetMarginLeft(HealthBar, healthOffset);

        SetAnchorAndMarginPreset(ManaBar, LayoutPreset.CenterBottom);
        SetMarginLeft(ManaBar, manaOffset);

        SetAnchorAndMarginPreset(StaminaBar, LayoutPreset.CenterBottom, margin: 80);
        SetMarginLeft(StaminaBar, -StaminaBar.MinSize.X / 2f);
        SetMarginRight(StaminaBar, StaminaBar.MinSize.X / 2f);

        SetAnchorPreset(Actions, LayoutPreset.BottomWide);
        SetMarginLeft(Actions, 0);
        SetMarginRight(Actions, 0);

        MainViewport.OnResized += ResizeActionContainer;
        Hotbar.OnResized += ResizeActionContainer;
        StaminaBar.OnResized += ResizeActionContainer; // stamina bar's size settles late (waits on networked data), must retrigger too

        ResizeActionContainer();
    }

    private void ResizeActionContainer()
    {
        // Action bar stacks above whichever is taller: stamina bar or hotbar
        float indent = 20;
        var maxWidth = MainViewport.Size.X - indent;
        if (maxWidth > 0)
            Actions.ActionsContainer.MaxGridWidth = maxWidth;

        var staminaTop = 80f + StaminaBar.MinSize.Y;
        var hotbarTop = 5f + Hotbar.Size.Y;
        var actionHeight = MathF.Max(Actions.MinSize.Y, 64f);
        var actionBottomOffset = MathF.Max(staminaTop, hotbarTop) + 8f - actionHeight / 2f;
        SetMarginBottom(Actions, -actionBottomOffset);
        SetMarginTop(Actions, -actionBottomOffset - actionHeight);
    }

    public override ChatBox ChatBox => Chat;

    // Chat is fixed-size, nothing to persist.
    public override void SetChatSize(Vector2 size)
    {
    }
}
