using Content.Shared._CE.Trading.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Trading;

[GenerateTypedNameReferences]
public sealed partial class CEBuyPositionControl : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public event Action<CETradingPositionPrototype>? OnSelect;

    public CEBuyPositionControl(CETradingPositionPrototype entry)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Button.OnPressed += _ => OnSelect?.Invoke(entry);

        UpdateView(entry);
    }

    private void UpdateView(CETradingPositionPrototype entry)
    {
        View.SetPrototype(entry.Service.GetTexture(_proto));
    }
}
