using System.Linq;
using System.Numerics;
using Content.Client._CE.UserInterface;
using Content.Client._CE.UserInterface.Systems.NodeTree;
using Content.Shared._CE.Trading;
using Content.Shared._CE.Trading.Components;
using Content.Shared._CE.Trading.Prototypes;
using Content.Shared._CE.Trading.Systems;
using Content.Shared.Power.Components;
using Robust.Client.AutoGenerated;
using Content.Shared._CE.Workbench.Prototypes;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static Robust.Shared.Localization.Loc;

namespace Content.Client._CE.Trading;

[GenerateTypedNameReferences]
public sealed partial class CETradingPlatformWindow : DefaultWindow
{
    [Dependency] private readonly ILogManager _log = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly CEClientTradingPlatformSystem _tradingSystem;
    private string _searchFilter = string.Empty;

    private CETradingPlatformUiState? _cachedState;
    private Entity<CETradingPlatformComponent>? _cachedPlatform;

    private CETradingPositionPrototype? _selectedPosition;
    private HashSet<CETradingPositionPrototype> _uncategorized = new();

    /// <summary>
    /// Used for category dropdown filtering.
    /// </summary>
    private readonly Dictionary<int, LocId> _categoryIndexes = new();
    private Dictionary<LocId, HashSet<CETradingPositionPrototype>> _categories = new();

    public event Action<ProtoId<CETradingPositionPrototype>>? OnBuy;
    public event Action? OnSell;
    public event Action<ProtoId<CETradingRequestPrototype>>? OnRequestSell;

    private const int AllCategoryId = -1;
    private ISawmill Sawmill { get; init; }

    public CETradingPlatformWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Sawmill = _log.GetSawmill("ce_trading");
        _tradingSystem = _entityManager.System<CEClientTradingPlatformSystem>();

        UpdatePositionVisibility();
        _prototype.PrototypesReloaded += _ => UpdatePositionVisibility();

        SearchBar.OnTextChanged += OnSearchChanged;
        BuyButton.OnPressed += BuyPressed;
        SellButton.OnPressed += _ => OnSell?.Invoke();
        OptionCategories.OnItemSelected += OnCategoryItemSelected;
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs _)
    {
        _searchFilter = SearchBar.Text.Trim().ToLowerInvariant();
        UpdatePositionVisibility();
    }

    private void OnCategoryItemSelected(OptionButton.ItemSelectedEventArgs obj)
    {
        OptionCategories.SelectId(obj.Id);
        UpdatePositionVisibility();
    }

    private void UpdatePositionVisibility()
    {
        if (_cachedState is null)
            return;

        CraftsContainer.RemoveAllChildren();

        if (_uncategorized.Count > 0 && OptionCategories.SelectedId == AllCategoryId)
        {
            var uncategorizedGridContainer = new GridContainer();
            uncategorizedGridContainer.Columns = 10;
            uncategorizedGridContainer.VerticalExpand = true;

            CraftsContainer.AddChild(uncategorizedGridContainer);
            AddRecipeListToGrid(_uncategorized, uncategorizedGridContainer);
        }

        foreach (var category in _categories)
        {
            if (_categoryIndexes.TryGetValue(OptionCategories.SelectedId, out var selectedCategory) &&
                category.Key != selectedCategory)
                continue;

            var categoryLabel = new RichTextLabel();
            categoryLabel.Margin = new Thickness(5);
            categoryLabel.Text = GetString(category.Key);
            CraftsContainer.AddChild(categoryLabel);

            var gridContainer = new GridContainer();
            gridContainer.Columns = 10;
            gridContainer.VerticalExpand = true;
            CraftsContainer.AddChild(gridContainer);

            AddRecipeListToGrid(category.Value, gridContainer);
        }
    }

    private void AddRecipeListToGrid(IEnumerable<CETradingPositionPrototype> category, GridContainer gridContainer)
    {
        if (_cachedState is null)
            return;

        foreach (var entry in category)
        {
            if (!ProcessSearchFilter(entry))
                continue;

            if (!ProcessSearchCategoryFilter(entry))
                continue;

            var active = _tradingSystem.GetPrice(entry) <= _cachedState.BuyBalance;
            var control = new CEBuyPositionControl(entry, active);
            control.OnSelect += SelectPosition;

            gridContainer.AddChild(control);
        }
    }

    private bool ProcessSearchCategoryFilter(CETradingPositionPrototype indexedEntry)
    {
        // If we are searching through all categories, we simply skip the current filter
        if (OptionCategories.SelectedId == AllCategoryId)
            return true;

        if (!_categoryIndexes.TryGetValue(OptionCategories.SelectedId, out var selectedCategory))
        {
            Sawmill.Error($"Non-existent {OptionCategories.SelectedId} category id selected. Filter skipped");
            return true;
        }

        var catProtoId = indexedEntry.Category;

        // If the entry doesn't have an explicit category, it's uncategorized
        // and should not match a specific category filter.
        if (catProtoId is null)
            return false;

        if (!_prototype.TryIndex(catProtoId, out CEWorkbenchRecipeCategoryPrototype? indexedCategory))
        {
            Sawmill.Error($"Non-existent {catProtoId} category prototype id. Filter skipped");
            return true;
        }

        return indexedCategory.Name == selectedCategory;
    }

    private bool ProcessSearchFilter(CETradingPositionPrototype indexedEntry)
    {
        if (_searchFilter == string.Empty)
            return true;

        return _tradingSystem.GetTradeName(indexedEntry).Contains(_searchFilter);
    }

    private void BuyPressed(BaseButton.ButtonEventArgs obj)
    {
        if (_selectedPosition is null)
            return;

        OnBuy?.Invoke(_selectedPosition.ID);
    }

    private void SelectPosition(CETradingPositionPrototype node)
    {
        if (_cachedPlatform is null)
        {
            DeselectNode();
            return;
        }

        if (_cachedState == null)
        {
            Sawmill.Error("Tried to select node without a cached state.");
            return;
        }

        _selectedPosition = node;

        Name.Text = _tradingSystem.GetTradeName(_selectedPosition);
        Description.Text = _tradingSystem.GetTradeDescription(_selectedPosition);
        LocationView.SetPrototype(_selectedPosition.Service.GetTexture(_prototype));

        BuyPriceHolder.RemoveAllChildren();
        var price = _tradingSystem.GetPrice(_selectedPosition) ?? 0;
        BuyPriceHolder.AddChild(new CEPriceControl((int)price));
    }

    private void DeselectNode()
    {
        Name.Text = string.Empty;
        Description.Text = string.Empty;
        LocationView.SetPrototype(null);
    }

    public void UpdateState(CETradingPlatformUiState state)
    {
        _cachedState = state;

        var platform = _entityManager.GetEntity(state.Platform);
        if (_entityManager.TryGetComponent<CETradingPlatformComponent>(platform, out var platformComp))
            _cachedPlatform = (platform, platformComp);

        _categoryIndexes.Clear();
        _categories.Clear();
        _uncategorized.Clear();
        OptionCategories.Clear();
        OptionCategories.AddItem(GetString("ce-recipe-category-all"), AllCategoryId);

        if (_player.LocalEntity is null)
            return;

        // Get all positions for this platform's faction
        var sortedRecipes = _prototype.EnumeratePrototypes<CETradingPositionPrototype>()
            .Where(e => e.Faction == state.Faction)
            .OrderBy(e =>
            {
                if (e.Category != null && _prototype.TryIndex(e.Category, out var category))
                    return category.ID;
                return string.Empty;
            });

        // Group positions by category
        foreach (var entry in sortedRecipes)
        {
            if (entry.Category == null)
            {
                _uncategorized.Add(entry);
                continue;
            }

            if (!_prototype.TryIndex(entry.Category, out var category))
            {
                Sawmill.Warning($"Position {entry.ID} references non-existent category {entry.Category}");
                _uncategorized.Add(entry);
                continue;
            }

            if (!_categories.ContainsKey(category.Name))
                _categories[category.Name] = new HashSet<CETradingPositionPrototype>();

            _categories[category.Name].Add(entry);
        }

        // Populate category dropdown, sorted by priority
        var sortedCategories = _categories.Keys
            .Select(name => _prototype.EnumeratePrototypes<CEWorkbenchRecipeCategoryPrototype>()
                .FirstOrDefault(c => c.Name == name))
            .Where(c => c != null)
            .OrderByDescending(c => c!.Priority)
            .ToList();

        var count = 0;
        foreach (var category in sortedCategories)
        {
            OptionCategories.AddItem(GetString(category!.Name), count);
            _categoryIndexes.Add(count, category.Name);
            count++;
        }

        // Sell UI
        SellPriceHolder.RemoveAllChildren();
        SellPriceHolder.AddChild(new CEPriceControl(state.SellBalance));

        if (_prototype.TryIndex(state.Faction, out var platformFaction))
            TreeName.Text = Loc.GetString("ce-trading-faction-request-prefix") + " " + Loc.GetString(platformFaction.Name);
        else
            TreeName.Text = string.Empty;

        Requests.RemoveAllChildren();
        foreach (var request in _tradingSystem.GetRequests(state.Faction))
        {
            var canFullfill = _tradingSystem.CanFulfillRequest(platform, request);
            var requestControl = new CESellingRequestControl(request, canFullfill);

            requestControl.OnSellAttempt += () => OnRequestSell?.Invoke(request);
            Requests.AddChild(requestControl);
        }

        UpdatePositionVisibility();
    }
}
