using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.Trading;

[GenerateTypedNameReferences]
public sealed partial class CETradingFactionButtonControl : Control
{
    public event Action? OnPressed;

    public CETradingFactionButtonControl(Color color, string label, FixedPoint2 reputation)
    {
        RobustXamlLoader.Load(this);

        ColorPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
        SkillTreeLabel.Text = $"{reputation}   {label}";

        MainButton.OnPressed += args => OnPressed?.Invoke();
    }
}
