using System.Linq;
using System.Numerics;
using Content.Client._CE.UserInterface;
using Content.Client._CE.UserInterface.Systems.NodeTree;
using Content.Shared._CE.Trading;
using Content.Shared._CE.Trading.Components;
using Content.Shared._CE.Trading.Prototypes;
using Content.Shared._CE.Trading.Systems;
using Content.Shared.Power.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static Robust.Shared.Localization.Loc;

namespace Content.Client._CE.Trading;

[GenerateTypedNameReferences]
public sealed partial class CETradingPlatformWindow : DefaultWindow
{
    [Dependency] private readonly ILogManager _log = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _e = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly CEClientTradingPlatformSystem _tradingSystem;
    private string _searchFilter = string.Empty;

    private CETradingPlatformUiState? _cachedState;
    private Entity<CETradingReputationComponent>? _cachedUser;
    private Entity<CETradingPlatformComponent>? _cachedPlatform;

    private CETradingPositionPrototype? _selectedPosition;

    /// <summary>
    /// Used for category dropdown filtering.
    /// </summary>
    private readonly Dictionary<int, LocId> _categoryIndexes = new();
    private Dictionary<LocId, HashSet<CETradingPositionPrototype>> _categories = new();

    public event Action<ProtoId<CETradingPositionPrototype>>? OnBuy;

    private const int AllCategoryId = -1;
    private ISawmill Sawmill { get; init; }

    public CETradingPlatformWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Sawmill = _log.GetSawmill("ce_trading");
        _tradingSystem = _e.System<CEClientTradingPlatformSystem>();

        UpdatePositionVisibility();
        _prototype.PrototypesReloaded += _ => UpdatePositionVisibility();

        SearchBar.OnTextChanged += OnSearchChanged;
        BuyButton.OnPressed += BuyPressed;
        OptionCategories.OnItemSelected += OnCategoryItemSelected;
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs _)
    {
        _searchFilter = SearchBar.Text.Trim().ToLowerInvariant();
        UpdatePositionVisibility();
    }

    private void OnCategoryItemSelected(OptionButton.ItemSelectedEventArgs obj)
    {
        OptionCategories.SelectId(obj.Id);
        UpdatePositionVisibility();
    }

    private void UpdatePositionVisibility()
    {
        if (_cachedState is null)
            return;

        CraftsContainer.RemoveAllChildren();

        foreach (var category in _categories)
        {
            if (_categoryIndexes.TryGetValue(OptionCategories.SelectedId, out var selectedCategory) &&
                category.Key != selectedCategory)
                continue;

            var categoryLabel = new RichTextLabel();
            categoryLabel.Margin = new Thickness(5);
            categoryLabel.Text = GetString(category.Key);
            CraftsContainer.AddChild(categoryLabel);

            var gridContainer = new GridContainer();
            gridContainer.Columns = 10;
            gridContainer.VerticalExpand = true;
            CraftsContainer.AddChild(gridContainer);

            AddRecipeListToGrid(category.Value, gridContainer);
        }
    }

    private void AddRecipeListToGrid(IEnumerable<CETradingPositionPrototype> category, GridContainer gridContainer)
    {
        if (_cachedState is null)
            return;

        foreach (var entry in category)
        {
            if (!ProcessSearchFilter(entry))
                continue;

            if (!ProcessSearchCategoryFilter(entry))
                continue;

            var active = _tradingSystem.GetPrice(entry) <= _cachedState.Price;
            var control = new CEBuyPositionControl(entry, active);
            control.OnSelect += SelectPosition;

            gridContainer.AddChild(control);
        }
    }

    private bool ProcessSearchCategoryFilter(CETradingPositionPrototype indexedEntry)
    {
        // If we are searching through all categories, we simply skip the current filter
        if (OptionCategories.SelectedId == AllCategoryId)
            return true;

        if (!_categoryIndexes.TryGetValue(OptionCategories.SelectedId, out var selectedCategory))
        {
            Sawmill.Error($"Non-existent {OptionCategories.SelectedId} category id selected. Filter skipped");
            return true;
        }

        if (!_prototype.TryIndex(indexedEntry.Faction, out var indexedFaction))
        {
            Sawmill.Error($"Non-existent {indexedEntry.Faction} faction prototype id. Filter skipped");
            return true;
        }

        return indexedFaction.Name == selectedCategory;
    }

    private bool ProcessSearchFilter(CETradingPositionPrototype indexedEntry)
    {
        if (_searchFilter == string.Empty)
            return true;

        return _tradingSystem.GetTradeName(indexedEntry).Contains(_searchFilter);
    }

    private void BuyPressed(BaseButton.ButtonEventArgs obj)
    {
        if (_selectedPosition is null)
            return;

        OnBuy?.Invoke(_selectedPosition.ID);
    }

    private void SelectPosition(CETradingPositionPrototype node)
    {
        if (_cachedUser is null || _cachedPlatform is null)
        {
            DeselectNode();
            return;
        }

        if (_cachedState == null)
        {
            Sawmill.Error("Tried to select node without a cached state.");
            return;
        }

        _selectedPosition = node;

        Name.Text = _tradingSystem.GetTradeName(_selectedPosition);
        Description.Text = _tradingSystem.GetTradeDescription(_selectedPosition);
        LocationView.SetPrototype(_selectedPosition.Service.GetTexture(_prototype));

        BuyPriceHolder.RemoveAllChildren();
        var price = _tradingSystem.GetPrice(_selectedPosition) ?? 0;
        BuyPriceHolder.AddChild(new CEPriceControl((int)price));
    }

    private void DeselectNode()
    {
        Name.Text = string.Empty;
        Description.Text = string.Empty;
        LocationView.SetPrototype(null);
    }

    public void UpdateState(CETradingPlatformUiState state)
    {
        _cachedState = state;

        _categoryIndexes.Clear();
        _categories.Clear();
        OptionCategories.Clear();
        OptionCategories.AddItem(GetString("ce-recipe-category-all"), AllCategoryId);

        if (_player.LocalEntity is null)
            return;

        if (!_e.TryGetComponent<CETradingReputationComponent>(_player.LocalEntity, out var repComp))
            return;

        _cachedUser = (_player.LocalEntity.Value, repComp);

        // First, we sort all the recipes by priority and category.
        var sortedRecipes = _prototype.EnumeratePrototypes<CETradingPositionPrototype>()
            .OrderBy(e => _tradingSystem.GetPrice(e));

        foreach (var entry in sortedRecipes)
        {
            if (!_prototype.TryIndex(entry.Faction, out var indexedFaction))
                continue;

            var factions = repComp.Factions;
            if (!factions.Contains(indexedFaction))
                continue;

            if (!_categories.TryGetValue(indexedFaction.Name, out var entries))
            {
                entries = new();
                _categories[indexedFaction.Name] = entries;
            }

            entries.Add(entry);
        }

        var plat = _e.GetEntity(state.Platform);
        if (!_e.TryGetComponent<CETradingPlatformComponent>(plat, out var platComp))
            return;

        var count = 0;
        foreach (var category in _categories)
        {
            OptionCategories.AddItem(GetString(category.Key), count);
            _categoryIndexes.Add(count, category.Key);
            count++;
        }

        _cachedPlatform = (plat, platComp);

        UpdatePositionVisibility();
    }
}
