using System.Linq;
using System.Numerics;
using Content.Client._CE.UserInterface;
using Content.Client._CE.UserInterface.Systems.NodeTree;
using Content.Shared._CE.Trading;
using Content.Shared._CE.Trading.Components;
using Content.Shared._CE.Trading.Prototypes;
using Content.Shared._CE.Trading.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._CE.Trading;

[GenerateTypedNameReferences]
public sealed partial class CETradingPlatformWindow : DefaultWindow
{
    [Dependency] private readonly ILogManager _log = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntityManager _e = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly CEClientTradingPlatformSystem _tradingSystem;
    private readonly CEClientEconomySystem _economySystem;

    private CETradingPlatformUiState? _cacheState;
    private Entity<CETradingReputationComponent>? _cachedUser;
    private Entity<CETradingPlatformComponent>? _cachedPlatform;

    private IEnumerable<CETradingPositionPrototype> _allPositions = [];

    private ProtoId<CETradingFactionPrototype>? _selectedFaction;
    private CETradingPositionPrototype? _selectedPosition;
    public event Action<ProtoId<CETradingPositionPrototype>>? OnBuy;

    private ISawmill Sawmill { get; init; }

    public CETradingPlatformWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Sawmill = _log.GetSawmill("ce_trading");

        CacheSkillProto();
        _proto.PrototypesReloaded += _ => CacheSkillProto();
        if (_cachedUser is not null)
        {
            foreach (var faction in _cachedUser.Value.Comp.Contracts)
            {
                if (_proto.TryIndex(faction, out var indexedFaction))
                {
                    SelectFaction(indexedFaction);
                    break;
                }
            }
        }

        _tradingSystem = _e.System<CEClientTradingPlatformSystem>();
        _economySystem = _e.System<CEClientEconomySystem>();

        GraphControl.OnOffsetChanged += offset =>
        {
            ParallaxBackground.Offset = -offset * 0.25f + new Vector2(1000, 1000); //hardcoding is bad
        };
        GraphControl.OnNodeSelected += SelectNode;
        BuyButton.OnPressed += BuyPressed;
    }

    private void BuyPressed(BaseButton.ButtonEventArgs obj)
    {
        if (_selectedPosition is null)
            return;

        OnBuy?.Invoke(_selectedPosition.ID);
    }

    private void SelectNode(CENodeTreeElement? node)
    {
        if (node == null)
        {
            DeselectNode();
            return;
        }

        if (_cacheState == null)
        {
            Sawmill.Error("Tried to select node without a cached state.");
            return;
        }

        if (!_proto.TryIndex<CETradingPositionPrototype>(node.NodeKey, out var indexedPosition))
            return;

        SelectNode(indexedPosition);
    }

    private void SelectNode(CETradingPositionPrototype? node)
    {
        if (node is null || _cachedUser is null || _cachedPlatform is null)
        {
            DeselectNode();
            return;
        }

        if (_cacheState == null)
        {
            Sawmill.Error("Tried to select node without a cached state.");
            return;
        }

        _selectedPosition = node;

        Name.Text = _tradingSystem.GetTradeName(_selectedPosition);
        Description.Text = _tradingSystem.GetTradeDescription(_selectedPosition);
        LocationView.Texture = _selectedPosition.Icon.Frame0();

        BuyPriceHolder.RemoveAllChildren();
        var price = _tradingSystem.GetPrice(_selectedPosition) * _cachedPlatform.Value.Comp.PlatformMarkupProcent ?? 0;
        BuyPriceHolder.AddChild(new CEPriceControl((int)price));
    }

    private void DeselectNode()
    {
        Name.Text = string.Empty;
        Description.Text = string.Empty;
        LocationView.Texture = null;
    }

    private void CacheSkillProto()
    {
        _allPositions = _proto.EnumeratePrototypes<CETradingPositionPrototype>();
        UpdateGraphControl();
    }

    public void UpdateState(CETradingPlatformUiState state)
    {
        _cacheState = state;

        if (!_e.TryGetComponent<CETradingReputationComponent>(_player.LocalEntity, out var repComp))
            return;

        _cachedUser = (_player.LocalEntity.Value, repComp);

        var plat = _e.GetEntity(state.Platform);
        if (!_e.TryGetComponent<CETradingPlatformComponent>(plat, out var platComp))
            return;

        _cachedPlatform = (plat, platComp);
        UpdateGraphControl();
    }

    private void UpdateGraphControl()
    {
        if (_cachedUser is null)
            return;

        HashSet<CENodeTreeElement> nodeTreeElements = new();
        var edges = new HashSet<(string, string)>();
        foreach (var position in _allPositions)
        {
            if (position.Faction != _selectedFaction)
                continue;

            var active = _tradingSystem.CanBuyPosition((_cachedUser.Value.Owner, _cachedUser.Value.Comp), position);
            var node = new CENodeTreeElement(position.ID, true, active, new Vector2(position.UiPosition.X * 50, position.UiPosition.Y * 50) , position.Icon);
            nodeTreeElements.Add(node);
        }

        GraphControl.UpdateState(
            new CENodeTreeUiState(
                nodeTreeElements,
                edges: edges,
                frameIcon: new SpriteSpecifier.Rsi(
                    new ResPath("/Textures/_CE/Interface/NodeTree/trading.rsi"),
                    "frame"),
                hoveredIcon: new SpriteSpecifier.Rsi(
                    new ResPath("/Textures/_CE/Interface/NodeTree/trading.rsi"),
                    "hovered"),
                selectedIcon: new SpriteSpecifier.Rsi(
                    new ResPath("/Textures/_CE/Interface/NodeTree/trading.rsi"),
                    "selected"),
                learnedIcon: new SpriteSpecifier.Rsi(
                    new ResPath("/Textures/_CE/Interface/NodeTree/trading.rsi"),
                    "learned"),
                activeLineColor: new Color(172, 102, 190),
                lineColor: new Color(83, 40, 121)
            )
        );

        //Faction tabs update
        TreeTabsContainer.RemoveAllChildren();
        foreach (var faction in _cachedUser.Value.Comp.Contracts)
        {
            if (!_proto.TryIndex(faction, out var indexedFaction))
                continue;
            var factionButton = new CETradingFactionButtonControl(
                indexedFaction.Color,
                Loc.GetString(indexedFaction.Name));

            factionButton.OnPressed += () =>
            {
                SelectFaction(indexedFaction);
            };

            TreeTabsContainer.AddChild(factionButton);
        }
        SelectNode(_selectedPosition);
    }

    private void SelectFaction(CETradingFactionPrototype faction)
    {
        _selectedFaction = faction;
        TreeName.Text = Loc.GetString("ce-trading-faction-prefix") + " " + Loc.GetString(faction.Name);
        UpdateGraphControl();
    }
}
