using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.Map;

[GenerateTypedNameReferences]
public sealed partial class CEMapWindow : DefaultWindow
{
    public CEMapWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetMap(EntityUid? mapUid)
    {
        ZNavMap.MapUid = mapUid;
        ZNavMap.ForceNavMapUpdate();
    }
}
