using Content.Client.Pinpointer.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.Map;

[GenerateTypedNameReferences]
public sealed partial class CEMapWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entManager = default!;

    private static readonly SpriteSpecifier.Texture DeviceBlip =
        new(new ResPath("/Textures/Interface/NavMap/beveled_circle.png"));

    public CEMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetMap(EntityUid owner, EntityUid? mapUid)
    {
        ZNavMap.MapUid = mapUid;
        ZNavMap.ForceNavMapUpdate();

        // Mark where the device that opened this map is located, like the power monitoring console does.
        var netEntity = _entManager.GetNetEntity(owner);

        if (_entManager.TryGetComponent<TransformComponent>(owner, out var xform))
        {
            var spriteSystem = _entManager.System<SpriteSystem>();
            var texture = spriteSystem.Frame0(DeviceBlip);
            ZNavMap.TrackedEntities[netEntity] = new NavMapBlip(xform.Coordinates, texture, Color.Cyan, true, false);
        }
    }
}
