- type: secretRole
  parent: CEBaseSecretRoleGuardRestricted
  id: CEWerewolf
  name: ce-secret-role-name-werewolf
  description: ce-secret-role-description-werewolf
  icon: CESecretRoleIconWerewolf
  skills:
  - Murkwalker
  - TimeSense
  - CEWerewolfTransformation
  objectives: !type:EntSelector
    id: CEObjectiveNightmareHunt
    amount: 3

- type: entity
  id: CEObjectiveNightmareHunt
  name: Hunt a victim
  description: Kill, kill, kill!
  components:
  - type: Sprite
    sprite: _CE/Actions/misc.rsi
    state: todo
  - type: CEObjective
  - type: CETargetObjective
    title: ce-nightmare-hunt-objective-title
  - type: CETargetPlayersObjective
  - type: CETargetExcludeHolderDepartment
  - type: CETargetKillCondition
