- type: secretRole
  parent: CEBaseSecretRoleGuardRestricted
  id: CEWerewolf
  name: ce-secret-role-name-werewolf
  description: ce-secret-role-description-werewolf
  icon: CESecretRoleIconWerewolf
  briefing: ce-secret-role-briefing-werewolf
  skills:
  - Murkwalker
  - CEWerewolfTransformation
  objectives: !type:EntSelector
    id: CEObjectiveNightmareHunt
    amount: 3
