- type: secretRole
  parent: CEBaseSecretRoleGuardRestricted
  id: CEWerewolf
  name: ce-secret-role-name-werewolf
  description: ce-secret-role-description-werewolf
  icon: CESecretRoleIconWerewolf
  skills:
  - Murkwalker
  - TimeSense
  - CEWerewolfTransformation
  objectives: !type:EntSelector
    id: CEObjectiveNightmareKillPriests

- type: entity
  id: CEObjectiveNightmareKillPriests
  name: Death to the light
  description: There are priests of light in this city whose very existence is repugnant to your nature. Find them out and kill them.
  components:
  - type: Sprite
    sprite: _CE/Interface/Icons/SecretRoles/city.rsi
    state: priest
  - type: CEObjective
  - type: CEObjectiveDepartmentSurviveCondition
    roles:
    - CEPriest
    invert: true
