using System.Numerics;
using Content.Client._CE.ResourceManager;
using Content.Client.Guidebook.Controls;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared._CE.InfusionAltar;
using Content.Shared._CE.InfusionAltar.Prototypes;
using Content.Shared._CE.MagicEssence.Prototypes;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Guidebook.Controls;

/// <summary>
/// Guidebook card for a single infusion altar recipe known to the local player: result icon, catalyst,
/// and the round-rolled essence/pedestal requirements carried by <see cref="CEInfusionAltarKnownRecipeInfo"/>.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class CEGuideInfusionAltarRecipeEmbed : PanelContainer, ISearchableControl
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _prototype = default!;

    private readonly SpriteSystem _sprite;

    public CEGuideInfusionAltarRecipeEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MouseFilter = MouseFilterMode.Stop;
        _sprite = _entity.System<SpriteSystem>();
    }

    public CEGuideInfusionAltarRecipeEmbed(CEInfusionAltarRecipePrototype recipe, CEInfusionAltarKnownRecipeInfo info) : this()
    {
        GenerateControl(recipe, info);
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    private void GenerateControl(CEInfusionAltarRecipePrototype recipe, CEInfusionAltarKnownRecipeInfo info)
    {
        ResultView.SetPrototype(recipe.Result);

        var counter = recipe.ResultCount > 1 ? $" x{recipe.ResultCount}" : string.Empty;
        ResultName.SetMarkup((_prototype.TryIndex(recipe.Result, out var result) ? result.Name : recipe.Result.Id) + counter);

        CatalystContainer.RemoveAllChildren();
        CatalystContainer.AddChild(new CEResourceRequirementControl(recipe.Catalyst));

        EssenceContainer.RemoveAllChildren();
        foreach (var (type, amount) in info.Essences)
        {
            EssenceContainer.AddChild(CreateEssenceChip(type, amount));
        }

        PedestalContainer.RemoveAllChildren();
        PedestalSection.Visible = info.PedestalRequirementIndices.Count > 0;
        foreach (var index in info.PedestalRequirementIndices)
        {
            if (index < 0 || index >= recipe.PedestalRequirementPool.Count)
                continue;

            PedestalContainer.AddChild(new CEResourceRequirementControl(recipe.PedestalRequirementPool[index].Requirement));
        }
    }

    private Control CreateEssenceChip(ProtoId<CEMagicEssenceTypePrototype> essenceId, int amount)
    {
        var chip = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalAlignment = HAlignment.Center,
            SeparationOverride = 2,
        };

        if (_prototype.TryIndex(essenceId, out var essence))
        {
            chip.AddChild(new TextureRect
            {
                Texture = _sprite.Frame0(essence.Icon),
                SetSize = new Vector2(24, 24),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
            });

            var label = new RichTextLabel();
            label.SetMarkup($"{essence.Name} x{amount}");
            chip.AddChild(label);
        }
        else
        {
            chip.AddChild(new Label { Text = $"{essenceId.Id} x{amount}" });
        }

        return chip;
    }
}
