using System.Diagnostics.CodeAnalysis;
using System.Numerics;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared._CE.MagicEssence.Prototypes;
using Content.Shared._CE.MagicEssence.Systems;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Guidebook.Controls;

/// <summary>
/// Guidebook card for a single thaumaturgical aspect: colored header, big icon, flavour text and
/// (if any) its combination recipe. Recipe data is resolved via <see cref="CEMagicEssenceSystem.GetRecipeComponents"/>,
/// which never assumes prototype IDs coincide - see that method for why.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class CEGuideEssenceRecipeEmbed : PanelContainer, IDocumentTag, ISearchableControl
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private ILogManager _logManager = default!;

    private readonly SpriteSystem _sprite;
    private readonly CEMagicEssenceSystem _essence;
    private readonly ISawmill _sawmill;

    public CEGuideEssenceRecipeEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MouseFilter = MouseFilterMode.Stop;
        _sprite = _entity.System<SpriteSystem>();
        _essence = _entity.System<CEMagicEssenceSystem>();
        _sawmill = _logManager.GetSawmill("guidebook.ce_essence_recipe");
    }

    public CEGuideEssenceRecipeEmbed(CEMagicEssenceTypePrototype essence) : this()
    {
        GenerateControl(essence);
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Essence", out var id))
        {
            _sawmill.Error("CE essence recipe embed tag is missing Essence argument");
            return false;
        }

        if (!_prototype.TryIndex<CEMagicEssenceTypePrototype>(id, out var essence))
        {
            _sawmill.Error($"Specified essence type \"{id}\" is not a valid magicEssenceType prototype");
            return false;
        }

        GenerateControl(essence);
        control = this;
        return true;
    }

    private void GenerateControl(CEMagicEssenceTypePrototype essence)
    {
        HeaderPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = essence.Color };

        var r = essence.Color.R;
        var g = essence.Color.G;
        var b = essence.Color.B;
        var textColor = 0.2126f * r + 0.7152f * g + 0.0722f * b > 0.5
            ? Color.Black
            : Color.White;

        AspectName.SetMarkup($"[color={textColor.ToHex()}]{essence.Name}[/color]");

        AspectIcon.Texture = _sprite.Frame0(essence.Icon);

        if (essence.Desc is { } descKey)
        {
            DescriptionContainer.Visible = true;
            AspectDescription.SetMarkup(Loc.GetString(descKey));
        }
        else
        {
            DescriptionContainer.Visible = false;
        }

        GenerateRecipe(essence);
    }

    private void GenerateRecipe(CEMagicEssenceTypePrototype essence)
    {
        RecipeContainer.RemoveAllChildren();

        var components = _essence.GetRecipeComponents(essence.ID);
        if (components.Count == 0)
        {
            RecipeContainer.Visible = false;
            return;
        }

        RecipeContainer.Visible = true;

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalAlignment = HAlignment.Center,
            SeparationOverride = 6,
        };

        for (var i = 0; i < components.Count; i++)
        {
            if (i > 0)
                row.AddChild(new Label { Text = "+", VerticalAlignment = VAlignment.Center });

            row.AddChild(CreateComponentChip(components[i]));
        }

        RecipeContainer.AddChild(row);
    }

    private Control CreateComponentChip(ProtoId<CEMagicEssenceTypePrototype> componentId)
    {
        var chip = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalAlignment = HAlignment.Center,
            SeparationOverride = 2,
        };

        if (_prototype.TryIndex(componentId, out var component))
        {
            chip.AddChild(new TextureRect
            {
                Texture = _sprite.Frame0(component.Icon),
                SetSize = new Vector2(24, 24),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
            });

            var label = new RichTextLabel();
            label.SetMarkup(component.Name);
            chip.AddChild(label);
        }
        else
        {
            chip.AddChild(new Label { Text = componentId.Id });
        }

        return chip;
    }
}
