using System;
using System.Linq;
using System.Numerics;
using Content.Client._CE.MagicEssence.Controls;
using Content.Client.Guidebook.Controls;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared._CE.InfusionAltar;
using Content.Shared._CE.InfusionAltar.Prototypes;
using Content.Shared._CE.ResourceManager;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Guidebook.Controls;

/// <summary>
/// Guidebook card for a single infusion altar recipe known to the local player. Draws a small diagram:
/// the altar (with the catalyst floating above it) in the center, the recipe's pedestal items arranged
/// evenly around it in a circle starting from the top, and the round-rolled essence cost as a row underneath.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class CEGuideInfusionAltarRecipeEmbed : PanelContainer, ISearchableControl
{
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _prototype = default!;

    private static readonly EntProtoId AltarProto = "CEInfusionAltar";
    private static readonly EntProtoId PedestalProto = "CEInfusionAltarPedestal";

    private const float DiagramCenterX = 165f;
    private const float DiagramCenterY = 175f;
    private const float PedestalOrbitRadius = 110f;
    private const float AltarIconSize = 96f;
    private const float CatalystIconSize = 72f;
    private const float PedestalIconSize = 96f;
    private const float PedestalItemIconSize = 72f;
    private const float EssenceIconSize = 32f;
    private const float ResultIconSize = 64f;

    private readonly SpriteSystem _sprite;

    /// <summary>
    /// Extra search terms not carried by any Label/RichTextLabel child - the catalyst, pedestal item,
    /// and essence names, which <see cref="ControlExtension.ChildrenContainText"/> can't see since they
    /// only appear as icon tooltips in this diagram. Populated fresh each <see cref="GenerateControl"/>.
    /// </summary>
    private readonly List<string> _searchableExtras = new();

    public CEGuideInfusionAltarRecipeEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MouseFilter = MouseFilterMode.Stop;
        _sprite = _entity.System<SpriteSystem>();
    }

    public CEGuideInfusionAltarRecipeEmbed(CEInfusionAltarRecipePrototype recipe, CEInfusionAltarKnownRecipeInfo info) : this()
    {
        GenerateControl(recipe, info);
    }

    public bool CheckMatchesSearch(string query)
    {
        if (this.ChildrenContainText(query))
            return true;

        foreach (var extra in _searchableExtras)
        {
            if (extra.Contains(query, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    private void GenerateControl(CEInfusionAltarRecipePrototype recipe, CEInfusionAltarKnownRecipeInfo info)
    {
        ResultIcon.Scale = EntityViewScale(ResultIconSize);
        ResultIcon.SetPrototype(recipe.Result);

        _prototype.TryIndex(recipe.Result, out var result);
        ResultName.Text = result?.Name ?? recipe.Result.Id;
        ResultCount.SetMarkup($"x{recipe.ResultCount}");
        ResultDescription.SetMarkup(result?.Description ?? string.Empty);

        _searchableExtras.Clear();
        _searchableExtras.Add(recipe.Catalyst.GetRequirementTitle(_prototype));

        DiagramRoot.RemoveAllChildren();

        var center = new Vector2(DiagramCenterX, DiagramCenterY);

        // Entities are drawn in top-to-bottom order (painter's algorithm) so lower entities overlap
        // higher ones, matching how they'd occlude each other from a top-down perspective. Each
        // entity's floating item is grouped with it and always drawn immediately after (on top of) its
        // own entity, regardless of the cross-group ordering.
        var groups = new List<(Control Entity, Vector2 Center, float EntitySize, Control? Item)>
        {
            (CreateEntityIcon(AltarProto, AltarIconSize), center, AltarIconSize, CreateRequirementIcon(recipe.Catalyst, CatalystIconSize)),
        };

        var pedestalCount = info.PedestalRequirementIndices.Count;
        for (var i = 0; i < pedestalCount; i++)
        {
            var angle = -MathF.PI / 2f + i * (2f * MathF.PI / pedestalCount);
            var pedestalCenter = center + PedestalOrbitRadius * new Vector2(MathF.Cos(angle), MathF.Sin(angle));

            Control? itemIcon = null;
            var index = info.PedestalRequirementIndices[i];
            if (index >= 0 && index < recipe.PedestalRequirementPool.Count)
            {
                var pedestalRequirement = recipe.PedestalRequirementPool[index].Requirement;
                itemIcon = CreateRequirementIcon(pedestalRequirement, PedestalItemIconSize);
                _searchableExtras.Add(pedestalRequirement.GetRequirementTitle(_prototype));
            }

            groups.Add((CreateEntityIcon(PedestalProto, PedestalIconSize), pedestalCenter, PedestalIconSize, itemIcon));
        }

        foreach (var group in groups.OrderBy(g => g.Center.Y))
        {
            PlaceCentered(group.Entity, group.Center);
            if (group.Item is { } item)
                PlaceAboveEntity(item, group.Center, group.EntitySize);
        }

        EssenceContainer.RemoveAllChildren();
        foreach (var (type, amount) in info.Essences)
        {
            var essenceControl = new CEEssenceAmountControl { SetSize = new Vector2(EssenceIconSize, EssenceIconSize) };
            essenceControl.SetEssence(type, amount);
            EssenceContainer.AddChild(essenceControl);

            if (_prototype.TryIndex(type, out var essenceProto))
                _searchableExtras.Add(essenceProto.Name);
        }
    }

    /// <summary>
    /// Positions a control so its own center sits at <paramref name="center"/>.
    /// </summary>
    private void PlaceCentered(Control control, Vector2 center)
    {
        DiagramRoot.AddChild(control);
        LayoutContainer.SetPosition(control, center - control.MinSize / 2f);
    }

    private void PlaceAboveEntity(Control control, Vector2 entityCenter, float entitySize)
    {
        PlaceCentered(control, entityCenter - new Vector2(0f, entitySize / 4f));
    }

    private static Vector2 EntityViewScale(float targetSize)
    {
        var factor = targetSize / EyeManager.PixelsPerMeter;
        return new Vector2(factor, factor);
    }

    private EntityPrototypeView CreateEntityIcon(EntProtoId proto, float size)
    {
        var view = new EntityPrototypeView
        {
            MinSize = new Vector2(size, size),
            Scale = EntityViewScale(size),
            MouseFilter = MouseFilterMode.Stop,
            ToolTip = _prototype.TryIndex(proto, out var protoData) ? protoData.Name : proto.Id,
            // Faded so the item resting on top (drawn separately, full opacity) reads as the focus.
            Modulate = Color.White.WithAlpha(0.3f),
        };
        view.SetPrototype(proto);
        return view;
    }

    private Control CreateRequirementIcon(CEResourceRequirement requirement, float size)
    {
        var tooltip = requirement.GetRequirementTitle(_prototype);

        if (requirement.GetRequirementTexture(_prototype) is { } texture)
        {
            return new TextureRect
            {
                Texture = _sprite.Frame0(texture),
                MinSize = new Vector2(size, size),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                MouseFilter = MouseFilterMode.Stop,
                ToolTip = tooltip,
            };
        }

        if (requirement.GetRequirementEntityView(_prototype) is { } entityView)
        {
            var view = new EntityPrototypeView
            {
                MinSize = new Vector2(size, size),
                Scale = EntityViewScale(size),
                MouseFilter = MouseFilterMode.Stop,
                ToolTip = tooltip,
            };
            view.SetPrototype(entityView);
            return view;
        }

        return new Control { MinSize = new Vector2(size, size) };
    }
}
