using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared._CE.Cooking.Prototypes;
using Content.Shared._CE.Cooking.Requirements;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Content.Shared.Tag;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._CE.Guidebook.Controls;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class CEGuideCookingRecipeEmbed : PanelContainer, IDocumentTag, ISearchableControl
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    private SpriteSystem _sprite = default!;
    private ISawmill _sawmill = default!;

    public CEGuideCookingRecipeEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MouseFilter = MouseFilterMode.Stop;
        _sprite = _entity.System<SpriteSystem>();
        _sawmill = _logManager.GetSawmill("guidebook.ce_cooking_recipe");
    }

    public CEGuideCookingRecipeEmbed(CECookingRecipePrototype recipe) : this()
    {
        GenerateControl(recipe);
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Recipe", out var id))
        {
            _sawmill.Error("CE cooking recipe embed tag is missing Recipe argument");
            return false;
        }

        if (!_prototype.TryIndex<CECookingRecipePrototype>(id, out var recipe))
        {
            _sawmill.Error($"Specified recipe prototype \"{id}\" is not a valid CECookingRecipe prototype");
            return false;
        }

        GenerateControl(recipe);
        control = this;
        return true;
    }

    private void GenerateControl(CECookingRecipePrototype recipe)
    {
        GenerateHeader(recipe);
        GenerateRequirements(recipe);
        GenerateCookTime(recipe.CookingTime);
        GenerateDescription(recipe);
    }

    private void GenerateHeader(CECookingRecipePrototype recipe)
    {
        var layer = recipe.FoodData.Visuals.First();

        if (layer.RsiPath is null && layer.State is null)
            _sawmill.Warning($"CE cooking recipe \"{recipe.ID}\" has no valid visual data.");

        if (layer is { RsiPath: not null, State: not null })
        {
            IconTexture.Visible = true;
            IconTexture.Texture = _sprite.Frame0(new SpriteSpecifier.Rsi(new ResPath(layer.RsiPath), layer.State));
            IconTexture.Modulate = layer.Color ?? Color.White;
        }
        else
        {
            IconTexture.Visible = false;
        }

        var nameKey = recipe.FoodData.Name ?? "ce-guidebook-cooking-unknown-food-name";
        ResultName.SetMarkup(Loc.GetString(nameKey));
    }

    private void GenerateDescription(CECookingRecipePrototype recipe)
    {
        if (recipe.FoodData.Desc is not { } descKey)
        {
            ResultDescription.Visible = false;
            return;
        }

        ResultDescription.Visible = true;
        ResultDescription.SetMarkup(Loc.GetString(descKey));
    }

    private void GenerateCookTime(TimeSpan time)
    {
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("ce-guidebook-cooking-cook-time", ("time", time)));
        msg.Pop();
        CookTimeLabel.SetMessage(msg);
    }

    private void GenerateRequirements(CECookingRecipePrototype recipe)
    {
        RequirementsContainer.RemoveAllChildren();

        if (recipe.Requirements.Count == 0)
        {
            AddRequirementLine(Loc.GetString("ce-guidebook-cooking-requirement-none"));
            return;
        }

        foreach (var requirement in recipe.Requirements)
        {
            switch (requirement)
            {
                case AlwaysMet:
                    AddRequirementLine(Loc.GetString("ce-guidebook-cooking-requirement-any"));
                    break;

                case TagRequired tagRequired:
                    AddRequirementLine(Loc.GetString(
                        "ce-guidebook-cooking-requirement-tag-required",
                        ("tags", FormatTags(tagRequired.Tags))));
                    break;

                case TagBlocked tagBlocked:
                    AddRequirementLine(Loc.GetString(
                        "ce-guidebook-cooking-requirement-tag-blocked",
                        ("tags", FormatTags(tagBlocked.Tags))));
                    break;

                case ReagentRequired reagentRequired:
                    AddRequirementLine(Loc.GetString(
                        "ce-guidebook-cooking-requirement-reagent-required",
                        ("reagents", FormatReagents(reagentRequired.Reagents)),
                        ("amount", FormatAmount(reagentRequired.Amount))));
                    break;

                default:
                    _sawmill.Warning($"Unknown CE cooking requirement type: {requirement.GetType().Name}");
                    AddRequirementLine(Loc.GetString("ce-guidebook-cooking-requirement-unknown"));
                    break;
            }
        }
    }

    private void AddRequirementLine(string text)
    {
        var label = new RichTextLabel();
        label.SetMarkup(text);
        RequirementsContainer.AddChild(label);
    }

    private string FormatTags(IEnumerable<ProtoId<TagPrototype>> tags)
    {
        return string.Join(", ", tags.Select(t => t.Id));
    }

    private string FormatReagents(IEnumerable<ProtoId<ReagentPrototype>> reagents)
    {
        var names = new List<string>();
        foreach (var reagentId in reagents)
        {
            if (_prototype.TryIndex(reagentId, out var reagent))
                names.Add(reagent.LocalizedName);
            else
                names.Add(reagentId.Id);
        }

        return string.Join(", ", names);
    }

    private static string FormatAmount(FixedPoint2 amount)
    {
        return amount.ToString();
    }
}
