using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared._CE.Cooking.Prototypes;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._CE.Guidebook.Controls;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class CEGuideCookingRecipeEmbed : PanelContainer, IDocumentTag, ISearchableControl
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    private readonly SpriteSystem _sprite = default!;
    private readonly ISawmill _sawmill = default!;

    public CEGuideCookingRecipeEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MouseFilter = MouseFilterMode.Stop;
        _sprite = _entity.System<SpriteSystem>();
        _sawmill = _logManager.GetSawmill("guidebook.ce_cooking_recipe");
    }

    public CEGuideCookingRecipeEmbed(CECookingRecipePrototype recipe) : this()
    {
        GenerateControl(recipe);
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Recipe", out var id))
        {
            _sawmill.Error("CE cooking recipe embed tag is missing Recipe argument");
            return false;
        }

        if (!_prototype.TryIndex<CECookingRecipePrototype>(id, out var recipe))
        {
            _sawmill.Error($"Specified recipe prototype \"{id}\" is not a valid CECookingRecipe prototype");
            return false;
        }

        GenerateControl(recipe);
        control = this;
        return true;
    }

    private void GenerateControl(CECookingRecipePrototype recipe)
    {
        GenerateHeader(recipe);
        GenerateRequirements(recipe);
        GenerateDescription(recipe);
        GenerateEffects(recipe);
    }

    private void GenerateEffects(CECookingRecipePrototype recipe)
    {
        if (recipe.FoodData?.StatusEffects == null || recipe.FoodData.StatusEffects.Count == 0)
        {
            EffectsContainer.Visible = false;
            return;
        }

        EffectsContainer.Visible = true;
        EffectsContainer.RemoveAllChildren();

        foreach (var (effectProto, basePower) in recipe.FoodData.StatusEffects)
        {
            if (!_prototype.Resolve(effectProto, out var indexedEffect))
                continue;

            var strength = Math.Max(recipe.GetComplexity(), 1);
            var strengthText = MathF.Round(strength).ToString();

            var label = new RichTextLabel();
            var text = Loc.GetString("ce-guidebook-cooking-effect-line", ("effect", indexedEffect.Name), ("strength", strengthText));
            label.SetMarkup(text);
            EffectsContainer.AddChild(label);
        }
    }

    public void SetPlateSprite(string rsiPath, string state)
    {
        try
        {
            var texture = _sprite.Frame0(new SpriteSpecifier.Rsi(new ResPath(rsiPath), state));
            PlateTextureRect.Texture = texture;
            PlateTextureRect.Visible = true;
        }
        catch (Exception e)
        {
            _sawmill.Warning($"Failed to load plate sprite {rsiPath}:{state}: {e.Message}");
            PlateTextureRect.Visible = false;
        }
    }

    private void GenerateHeader(CECookingRecipePrototype recipe)
    {
        var layer = recipe.FoodData.Visuals.FirstOrDefault();

        if (layer is null)
            return;

        if (layer.RsiPath is null && layer.State is null)
            _sawmill.Warning($"CE cooking recipe \"{recipe.ID}\" has no valid visual data.");

        if (layer is { RsiPath: not null, State: not null })
        {
            IconTexture.Visible = true;
            IconTexture.Texture = _sprite.Frame0(new SpriteSpecifier.Rsi(new ResPath(layer.RsiPath), layer.State));
            IconTexture.Modulate = layer.Color ?? Color.White;
        }
        else
        {
            IconTexture.Visible = false;
        }

        var nameKey = recipe.FoodData.Name ?? "ce-guidebook-cooking-unknown-food-name";
        ResultName.SetMarkup(Loc.GetString(nameKey));
    }

    private void GenerateDescription(CECookingRecipePrototype recipe)
    {
        if (recipe.FoodData.Desc is not { } descKey)
        {
            ResultDescription.Visible = false;
            return;
        }

        ResultDescription.Visible = true;
        ResultDescription.SetMarkup(Loc.GetString(descKey));
    }

    private void GenerateRequirements(CECookingRecipePrototype recipe)
    {
        RequirementsContainer.RemoveAllChildren();

        if (recipe.Requirements.Count == 0)
        {
            AddRequirementLine(Loc.GetString("ce-guidebook-cooking-requirement-none"));
            return;
        }

        foreach (var requirement in recipe.Requirements)
        {
            AddRequirementLine(requirement.GetGuidebookDescription(_prototype));
        }
    }

    private void AddRequirementLine(string text)
    {
        var label = new RichTextLabel();
        label.SetMarkup(text);
        RequirementsContainer.AddChild(label);
    }
}
