- type: secretDepartment
  id: CENightmares
  name: ce-secret-department-nightmares-name
  description: ce-secret-department-nightmares-description
  color: "#922525"
  weight: 0
  membersRecognizeEachOther: true
  roles:
  - CEWerewolf
  objectives: !type:EntSelector
    id: CEObjectiveNightmareSphereCollapse

- type: secretDepartment
  id: CECity
  name: ce-secret-department-city-name
  description: ce-secret-department-city-description
  color: "#87b7ff"
  weight: 0
  roles:
  - CECivilian
  - CEThief
  - CEMurkwalker
  - CELover
  objectives: !type:EntSelector
    id: CEObjectiveCityRestoreLucsonSphere
