- type: entity
  abstract: true
  parent: Clothing
  id: CEClothingCloakBase
  categories: [ ForkFiltered ]
  components:
  - type: Clothing
    equipDelay: 1
    unequipDelay: 1
    slots:
    - cloak
  - type: Sprite
    state: icon

