- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: false # Baseline - disable vanilla content
  objective: roles-antag-thief-objective
  guides: [ Thieves ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h

- type: startingGear
  id: ThiefGear
  storage:
    back:
    - ThiefBeacon
    - SatchelThief
