using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.SkillTree.Ui;

[GenerateTypedNameReferences]
public sealed partial class CESkillTreeButtonControl : Control
{
    public event Action? OnPressed;

    public CESkillTreeButtonControl(Color color, string label, float points, Texture? icon)
    {
        RobustXamlLoader.Load(this);

        ColorPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = color };

        if (points > 0)
        {
            PointsIcon.Texture = icon;
            PointsIcon.Visible = icon != null;
            TreeLabel.Text = $"{points} {label}";
        }
        else
        {
            PointsIcon.Visible = false;
            TreeLabel.Text = label;
        }

        MainButton.OnPressed += _ => OnPressed?.Invoke();
    }
}
