using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.SkillTree.Ui;

[GenerateTypedNameReferences]
public sealed partial class CESkillNodeTooltip : PanelContainer
{
    public CESkillNodeTooltip()
    {
        RobustXamlLoader.Load(this);

        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = StyleNano.PanelDark,
            BorderColor = StyleNano.ButtonColorHovered,
            BorderThickness = new Thickness(1f),
        };
    }
}
