- type: entity
  abstract: true
  parent: Clothing
  id: CEClothingPantsBase
  categories: [ ForkFiltered ]
  description: Pants to cover my thighs from the cold.
  components:
  - type: Clothing
    equipDelay: 1
    unequipDelay: 1
    slots:
    - pants
  - type: Sprite
    state: icon
  #- type: Butcherable
  #  butcheringType: Knife
  #  spawned:
  #  - id: CECloth1
  #    amount: 1

- type: entity
  parent: CEClothingPantsBase
  id: CEClothingPantsDress
  abstract: true
  description: A roomy, feminine skirt
  components:
  - type: Clothing
    equipDelay: 1.5
