using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.Skill.Ui.Window;

[GenerateTypedNameReferences]
public sealed partial class CESkillWindow : DefaultWindow
{
    public CESkillWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
