using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.Skill.Ui;

[GenerateTypedNameReferences]
public sealed partial class CESkillTreeButtonControl : Control
{
    public event Action? OnPressed;

    public CESkillTreeButtonControl(Color color, string label, float skillpoints, Texture? icon)
    {
        RobustXamlLoader.Load(this);

        ColorPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
        if (skillpoints > 0)
        {
            SkillPointImage.Texture = icon;
            SkillPointImage.Visible = true;
            SkillTreeLabel.Text = $"{skillpoints} {label}";
        }
        else
        {
            SkillPointImage.Visible = false;
            SkillTreeLabel.Text = $"{label}";
        }

        MainButton.OnPressed += args => OnPressed?.Invoke();
    }
}
