using Content.Client._CE.Skill;
using Content.Shared._CE.Skill.Components;
using Content.Shared._CE.Skill.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._CE.Skill.Ui;

/// <summary>
/// A single learned skill's card in the character menu: icon, title, description, and - if the
/// skill has a <see cref="CESkillDescriptor"/> - a colored badge naming its source. Mirrors
/// <c>CEObjectiveControl</c>, minus the progress bar (skills don't have progress).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CESkillControl : BoxContainer
{
    [Dependency] private EntityManager _ent = default!;
    private readonly CEClientSkillSystem _skill;
    private readonly SpriteSystem _sprite;

    public CESkillControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _skill = _ent.System<CEClientSkillSystem>();
        _sprite = _ent.System<SpriteSystem>();
    }

    public void SetSkill(EntityUid target, ProtoId<CESkillPrototype> skill)
    {
        TitleLabel.Text = _skill.GetSkillName(skill);
        DescriptionLabel.Text = _skill.GetSkillDescription(skill);

        Icon.Texture = _skill.GetSkillIcon(skill) is { } icon ? _sprite.Frame0(icon) : null;

        if (_skill.GetDescriptor(target, skill) is { } descriptor)
        {
            OwnerPanel.Visible = true;
            OwnerPanel.ModulateSelfOverride = descriptor.Color;

            var luminance = 0.2126f * descriptor.Color.R + 0.7152f * descriptor.Color.G + 0.0722f * descriptor.Color.B;
            OwnerLabel.Text = Loc.GetString(descriptor.Name);
            OwnerLabel.FontColorOverride = luminance > 0.5f ? Color.Black : Color.White;

            if (descriptor.Tooltip is { } tooltipId)
            {
                var tooltip = new Tooltip { MaxWidth = 400 };
                tooltip.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString(tooltipId)));
                TooltipSupplier = _ => tooltip;
            }
            else
            {
                TooltipSupplier = null;
            }
        }
        else
        {
            OwnerPanel.Visible = false;
            TooltipSupplier = null;
        }

        ResizeTitle();
    }

    private void ResizeTitle()
    {
        TitleLabel.MaxWidth = Header.Width - OwnerPanel.Width - Icon.Width;
    }

    protected override void Resized()
    {
        base.Resized();

        ResizeTitle();
    }
}
