using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.UserInterface.Systems.Character.Tabs;

[GenerateTypedNameReferences]
public sealed partial class CECharacterSkillsTab : ScrollContainer
{
    public CECharacterSkillsTab()
    {
        RobustXamlLoader.Load(this);
    }
}
