using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.UserInterface.Systems.Character.Tabs;

[GenerateTypedNameReferences]
public sealed partial class CECharacterInventoryTab : BoxContainer
{
    private Direction _rotation = Direction.South;

    public CECharacterInventoryTab()
    {
        RobustXamlLoader.Load(this);

        // A lighter border than the theme's own PanelInsetDark (whose border blends into its
        // own dark fill) so the portrait panel actually reads as a distinct frame.
        PortraitPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = StyleNano.PanelDark,
            BorderColor = StyleNano.ButtonColorHovered,
            BorderThickness = new Thickness(2f),
        };

        RotateLeft.OnPressed += _ => Rotate(TurnCardinal(_rotation, -1));
        RotateRight.OnPressed += _ => Rotate(TurnCardinal(_rotation, 1));
    }

    private void Rotate(Direction direction)
    {
        _rotation = direction;
        SpriteView.OverrideDirection = _rotation;
    }

    // Direction.TurnCw/TurnCcw step through all 8 compass points (45 degrees);
    // most sprites only have 4 facings, so we step directly between cardinals (90 degrees).
    private static Direction TurnCardinal(Direction current, int steps)
    {
        return (Direction)(((int) current + steps * 2 + 8) % 8);
    }
}
