using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.UserInterface.Systems.Character.Tabs;

[GenerateTypedNameReferences]
public sealed partial class CECharacterSkillsTab : BoxContainer
{
    public CECharacterSkillsTab()
    {
        RobustXamlLoader.Load(this);

        // Keeps the parallax drifting opposite to the graph's own pan/zoom offset.
        GraphControl.OnOffsetChanged += offset =>
        {
            ParallaxBackground.Offset = -offset * 0.25f + new Vector2(1000, 1000);
        };
    }
}
