using Content.Client.UserInterface.Systems.Inventory;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.UserInterface.Systems.Character.Tabs;

[GenerateTypedNameReferences]
public sealed partial class CECharacterInventoryTab : BoxContainer
{
    private Direction _rotation = Direction.South;

    public CECharacterInventoryTab()
    {
        RobustXamlLoader.Load(this);

        UserInterfaceManager.GetUIController<InventoryUIController>().RegisterInventoryBarContainer(InventorySlots);

        RotateLeft.OnPressed += _ => Rotate(TurnCardinal(_rotation, -1));
        RotateRight.OnPressed += _ => Rotate(TurnCardinal(_rotation, 1));
    }

    private void Rotate(Direction direction)
    {
        _rotation = direction;
        SpriteView.OverrideDirection = _rotation;
    }

    // Direction.TurnCw/TurnCcw step through all 8 compass points (45 degrees);
    // most sprites only have 4 facings, so we step directly between cardinals (90 degrees).
    private static Direction TurnCardinal(Direction current, int steps)
    {
        return (Direction)(((int) current + steps * 2 + 8) % 8);
    }
}
