using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE.UserInterface.Systems.Character.Tabs;

[GenerateTypedNameReferences]
public sealed partial class CECharacterInventoryTab : BoxContainer
{
    public CECharacterInventoryTab()
    {
        RobustXamlLoader.Load(this);
    }
}
