- type: entity
  abstract: true
  id: CEConstructibleMachine
  components:
  - type: Animateable
  - type: Machine
  - type: ContainerContainer
    containers:
      machine_board: !type:Container
      machine_parts: !type:Container
  - type: Construction
    graph: CEMachine
    node: machine
    containers:
    - machine_parts
    - machine_board

- type: entity
  abstract: true
  parent: BaseMachine
  id: CEBaseMachinePowered
  components:
  - type: ApcPowerReceiver
    powerLoad: 1
  - type: ExtensionCableReceiver
    receptionRange: 0
